SUB1

{
	TYPE	"bark"
	DESCR	"Opièí bestie"
	SUB "ab2a0mu3" { TEXT "Chci to hned...zmizet...!" }
	SUB "ab2a1__1" { TEXT "Eeeh! Co to je?" }
	SUB "ab2a1__2" { TEXT "Eeeh?" }
	SUB "ab2a1__3" { TEXT "Kdo je tam?" }
	SUB "ab2a1__6" { TEXT "Co tam je?" }
	SUB "ab2a1_w1" { TEXT "Nìco tam, myslíš?" }
	SUB "ab2a1h_1" { TEXT "Kdo ten hluènı?" }
	SUB "ab2a1h_3" { TEXT "Kdo to øekl?" }
	SUB "ab2a1hw1" { TEXT "Nìco... hluèet!" }
	SUB "ab2a1hw2" { TEXT "Poslouchat, brate! Poslouchat!" }
	SUB "ab2a1hw3" { TEXT "Slyšíš to?" }
	SUB "ab2a1hw4" { TEXT "Slyšíš hluk?" }
	SUB "ab2a1v_1" { TEXT "Vidíš co já?" }
	SUB "ab2a1vw1" { TEXT "Co to? Vidíš to?" }
	SUB "ab2a1vw2" { TEXT "Vidíš ty to?" }
	SUB "ab2a1vw3" { TEXT "Hej, koukni! Nìco?" }
	SUB "ab2a1vw4" { TEXT "Vidíš to, brate?" }
	SUB "ab2a1vw5" { TEXT "Vidí nìco taky?" }
	SUB "ab2a2__1" { TEXT "Kdo je tam? Vyleze." }
	SUB "ab2a2__2" { TEXT "Uka se, taføe!" }
	SUB "ab2a2__3" { TEXT "Vylez, vylez, myšáku zlodìjská!" }
	SUB "ab2a2__4" { TEXT "Staèí! Vylez ven, hned!" }
	SUB "ab2a2__5" { TEXT "U vím, e jsi tam!" }
	SUB "ab2a2__6" { TEXT "Našli nenašli... Další jsi ty!" }
	SUB "ab2a2h_1" { TEXT "Teï ukáeš, pak krvácíš! Mì to jedno!" }
	SUB "ab2a2h_2" { TEXT "Tentokrát ublíil já!" }
	SUB "ab2a2h_3" { TEXT "Slyšel to. Slyšel tì!" }
	SUB "ab2a2v_1" { TEXT "Vidìl to!" }
	SUB "ab2a3b_1" { TEXT "Vidím, co udìlal!" }
	SUB "ab2a3na1" { TEXT "Vetøelec tady!" }
	SUB "ab2a3na2" { TEXT "Ani hnout, ty!" }
	SUB "ab2a3na3" { TEXT "Haah, mám tì!" }
	SUB "ab2a3na4" { TEXT "Trefil tì...!" }
	SUB "ab2a3na5" { TEXT "Našel tì teï." }
	SUB "ab2a3na6" { TEXT "Tady myška: boj koèky!" }
	SUB "ab2a3na7" { TEXT "Teï u není taková lest!" }
	SUB "ab2chgw3" { TEXT "Èlovìk útoèí!" }
	SUB "ab2chgw4" { TEXT "Na nìj!" }
	SUB "ab2det_1" { TEXT "Chce schovat?" }
	SUB "ab2det_2" { TEXT "Zalez, masáèi!" }
	SUB "ab2det_3" { TEXT "Gaak! Malé mìkké bøíško!" }
	SUB "ab2det_4" { TEXT "Dìsím tì, co?" }
	SUB "ab2detw1" { TEXT "Dìsí se nás?" }
    SUB "ab2detw2" { TEXT "Masáè srab!"	}
	SUB "ab2hhi_3" { TEXT "Ech! K èertu tvé oko!" }
	SUB "ab2hit_1" { TEXT "Cítím tvé krvavé maso!" }
	SUB "ab2hit_2" { TEXT "Krev masáèe sladká!" }
	SUB "ab2hit_3" { TEXT "Zelené pšenièné snopy pøinášejí myši!" }
	SUB "ab2hit_4" { TEXT "Krmíš listí!" }
	SUB "ab2hit_5" { TEXT "Tvá horká krev nám prší!" }
	SUB "ab2hit_6" { TEXT "Chcípni, masáèi!" }
	SUB "ab2hitw1" { TEXT "Padá! Padá!" }
	SUB "ab2hitw2" { TEXT "Rozsekej ho! Rozsekej ho, brate!" }
	SUB "ab2hitw3" { TEXT "Sleduj, jak padá!" }
	SUB "ab2hlow1" { TEXT "Ten masáè mì zabije!" }
	SUB "ab2hlow2" { TEXT "A mì nezabije!" }
	SUB "ab2hnd_1" { TEXT "Zkus to znovu, slabı blázne!" }
	SUB "ab2hnd_2" { TEXT "Heh heh heh heh! Moje krev je pro Pána, ne pro tebe!" }
	SUB "ab2hnd_3" { TEXT "Mì to nebolí!" }
	SUB "ab2lar_1" { TEXT "Eee, opravíš to?" }
	SUB "ab2lar_2" { TEXT "Kdo to dìlá? Tady!" }
	SUB "ab2los_1" { TEXT "Stínovı èmuchal! Na tvé stopì!" }
	SUB "ab2los_2" { TEXT "Hej! Vra se!" }
	SUB "ab2los_3" { TEXT "Vra se, ty!" }
	SUB "ab2los_4" { TEXT "Ještì neprohrál!" }
	SUB "ab2los_5" { TEXT "Utíkej, myško! I tak chytím!" }
	SUB "ab2mis_1" { TEXT "Eeeeh.... Zlodìj!" }
	SUB "ab2mis_2" { TEXT "Kde to je? Zlodìj! Zlodìj!" }
	SUB "ab2mis_3" { TEXT "Eeeh, mìl tu bıt?" }
	SUB "ab2rbod1" { TEXT "Bacha na vrahy!" }
	SUB "ab2rbod2" { TEXT "Chodí tu zabiják!" }
	SUB "ab2rbod3" { TEXT "Èlovìk nám bere ivot!" }
	SUB "ab2rint1" { TEXT "Bacha! Èlovìk tu slídí!" }
	SUB "ab2rint2" { TEXT "Videl masáèe. Dávej taky bacha." }
	SUB "ab2rint3" { TEXT "Nedá spát, brate. Masáè slídí kolem!" }
	SUB "ab2rmis1" { TEXT "Najdem u nás lupièe!" }
	SUB "ab2rmis2" { TEXT "Hledat ty, kdo berou naše poklady!" }
	SUB "ab2rmis3" { TEXT "Øekni bratùm: Bacha na zlodìje!" }
	SUB "ab2roth1" { TEXT "Zùstaneš vzhùru! Nìco se dìje." }
	SUB "ab2roth2" { TEXT "Hlídej, masitého narušitele." }
	SUB "ab2roth3" { TEXT "Hlídej, nìco divného." }
	SUB "ab2roth4" { TEXT "Nìco dìje! Vetøelec plíí kolem!" }
	SUB "ab2runa1" { TEXT "Pøichází sem! Pomoz!" }
	SUB "ab2runa2" { TEXT "Masáè hrozí!" }
	SUB "ab2runa3" { TEXT "Tady, brate! Tady!" }
	SUB "ab2runa4" { TEXT "Pomoz mi! Tady!" }
	SUB "ab2sec_1" { TEXT "Cizinec u nás!" }
	SUB "ab2sec_2" { TEXT "Slídí tady!" }
	SUB "ab2sec_3" { TEXT "Hej, pozor na slídila!" }
	SUB "ab2sec_4" { TEXT "Di varuj pøed tímhle." }
	SUB "ab2sec_5" { TEXT "Dostal ses sem, co?" }
	SUB "ab2sma_1" { TEXT "Kdo se tu dìje?" }
	SUB "ab2sma_2" { TEXT "To není správné!" }
	SUB "ab2sma_3" { TEXT "Leze do míst, kam nemá!" }
	SUB "ab2telc1" { TEXT "Tady je! Tam!" }
	SUB "ab2telc2" { TEXT "Rozsekat masáèe, pøímo tady!" }
	SUB "ab2telc3" { TEXT "Našel ho!" }
	SUB "ab2telc4" { TEXT "Tudy! Zastaví èlovìka!" }
	SUB "ab2telc5" { TEXT "Tady ho najdi! Chytí ho!" }
	SUB "ab2telc6" { TEXT "Zase vidím èlovìka!" }
	SUB "ab2telr1" { TEXT "Hej, slídil, tady!" }
	SUB "ab2telr2" { TEXT "Najdi nám slídila, tady." }
	SUB "ab2telr3" { TEXT "Èlovìk snaí proplíit, ale já ho chytím!" }
	SUB "ab2telr4" { TEXT "Mám vetøelce!" }
} 
