SUB1

{
	TYPE "convo"
	DESCR "Šejdíø"
	SUB "condone" { TEXT "Hotovo! Vláda mansy kamennıch slepıch bláznù pøipadá mnì!" }
	SUB "confail" { TEXT "Zrada!" }
	SUB "confin" { TEXT "Otevøi se pro mne! Otevøi se mi! Otevøi mi smìr! Otevøi mi cestu! Otevøi se pro mne! Otevøi!" }
	SUB "conpom1" { TEXT "Révo, kru se a ros! Zeleò se a viò, svazuj a škr! Listy rozviò, trnma obras, roucej zeï! Viò se dál, vše pøikryj teï! Listy mé, zvolete révu, zvolejte zeleò, vyeòte se na svìtlo svìta!" }
	SUB "conpom2" { TEXT "Bouøe èerná duj! Víøivı poryv, dešové vìtry proudí! Tlaèí prach, bouøkové mraky rostou!Darksie mraky, blesky metají! Mlnı rubáš, mrznoucí sníh!Zavolej bouøi, zavolej šeï: pøiveï svìt starou cestou!" }
	SUB "conpom3" { TEXT "Plamen, spalující ár!Ploty ohoøelé, plamennı list!Èernı dehet, lidské maso! Tavící se ozubená kola, tanec a skok!Strach lidojedù, pøijïte sklízet!Zavolejte oheò, zavolejte rudou: vyveïte ven minulost ne mrtvou!"}
	SUB "conpom4" { TEXT "Pøíliv, pøíliv a odliv!Øíèní záplavy, déš a bouøe!Churny bahno, pøehrady prolomit všechny!Moøské vlny omıvají, bainatá smrš!Kanalizace šumí, odtokové roury se zadrhávají! Zavolej vlnu, zavolej modø: vyvolej svìt znovu!"}
	SUB "conpom5" { TEXT "Kámen, drtit a tøást! Tøíští se dladice, tøesou se sloupy! Cihly se rozpadají, tøíští a vloèkují! Tmavá pùda, okna se rozbíjejí! Zemská døina, zeï se rozpadá! Zavolej zemi, zavolej hnìdou: pøiveï zpìt svìt svrenı!"}
	SUB "conpom6" { TEXT "Noc, dusí svìtlo!Èerná rozbij lampu, skoncuj s jasnou!Rosa a vlhko, dusí tìsnì! Tma ve skrytu, bláznivı zrak!Zùstaò uvnitø, boj se noci!Zavolej tmu, zavolej èernou: bringie ven! Já ji volám zpátky!"}
	SUB "consee1" { TEXT "Garrett! Mùj zlodìjskı blázne? Ještì iješ?" }
	SUB "consee2" { TEXT "Pøichází honba za tvou smrtí, Garrette? Lepší pro tebe je zùstat nahoøe!" }
	SUB "consee3" { TEXT "Pøijï si zavolat svou smrt!" }
	SUB "consee4" { TEXT "Tvoje role je splnìna!" }
} 
