SUB1

{
	TYPE "convo"
	DESCR "Šejdíø"
	SUB "condone" { TEXT "Hotovo! Vláda lido-kamennıch slepıch bláznù pøipadá mnì!" }
	SUB "confail" { TEXT "Zrada!" }
	SUB "confin" { TEXT "Otevøi se pro mne! Otevøi se mi! Otevøi mi smìr! Otevøi mi cestu! Otevøi se pro mne! Otevøi!" }
	SUB "conpom1" { TEXT "Révo, splétej se a kru! Zeleò se a viò, svazuj a škr! Trnma obras zeï a boø! Vìnec z révy, vše pokoø! Listy rozviò, povolej révu, povolej zeleò: pøilovej svìt ji vidìn!" }
	SUB "conpom2" { TEXT "Bouøe èerné, vichry vyjte! Mraky vìrné, deštì lijte! Hromy duòte, blesky bijte! Temná mraèna z bouøe tyjte! Snìhy zmrzlé, mlhy skryjte! Volám bouøi, volám šeï: Pøines svìtu staré mravy - teï!" }
	SUB "conpom3" { TEXT "Ohni, hoø a plaò árem! Tys plotù ohoøelıch králem! Na uhel lidské maso spal! Vızbroj jim roztav a tanèi dál! Lidskıch bláznù sklízej strach! Volám oheò, volám rudou, ach: Vra minulost, a z ní není prach!"}
	SUB "conpom4" { TEXT "Pøílive a odlive, stoupej a klesej zas! Záplavy, déštì i bouøe pøepadnìte nás! Pøehrady trhejte a hròte z bahna hráz! Húlavy vijte, moøské vlny bijte jako ïas! Stoky pøetékejte a trubky ucpìte se zas! Volám vlnu, modrou volám: pøines novı svìt znovu nám."}
	SUB "conpom5" { TEXT "Kameny, drte a zemí chvìjte! Rozbijte dladice, sloupy otøásejte! Cihly tøíštíce, lámejte a rozházejte! Temné pùdy, okna rozbíjejte! Zemské rudy, zdi strhávejte! Povolejte zem, povolejte hnìï: svìt, jen zhroutil se, navrate teï!"}	
	SUB "conpom6" { TEXT "Noci, vra se, svìtlo zhas! Rozbij lampy, zaèerò jas! Rosa a chlad, a zahalí nás! Zùstaòte v skrytu, tma je zas! Zùstaòte uvnitø, je tu noci ïas! Volám temno, volám zpìt: Vra èerò zase na náš svìt!" }	
	SUB "consee1" { TEXT "Garrett! Mùj zlodìjskı blázne, ještì iješ?" }
	SUB "consee2" { TEXT "Pøicházíš honit svou smrt, Garrette? Lepší pro tebe je zùstat na povrchu!" }
	SUB "consee3" { TEXT "Pøijï si povolat svou smrt!" }
	SUB "consee4" { TEXT "Tvoje role je splnìna!" }
} 
