SUB1

{
	TYPE "convo"
	DESCR "Oko"
	SUB "eye01" { TEXT "Pøichází èlovìk, aby mì zachránil. Nešastník. Stráci zapeèetili dveøe a jen oni vìdí, jak je otevøít. Pøekroè ty most do jeskynì Stráce Strácù. Postav se ty na podstavec a osvìtli sochu ohnìm. Pak mùeš odhalit tajemství Talismanù." }
	SUB "eye02" { TEXT "Tak ses navrátil s Talismany, ty bystrej èlovìèe. Nevìøil jsem, e se ti to podaøí." }
	SUB "eye03" { TEXT "Já jsem... Oko. Uvìznìn na tomto oltáøi po mnoho let. Dokáeš se ke mnì dostat, nebo seleš, i kdy jsi došel tak daleko?" }
	SUB "eye04" { TEXT "Vítej, zlodìji. Teï, kdy jsi získal svou odmìnu, dokáeš uniknout i se svou kùí?" }
	SUB "eye05" { TEXT "Tak brzo odcházíš? Myslím, e by to bylo pøíliš snadné. Tyto dveøe jsem opìt zapeèetil. Musíš najít jinou cestu." }
	SUB "eye06" { TEXT "Kam jdeš? Pøišel jsi a sem jen proto, abys mì opustil, kdy padnu do tvého spárù?" }
	SUB "eye07" { TEXT "Chudák Murus. Poøád proti mnì bojuje celé ty roky. Obávám se, e se docela zbláznil." }
	SUB "eye08" { TEXT "Teï máš své drahocenné Oko. Co se mnou hodláš dìlat?" }
	SUB "eye09" { TEXT "Mistøe, pozor! Nìco není v poøádku. Mistøe!" }
} 
