SUB1

{
	TYPE	"convo"
	DESCR	"Hlídka"
	SUB "sg106201" { TEXT "Zpomaluje však narušitele." }
	SUB "sg106203" { TEXT "No, tahle situace s vázou by ti mohla dopøát veškerou akci, kterou potøebuješ." }
	SUB "SG106400" { TEXT "Donal a Rueben a se klidnì navzájem pozabíjí. Zatímco se budou prát o vázu, nebudou se mi plést do cesty." }
	SUB "SG106402" { TEXT "Jo, ale Donalovi to stejnì neprospìje, protoe klíè od zámku má lord Rueben." }
	SUB "SG107100" { TEXT "Heslo." }
	SUB "SG107102" { TEXT "'Bezpeènost je nepostradatelná, aby se zabránilo odhalení a rozmìlnìní talentu'. Chceš se hádat s pány? A teï to heslo...?" }
	SUB "SG107104" { TEXT "No ještì mi neøekl heslo on." }
	SUB "sg107106" { TEXT "'Bezpeènost je nepostradatelná...'" }
	SUB "SG110101" { TEXT "Jsme tu, abychom hlídali spoleèné prostory a øešili všední hrozby. Mágové se umí bránit sami." }
	SUB "SG110103" { TEXT "Zjistil jsem, e nejlepší bude neptat se. Zlato, co mi dají, mi zodpoví všechny otázky, které mám." }
	SUB "sg110201" { TEXT "Pøípadní narušitelé by mìli doufat, e se k nim dostaneme døív ne mágové." }
	SUB "sg110500" { TEXT "Nazdar Bertrame, jak ti jde první noc na strái?" }
	SUB "sg110502" { TEXT "Hele, kdy se podíváš nahoru na vì, obèas vidíš podivná svìtla a kouø, jak se toèí kolem vrcholkù vìe. Tam se dìjí všechny ty jejich 'speciální' vìci." }
	SUB "sg110504" { TEXT "Buï rád, e se nedostaneš dovnitø. V tìch vìích jsou... nestvùrnosti. Hrají si s ivly zpùsobem, kterému my obyèejní lidé nechceme rozumìt. Já? Jsem šastnìjší tady venku, kde je bezpeèno." }
	SUB "sg112300" { TEXT "Jen aby bylo jasno: kdyby došlo k nìjakım potíím, zdvojnásobíme strá v pokojích paní Valerie." }
	SUB "sg112302" { TEXT "Ale vzhledem k tomu, e jsi stránı a ne zlodìj, je ti jasné, kam máš jít, kdyby došlo k potíím?" }
	SUB "SG112304" { TEXT "Jakoto kapitán si mùeš vybrat, zda budeš hlídat dle libosti. Do té doby si to poslechneme: Kam pùjdeš, kdy nastanou potíe?" }
	SUB "sg112306" { TEXT "Dobøe. A pøestaneš remcat, doporuèuji ti, aby ses pustil do obchùzky."  }
}
{
	TYPE	"bark"
	DESCR	"Hlídka"
	SUB "sg117100" { TEXT "Je èas na oponu, zlodìji!" }
	SUB "sg117101" { TEXT "Doufám, e máš rád tragické konce!" }
	SUB "sg117102" { TEXT "Tak jo, pøedstavení skonèilo, zlodìji!" }
	SUB "SG1A1__1" { TEXT "Hmm... Je tam nìkdo?" }
	SUB "SG1A1__2" { TEXT "Ha... Nìco tam je?" }
	SUB "SG1A1__3" { TEXT "Kdo je tam? Haló?" }
	SUB "SG1A1__4" { TEXT "Co se to tam dìje?" }
	SUB "SG1A1__5" { TEXT "Hej, co to bylo?" }
	SUB "SG1A1__6" { TEXT "Hmm..." }
	SUB "SG1A1_W1" { TEXT "Dívej. Tamhle..." }
	SUB "sg1a1_w2" { TEXT "Psst! Tamhle." }
	SUB "sg1a1h_1" { TEXT "Hmm... Myslel jsem, e jsem nìco zaslechl..." }
	SUB "sg1a1h_2" { TEXT "Co to bylo za zvuk?" }
	SUB "sg1a1h_3" { TEXT "Zvláštní zvuk." }
	SUB "sg1a1hw1" { TEXT "Slyšeli jste nìco?" }
	SUB "sg1a1hw2" { TEXT "Slyšeli jste to?" }
	SUB "sg1a1hw3" { TEXT "Pst! Nìco slyším." }
	SUB "sg1a1hw4" { TEXT "Slyšíš to?" }
	SUB "sg1a1v_1" { TEXT "Hmm... Zdálo se mi, e nìco vidím." }
	SUB "sg1a1v_2" { TEXT "Co jsem to vidìl?" }
	SUB "sg1a1vw1" { TEXT "Vidìl jsi tam nìco?" }
	SUB "sg1a1vw2" { TEXT "Hej! Vidìl jsi tam nìkoho?" }
	SUB "sg1a1vw3" { TEXT "Vidìl jsi to taky?" }
	SUB "sg1a1vw4" { TEXT "Podívej se tam!" }
	SUB "SG1A2__1" { TEXT "Kdo je to tam? Identifikujte se!" }
	SUB "sg1a2__2" { TEXT "Vy tam! Pøedstupte a hlaste se!" }
	SUB "sg1a2__3" { TEXT "Dobøe... co je to?" }
	SUB "sg1a2__4" { TEXT "Kdo se to tam plíí?" }
	SUB "sg1a2__5" { TEXT "Uka se!" }
	SUB "sg1a2h_1" { TEXT "Dobøe, slyším tì! Okamitì vyjdi ven." }
	SUB "sg1a2h_2" { TEXT "Slyšel jsem to! Okamitì stùj!" }
	SUB "sg1a2h_3" { TEXT "Vylez ven! Slyšel jsem to!" }
	SUB "sg1a2se1" { TEXT "Nemysli si, e se mùeš dlouho schovávat!" }
	SUB "sg1a2se2" { TEXT "No tak u pojï... No tak!" }
	SUB "sg1a2se3" { TEXT "Vím, e tu nìkde jsi." }
	SUB "sg1a2se4" { TEXT "Neboj se, já tì najdu!" }
	SUB "sg1a2v_1" { TEXT "Vidím tì tam! Vyjdi ven!" }
	SUB "sg1a3__2" { TEXT "Hej!" }
	SUB "sg1a3b_1" { TEXT "Tys ho zabil! Stùj, kde si." }
	SUB "sg1a3na1" { TEXT "Okamitì stùj a dej ruce nahoru!" }
	SUB "sg1a3na2" { TEXT "Velmi pomalu se otoè a dej ruce za hlavu." }
	SUB "sg1a3na3" { TEXT "Odhoï zbraò! Nehıbej se!" }
	SUB "sg1a3na4" { TEXT "Zastav se!" }
	SUB "sg1a3na5" { TEXT "Hej! Ty tam, nehıbej se!" }
	SUB "sg1a3na6" { TEXT "Stùj, zlodìji, vidím tì tam!" }
	SUB "SG1A3NA7" { TEXT "Stùj, Garrette! Pohni se a jsi mrtvı!" }
	SUB "sg1a3s_1" { TEXT "Hah! Kdo jsi?!" }
	SUB "sg1a3s_2" { TEXT "Hej, odkud jsi pøišel?" }
	SUB "sg1a3s_3" { TEXT "Hej! Stùj, ty taføe!" }
	SUB "sg1a3s_4" { TEXT "Hej!" }
	SUB "sg1a3se1" { TEXT "Vylez a bojuj se mnou!" }
	SUB "sg1a3se2" { TEXT "Jakmile tì najdu, jsi mrtvı!" }
	SUB "sg1a3se3" { TEXT "Vra se sem, ty taføe!" }
	SUB "sg1a3se4" { TEXT "Najdu tì... zatracenì!" }
	SUB "sg1alma1" { TEXT "Do zbranì, všichni!" }
	SUB "sg1alma2" { TEXT "Spuste poplach!" }
	SUB "sg1alma3" { TEXT "Poplach!" }
	SUB "sg1almw1" { TEXT "Jdi! Spusti poplach!" }
	SUB "sg1almw2" { TEXT "Spusti poplach!" }
	SUB "sg1amb_1" { TEXT "Vylez a bojuj!" }
	SUB "sg1amb_2" { TEXT "Bojuj se mnou jako chlap, ty hade!" }
	SUB "sg1amb_3" { TEXT "Kde jsi, ty zbabìlèe?" }
	SUB "sg1amb_4" { TEXT "Pojï na otevøené prostranství a zkus to znovu!" }
	SUB "sg1ambw1" { TEXT "Pomoc, byl jsem zasaen!" }
	SUB "sg1ambw2" { TEXT "Pomoc, byl jsem postøelen!" }
	SUB "sg1ambw3" { TEXT "Uff, ostøelovaè!" }
	SUB "sg1atb_1" { TEXT "Je z tebe polštáøek na špendlíky, taføe!"  }
	SUB "sg1atb_2" { TEXT "Tady máš šíp!" }
	SUB "sg1atb_3" { TEXT "Brzy budeš mít plno dìr!" }
	SUB "sg1atn_1" { TEXT "Tu máš!" }
	SUB "sg1atn_2" { TEXT "Mìj se!" }
	SUB "sg1atw_1" { TEXT "Chcípni, taføe!" }
	SUB "sg1atw_2" { TEXT "Jaké to je?" }
	SUB "sg1atww1" { TEXT "U ho máme!" }
	SUB "sg1bak_1" { TEXT "Hmm... Teï u tam nic není." }
	SUB "sg1bak_2" { TEXT "Teï u je tu klid." }
	SUB "sg1bak_3" { TEXT "No jo... To asi nic nebylo." }
	SUB "sg1bak_4" { TEXT "Hmm... To musely bıt krysy." }
	SUB "sg1bak_5" { TEXT "Aaahh, teï nic nevidím." }
	SUB "sg1bak_6" { TEXT "Asi jen vítr." }
	SUB "sg1bak_7" { TEXT "Hmm... Hluk pøestal. Asi to nic nebylo." }
	SUB "sg1bak_8" { TEXT "Teï u nic." }
	SUB "sg1bkd_1" { TEXT "Pøíštì poteèe krev!" }
	SUB "sg1bkd_2" { TEXT "Myslíš si, jak jsi chytrı!" }
	SUB "sg1bkd_3" { TEXT "Sakra, jsi rychlı!" }
	SUB "sg1bkdw1" { TEXT "Nedostaneme se dál." }
	SUB "sg1blk_1" { TEXT "Nejsi tak rychlı, co?" }
	SUB "sg1blk_2" { TEXT "Myslel sis, es mì dostal!" }
	SUB "sg1blk_3" { TEXT "Tentokrát ne!" }
	SUB "sg1blkw1" { TEXT "Nejseš takovı tvrïák, co?" }
	SUB "sg1bod_1" { TEXT "Poèkej! Poèkej! Vrada!" }
	SUB "sg1bod_2" { TEXT "Hej! Vrahoun! Vrada!" }
	SUB "sg1bod_3" { TEXT "Vrada!" }
}
{
	TYPE	"convo"
	DESCR	"Hlídka"
	SUB "sg1c0601" { TEXT "Hraješ ještì?" }
	SUB "sg1c0603" { TEXT "Na, nechám tì hádat jako prvního." }
	SUB "sg1c0605" { TEXT "No tak, nízké sázky! Jen jednou." }
	SUB "sg1c0607" { TEXT "Dobrá tedy: Kámen nebo mince?" }
	SUB "sg1c0609" { TEXT "Ne!" }
	SUB "sg1c0611" { TEXT "Dvojnásobek nebo nic?" }
	SUB "sg1c0613" { TEXT "Mince!" }
	SUB "sg1c0615" { TEXT "Ještì jednou, dvojnásobek nebo nic?" }
	SUB "sg1c0701" { TEXT "V této práci se nikdy nic nedìje!" }
	SUB "sg1c0703" { TEXT "Taková nuda, jen obchùzka v kruhu." }
	SUB "sg1c0705" { TEXT "Onehdá jsem aspoò potkával lidi." }
	SUB "sg1c0707" { TEXT "Aaah! Nuda, nuda, nuda...." }
	SUB "sg1c0801" { TEXT "Dostal jsi dnes veèer fazoláka?" }
	SUB "sg1c0803" { TEXT "Škoda. Byl dobrı." }
	SUB "sg1c0805" { TEXT "(Smìje se) Ne, kuchaø si nechá zbytky!" }
	SUB "sg1c0901" { TEXT "Myslel jsem, e Quince a Jacow jsou dnes na hlídce." }
	SUB "sg1c0903" { TEXT "Slyšel jsem o nìm.... Garrett. S tím si není radno zahrávat, tak jsem slyšel." }
	SUB "sg1c1001" { TEXT "Øekni, kde jsou Hal a Joss dnes veèer?" }
	SUB "sg1c1003" { TEXT "To je ale pruda, kdy je pán na dovolené." }
	SUB "sg1c1005" { TEXT "Pravda." }
	SUB "sg1c1201" { TEXT "Slyšel jsem, e ti bude pøidìleno chùvièení potvor." }
	SUB "sg1c1203" { TEXT "Šéf si myslí, e jeho zrùdièky nemají dost lásky. Budeš jim tam dole masírovat bøíška!" }
	SUB "sg1c1302" { TEXT "Ta èernostøíbrná? Jo... pìknı." }
	SUB "sg1c1304" { TEXT "Hah! Vypíchl by sis oko." }
	SUB "sg1c1401" { TEXT "Slyšel jsem, e Grandmauden se chystá zavést nìjaké zabezpeèení vyrobené Kladiváøma." }
	SUB "sg1c1403" { TEXT "Jo." }
	SUB "sg1c1405" { TEXT "Heh heh, ha ha! To ji nauèí." }
	SUB "sg1c1502" { TEXT "Jo, taføí se s tebou. Kam dají ty uboáky, které chytí?" }
	SUB "sg1c1504" { TEXT "Trochu smutné. Døív byli mocní. Teï je z nich jen banda chlapù, co spomínaj na staré èasy." }
	SUB "sg1c1801" { TEXT "Tak jsem slyšel, e ti chlapi, co èistí kanály, udrují v chodu èerpadla a tak...?" }
	SUB "sg1c1803" { TEXT "Slyšel jsem, e prı mizí... Puf! Objevují se po kouskách. Tøeba jejich hlavy." }
	SUB "sg1c1805" { TEXT "S funkèním spláchováním u asi dlouho poèítat nemusíme." }
	SUB "sg1c1901" { TEXT "Pøemıšlel jsem...: Pán by mohl opravdu trochu posílit bezpeènost." }
	SUB "sg1c1903" { TEXT "No, jsme v pohodì, ale pøemıšlel jsem, e bychom mìli víc hlídat venku." }
    SUB "sg1c1905" { TEXT "Tak je aspoò chytíš døív, ne se dostanou dovnitø, ty taføe!"  }
	SUB "sg1c2101" { TEXT "Nemùu vystát to jídlo tady! Ach, tohle místo!" }
	SUB "sg1c2103" { TEXT "No jo, snad nìkdy pøíštì." }
	SUB "sg1c2202" { TEXT "Asi ne... ale nevymìkni." }
	SUB "sg1c2301" { TEXT "Šéf byl dneska nebezpeènı." }
	SUB "sg1c2303" { TEXT "Heh, jo, øíkal jsem jí to! Dobrá nálada, ta je nejhorší!" }
	SUB "sg1c2402" { TEXT "Jo, pìknı." }
	SUB "sg1c2601" { TEXT "Nemùu uvìøit, jak se to ve Waysidu zhoršilo. Zrovna nedávno se mì pokusil okrást chlap - za bílého dne!" }
	SUB "sg1c2603" { TEXT "Hele, bydlí tam moje ségra!" }
	SUB "sg1c3001" { TEXT "Jak to jde?" }
	SUB "sg1c3101" { TEXT "Dobrá hlídka." }
	SUB "sg1c3202" { TEXT "Ne. Docela klid." }
	SUB "sg1c3602" { TEXT "Nic moc." }
	SUB "sg1c3701" { TEXT "Nesnáším noèní hlídky." }
	SUB "sg1c3802" { TEXT "To jsem já, ty taføe!" }
}
{
	TYPE	"bark"
	DESCR	"Hlídka"
	SUB "sg1chga1" { TEXT "To staèí! Máš to mít!" }
    SUB "sg1chga2" { TEXT "Je z tebe rádlo pro psy!" }
	SUB "sg1chgw1" { TEXT "Nauèíme ho, jak si s námi zahrávat!" }
	SUB "sg1chgw2" { TEXT "Chopte se ho!" }
	SUB "sg1chgw3" { TEXT "Za ním!" }
	SUB "sg1det_1" { TEXT "Bojíme se?" }
	SUB "sg1det_2" { TEXT "Otoè se a bì!" }
	SUB "sg1det_3" { TEXT "Nechceš to schytat, taføe?" }
	SUB "sg1detw1" { TEXT "Nyní je v obranì!" }
	SUB "sg1hit_1" { TEXT "Jaké to je?" }
	SUB "sg1hit_2" { TEXT "Vidíš krev?" }
	SUB "sg1hit_3" { TEXT "To ti ukáe!" }
	SUB "sg1hit_4" { TEXT "Tady!" }
	SUB "sg1hitw1" { TEXT "Máme ho!" }
	SUB "sg1hitw2" { TEXT "Teï je náš!" }
	SUB "sg1hlow1" { TEXT "Uuughhh! Pomozte mi!" }
	SUB "sg1hnd_1" { TEXT "Ani škrábnutí!" }
	SUB "sg1hnd_2" { TEXT "Ooo! Myslím, e mì klovl ptáèek!" }
	SUB "sg1hnd_3" { TEXT "Budeš se muset snait víc, taføe!" }
	SUB "sg1lar_1" { TEXT "Tohle je katastrofa.... Pomoc!" }
	SUB "sg1lar_2" { TEXT "Ale ne, pán nás pøipraví o hlavu!" }
	SUB "sg1lar_3" { TEXT "Proklatì. Seeòte pomoc!" }
	SUB "sg1los_1" { TEXT "Sakra, kam se podìl?" }
	SUB "sg1los_2" { TEXT "Právì tam byl! Kde je?" }
	SUB "sg1los_3" { TEXT "Ztratil se! To není dobré." }
	SUB "sg1los_4" { TEXT "Sakra! Ztratil jsem ho." }
}
{
	TYPE	"convo"
	DESCR	"Hlídka"
	SUB "sg1m0201" { TEXT "Pomoc! Jsme napadeni!" }
	SUB "SG1M0500" { TEXT "Ano, urèitì to byl Garrett v tom oknì. Je mrtvı. Vrátíme se zpátky." }
	SUB "sg1m0501" { TEXT "Podívej, to je on! Sledoval nás!" }
	SUB "sg1m0502" { TEXT "To on zabil šéfa! Za ním!" }
	SUB "sg1m0503" { TEXT "Zastav... Sleduje nás nìkdo?" }
	SUB "sg1m0504" { TEXT "Myslel jsem, e tam vzadu nìkoho slyším." }
	SUB "sg1m0505" { TEXT "Zastav... Myslím, e nás nìkdo sleduje." }
	SUB "sg1m0506" { TEXT "To je on! Utíká nám. Spuste poplach!" }
	SUB "sg1m0507" { TEXT "To je on! Dokonèíme to!" }
	SUB "sg1m0508" { TEXT "Je nìkdo za námi?" }
	SUB "sg1m0509" { TEXT "Myslíš, e tam vzadu nìkdo je?" }
	SUB "sg1m0510" { TEXT "Nìkdo nás sleduje." }
	SUB "sg1mis_1" { TEXT "Zlodìj! Zlodìj v domì!" }
	SUB "sg1mis_2" { TEXT "Hej, kam se to podìlo?" }
	SUB "sg1mis_3" { TEXT "Chybí ezlo! Pán mì pøipraví o hlavu!" }
	SUB "sg1mis_4" { TEXT "Zlodìj má meè!" }
	SUB "SG1MIS_5" { TEXT "Váza byla ukradena!" }
	SUB "SG1MIS_6" { TEXT "Zdá se, e nìco chybí." }
	SUB "sg1rbod1" { TEXT "Je tu vrah. U došlo k vradì." }
	SUB "sg1rbod2" { TEXT "Pozor na vrahy. Na jednu noc bylo prolito u dost krve." }
	SUB "sg1rbod3" { TEXT "Nìkdo zabil Kevela. Dejte si pozor!" }
	SUB "sg1rbod4" { TEXT "Zlodìj vradil. Dávejte pozor." }
	SUB "sg1rint1" { TEXT "Mìjte oèi otevøené. Volnì tu pobíhá zlodìj." }
	SUB "sg1rint2" { TEXT "Pred chvílí jsem vidìl vetøelce. Buïte ve støehu." }
	SUB "sg1rint3" { TEXT "V budovì je zlodìj." }
	SUB "SG1RINT4" { TEXT "Je tu cizinec a dìlá problémy. Mìjte oèi na stopkách." }
	SUB "SG1RINT5" { TEXT "Nìkdo se zmocnil vázy. Vypadá to, e bude zle." }
	SUB "SG1RINT6" { TEXT "Nìkdo se mi plete do akce." }
	SUB "SG1RINT7" { TEXT "Nìjakı chmaták si bere, co se mu zlíbí. Buïte ve støehu." }
	SUB "sg1rmis1" { TEXT "Øekni pánovi, e byl okraden!" }
	SUB "sg1rmis2" { TEXT "Øeknìte ostatním, e se tu pohybuje zlodìj. Byli jsme okradeni!" }
    SUB "sg1rmis3" { TEXT "Proè neøekneš pánovi, e ezlo je pryè?"  }
	SUB "sg1rmis4" { TEXT "Meè je pryè!" }
}
{
	TYPE	"bark"
	DESCR	"Hlídka"
	SUB "sg1roth1" { TEXT "Je tu nìco? Pøed chvílí tu nìco bylo." }
	SUB "sg1roth2" { TEXT "Buïte ve støehu. Myslím, e jsem nìco vidìl." }
	SUB "sg1roth3" { TEXT "Jsem si jistı, e v budovì nìkdo je." }
	SUB "sg1roth4" { TEXT "Uvnitø je zlodìj!" }
	SUB "sg1runa1" { TEXT "Tady! Stráe!" }
	SUB "sg1runa2" { TEXT "Tudy! Pozor na vetøelce!" }
	SUB "sg1runa3" { TEXT "Stráe! Stáhnìte se! Tady!" }
	SUB "sg1runa4" { TEXT "Tudy! Zlodìj!" }
	SUB "sg1sec_1" { TEXT "Hej, je tu vetøelec!" }
	SUB "sg1sec_2" { TEXT "Co je s tímhle?" }
	SUB "sg1sec_3" { TEXT "Tady!" }
	SUB "sg1sec_4" { TEXT "Zlodìj v budovì!" }
	SUB "sg1sma_1" { TEXT "Takhle to ráno nevypadalo." }
    SUB "sg1sma_2" { TEXT "Nìkdo se tu moc bavil..." }
	SUB "sg1sma_3" { TEXT "Kdo tu byl?" }
	SUB "sg1sma_4" { TEXT "Co je to?" }
	SUB "sg1telc1" { TEXT "Vidíš ho? Dávej pozor, aby tì nezastøelil!" }
	SUB "sg1telc2" { TEXT "Tudy! Vetøelec utíká!" }
	SUB "sg1telc3" { TEXT "Zahlédl jsem ho!" }
	SUB "sg1telc4" { TEXT "Zlodìj je tam!" }
	SUB "sg1telc5" { TEXT "Vetøelec je tady!" }
	SUB "sg1telc6" { TEXT "Zlodìj je tady!" }
	SUB "sg1telc7" { TEXT "Je to Garrett!" }
	SUB "sg1telr1" { TEXT "Tady! Máme tu zlodìje!" }
	SUB "sg1telr2" { TEXT "Máme tu zlodìje!" }
	SUB "sg1telr3" { TEXT "Vetøelec! Támhle máme zlodìje!" }
	SUB "sg1telr4" { TEXT "Máme tu vetøelce! Rychle, je pøímo tady!" }
	SUB "sg1telr5" { TEXT "Hej, máme tu cizince!" }
	SUB "sg1telr6" { TEXT "Garrett je na pozemku. Jdìte po nìm!" }
	SUB "sg1telr7" { TEXT "Máme problém!" }
	SUB "sg1wrn11" { TEXT "Toto je soukromı pozemek. Okamitì se prac." }
	SUB "sg1wrn21" { TEXT "U to nebudu opakovat, darebáku: Ztra se, jestli nechceš pøijít o hlavu!" }
	SUB "sg1wrnf1" { TEXT "Dobøe, mizero, øekl sis o to! " }
}
