SUB1

{
	TYPE "player"
	DESCR "Garrett to himself"
	SUB "gar001" { TEXT "Tyto dveøe jsou zajištìné a není moné je otevøít." }
	SUB "gar002" { TEXT "Zamèeno. K otevøení potøebuji klíè." }
	SUB "gar003" { TEXT "Je zamèeno. Mohu zkusit vypáèit zámek nebo najít správnı klíè." }
	SUB "gar004" { TEXT "Á, mám to!" }
	SUB "gar005" { TEXT "Taková nádoba by mohla mít uvnitø nìco dobrého." }
	SUB "gar006" { TEXT "To je moc vysoko." }
	SUB "gar007" { TEXT "Krystaly jsou dobré k vylepšení šípù." }
	SUB "gar008" { TEXT "To se bude hodit." }
	SUB "gar009" { TEXT "Provazové šípy se zabodnou pouze do døevìnıch povrchù." }
	SUB "gar010" { TEXT "Vdy je dobré sebrat koøist." }
	SUB "gar011" { TEXT "Tak tohle stojí za to." }
	SUB "gar012" { TEXT "Nyní bude luk støílet ohnivé šípy." }
	SUB "gar013" { TEXT "Nyní bude luk støílet vodní šípy." }
	SUB "gar014" { TEXT "Nyní bude luk støílet mechové šípy." }
	SUB "gar015" { TEXT "Nyní bude luk støílet plynové šípy." }
	SUB "gar016" { TEXT "Radìji bych nechodil na svìtlo." }
	SUB "gar017" { TEXT "Kdy se budu dret u stìn, je šance, e mì nikdo neuvidí." }
	SUB "gar018" { TEXT "Radìji poèkám, a se otoèí zády." }
	SUB "gar019" { TEXT "Je jich pøíliš mnoho na mì, ne abych je sundal všechny najednou." }
	SUB "gar020" { TEXT "Radìji bych hledal jinou cestu." }
	SUB "gar021" { TEXT "Nemìl bych tady nechat leet tìlo." }
	SUB "gar022" { TEXT "Perfektní. Jen jeden a ten se dívá jinam." }
	SUB "gar023" { TEXT "Jen se dívej jinam." }
	SUB "gar024" { TEXT "Myslím, e jsem ho ztratil." }
	SUB "gar025" { TEXT "Nesnáším slepé zatáèky. Nikdy nevíš, na co narazíš." }
	SUB "gar026" { TEXT "Témìø vdy se vyplatí poslouchat u dveøí, ne je otevøeš." }
	SUB "gar027" { TEXT "Kdy ho praštím obuškem, ani by si toho nìkdo všimnul, bez hlesnutí se sesype." }
	SUB "gar028" { TEXT "Spousta krve. Mìl bych to tìlo odnést, ale jestli tudy nìkdo pùjde, mohl by pøijít na to, e se nìco dìje." }
	SUB "gar029" { TEXT "Uf! Tohle není dobré." }
	SUB "gar030" { TEXT "Mohl bych toho chlapa sejmout šípem, ale kdy se netrefím, prozradím se." }
	SUB "gar031" { TEXT "Spousta pyrotechniky, ale není to moc nenápadné. S tìmi si musím dávat pozor." }
	SUB "gar032" { TEXT "Vodní šípy jsou nejuiteènìjší na zhasnutí pochodní." }
	SUB "gar033" { TEXT "Mechové šípy jsou urèeny k vystøelování na hluèné povrchy, abych po nich mohl chodit a nedìlal rámus." }
	SUB "gar034" { TEXT "Nemá moc smysl støílet jimi do podlahy." }
	SUB "gar035" { TEXT "Mìl bych si uvìdomit, e šplouchání po okolí mùe zpùsobit velkı hluk." }
	SUB "gar036" { TEXT "Nesmím zùstat pod vodou pøíliš dlouho, jinak se utopím!" }
	SUB "gar037" { TEXT "Mám u jen pár vteøin vzduchu!" }
	SUB "gar038" { TEXT "Proti tomuhle proudu nikdy nepostoupím!" }
	SUB "gar039" { TEXT "Sudy, jako jsou tyto, mohou v nouzi poskytnout dobré krytí." }
	SUB "gar040" { TEXT "Bedny, jako jsou tyto, jsou uiteèné jako úkryt." }
	SUB "gar041" { TEXT "Kadı klíè nìkde nìco otevírá." }
	SUB "gar042" { TEXT "(Chichot) U to není tak tajné, co?" }
	SUB "gar043" { TEXT "Ach! Dìlám moc velkı hluk, kdy chodím po téhle dladici." }
	SUB "gar044" { TEXT "Chùze po kovu je hluèná.... Musím bıt opatrnı." }
	SUB "gar045" { TEXT "Mám z toho špatnı pocit...." }
	SUB "gar046" { TEXT "Hmm.... Tohle vypadá zajímavì." }
	SUB "gar047" { TEXT "Zajímalo by mì, co se tu stalo?" }
	SUB "gar048" { TEXT "Vypadá to, e tohle u léta nefunguje." }
	SUB "gar049" { TEXT "Zajímalo by mì, jak se tam dostanu?" }
	SUB "gar050" { TEXT "Hmm.... Tam dole musí vést nìjaká cesta." }
	SUB "gar06100" { TEXT "Dobrou noc!" }
	SUB "gar06101" { TEXT "To zaplatí nájem." }
	SUB "gar06102" { TEXT "Ahh, zadní dveøe." }
	SUB "gar06103" { TEXT "Fuuh, kanalizace rozhodnì není tou nejpùvabnìjší èástí práce." }
	SUB "gar06104" { TEXT "U lorda Randalla by to vonìlo líp." }
	SUB "gar06105" { TEXT "Jsou tak zaneprázdnìní gamblerstvím, e si ani nevšimnou, kdy si trochu vezmu." }
	SUB "gar06106" { TEXT "Teï si mùu vzít svou vázu." }
	SUB "gar06107" { TEXT "To jsem potøeboval slyšet." }
	SUB "gar06108" { TEXT "Miluju, kdy mi peníze spadnou do klína." }
	SUB "gar100" { TEXT "Tady nemám štìstí." }
	SUB "gar101" { TEXT "Tohle neotevøu." }
	SUB "gar10100" { TEXT "Hmm.... Tohle vypadá jako cesta ven. To se bude hodit pozdìji." }
	SUB "gar10101" { TEXT "Tak tady mágové skrıvají svá malá špinavá tajemství." }
	SUB "gar10102" { TEXT "Vypadá to, e kapitán Regalio mágùm nìco zatajil. Ještì, e to nemùe tajit pøede mnou." }
	SUB "gar10103" { TEXT "Tohle vykouzlí úsmìv na tváøi kadému pøekupníkovi." }
	SUB "gar102" { TEXT "Tudy neprojdu." }
	SUB "gar103" { TEXT "Tímto smìrem nelze jít." }
	SUB "gar104" { TEXT "Tudy ne." }
	SUB "gar105" { TEXT "Ach, tudy nemá smysl jít." }
	SUB "gar106" { TEXT "Tady se nemusím obtìovat." }
	SUB "gar107" { TEXT "Tudy není nic uiteèného." }
	SUB "gar108" { TEXT "Tady vzadu mì nic nezajímá." }
	SUB "gar110" { TEXT "Nezdá se, e by to k nìèemu bylo." }
	SUB "gar111" { TEXT "Nic moc nedìlá." }
	SUB "gar120" { TEXT "Hmm. Tohle teï nejde otevøít." }
	SUB "gar121" { TEXT "Vypadá to, e to nejde otevøít." }
	SUB "gar12100" { TEXT "Hádám, e od Giryho nakonec nedostanu ádné informace." }
	SUB "gar12101" { TEXT "Prázdno.... Co teï?" }
	SUB "gar12102" { TEXT "Na toho chlapa u dávno padla opona, ale je to nejlepší vodítko, které mám." }
	SUB "gar12103" { TEXT "Tohle vypadá jako cesta dovnitø." }
	SUB "gar12104" { TEXT "Heh. Opravdu lidi za tohle dali peníze, aby to vidìli?" }
	SUB "gar12105" { TEXT "Ááá. Tajnı vchod." }
	SUB "gar12106" { TEXT "Rád bych zùstal na finále, ale mám pocit, e je èas jít dál." }
	SUB "gar12107" { TEXT "Tak to bylo pøekvapení." }
	SUB "gar12108" { TEXT "Tohle bude pìknı malı bonus." }
	SUB "gar99100" { TEXT "Prostì se vyplíím oknem." }
	SUB "gar99102" { TEXT "Radìji se dám do práce." }
	SUB "gar99103" { TEXT "Tafel?" }
	SUB "gar99104" { TEXT "Radši se odeberu do stínu, ne mì uvidí." }
	SUB "gar99105" { TEXT "Nemùu se tu schovávat vìènì." }
	SUB "gar99106" { TEXT "Ten chlap potøebuje zhubnout!" }
	SUB "gar99107" { TEXT "To ho umlèelo!" }
	SUB "gar99108" { TEXT "Tihle chlapi prostì nemají smysl pro humor." }
	SUB "gar99109" { TEXT "Ááá... mùj oblíbenı rok!" }
	SUB "gar99110" { TEXT "Sluebná musí mít volno." } 
	SUB "garc0101" { TEXT "Tak jo, starouši. Dostaòme tì odsud a já dostanu své peníze." }
	SUB "garc0103" { TEXT "Ještì e umíráš, Cutty, jinak bych tì musel zabít za to, e jsi mnì podvedl... zase." }
	SUB "garhmmm" { TEXT "Hmm...." }
	SUB "garm0101" { TEXT "Stráci mì trénovali, abych se stal jedním z nich, ale našel jsem... jiné vyuití tìchto schopností." }
	SUB "garm0201" { TEXT "Hmm. Je jich pøíliš mnoho ne abych se snail projít tudy." }
	SUB "garm0202" { TEXT "Jen jeden stránı. Pøesto by bylo fajn ho dostat." }
	SUB "garm0203" { TEXT "Koneènì uvnitø." }
	SUB "garm0204" { TEXT "Ha. Mohl bys bıt ještì uiteènìjší?" }
	SUB "garm0205" { TEXT "Radìji tu nenechat leet pøíliš mnoho tìl." }
	SUB "garm0206" { TEXT "Zajímalo by mì, jestli je ète, nebo je to jen na oko." }
	SUB "garm0207" { TEXT "Kdy u jsem tady, mohl bych si vzít nìco pro sebe." }
	SUB "garm0208" { TEXT "Heh. Je to trùnní sál. Jak moc namyšlenı mùe èlovìk bıt?" }
	SUB "garm0209" { TEXT "A je to tady." }
	SUB "garm0301" { TEXT "U bych mìl bıt blízko vchodu do vìzení." }
	SUB "garm0302" { TEXT "Nevidí mì, kdy se drím ve stínu, ale budu muset pøejít na svìtlo, abych se dostal ke schodùm." }
	SUB "garm0303" { TEXT "Áááá! Køehká kovová møí.... Radìji budu našlapovat opatrnì." }
	SUB "garm0304" { TEXT "Zamèeno z druhé strany." }
	SUB "garm0305" { TEXT "Hmm.... Radši a do toho gongu nikdo nebouchne, nebo budu mít víc spoleènosti, ne zvládnu." }
	SUB "garm0306" { TEXT "Heh. Pøesnì to svìt potøebuje: více kladiv!" }
	SUB "garm0307" { TEXT "Více ne jeden chlap. To bude sloitìjší." }
	SUB "garm0308" { TEXT "Vypadá to, e jsem na správné cestì." }
	SUB "garm0309" { TEXT "Nesnáším slepé zatáèky. Nikdy nevíš, na co narazíš." }
	SUB "garm0310" { TEXT "Mám z toho špatnı pocit...." }
	SUB "garm0311" { TEXT "Radìji se tu budu dret ve stínu. Jestli mì uvidí, budu mít problém." }
	SUB "garm0312" { TEXT " Vpravo.... Blok ètyøi. Cutty, tohle by sis mìl váit." }
	SUB "garm0313" { TEXT "Tohle se zdá pøíliš snadné." }
	SUB "garm0314" { TEXT "Kolik tu vlastnì mají stráí?" }
	SUB "garm0315" { TEXT "Ale kterı z nich je Cutty? A jak mám otevøít dveøe?" }
	SUB "garm0316" { TEXT "Prostì se poøád dívej jinam." }
	SUB "garm0317" { TEXT "Vsadím se, e ovládání dveøí je tam." }
	SUB "garm0318" { TEXT "Tak tohle byl ztracenı pøípad. Je èas vypadnout, ne skonèím ve vedlejší cele." }
	SUB "garm0319" { TEXT "Ha.... Takhle asi utrácejí všechny ty desátky." }
	SUB "garm0320" { TEXT "Zajímalo by mì, jestli mám èas zastavit se na svaèinu." }
	SUB "garm0321" { TEXT "Nemá smysl tamtudy chodit... bude se to tam hemit Kladiváøi." }
	SUB "garm0322" { TEXT "Berou všechny tyhle vìci pøíliš vánì." }
	SUB "garm0323" { TEXT "Jestli pùjdu poøád nahoru, tak mi dojde budova." }
	SUB "garm0324" { TEXT "Nemá smysl tudy chodit.... Není se kam schovat." }
	SUB "garm0325" { TEXT "Cutty u to nebude potøebovat." }
	SUB "garm0326" { TEXT "Ahh, to je to, co hledám." }
	SUB "garm0327" { TEXT "Aspoò umím plavat líp ne nìkdo, kdo nosí kladivo." }
	SUB "garm0328" { TEXT "Sbohem, kladiva." }
	SUB "garm0329" { TEXT "Zajímavá jízda. Zajímalo by mì, jestli to nìkdo z Kladiváøù absolvoval." }
	SUB "garm0330" { TEXT "No, tady je Basso. Kdyby nebyl v bezvìdomí, bylo by to jednodušší, ale teï ho budu muset vynést ven." }
	SUB "garm0401" { TEXT "Nebyl to mùj nejelegantnìjší vstup, ale fungovalo to." }
	SUB "garm0402" { TEXT "Felixi, nevypadáš moc dobøe." }
	SUB "garm0403" { TEXT "Sakra, musí bıt ještì nìjaká jiná cesta dovnitø." }
	SUB "garm0404" { TEXT "Co je to za zvuk?" }
	SUB "garm0405" { TEXT "Wau! Víš, e si to nemùeš vzít s sebou... Ale já mùu." }
	SUB "garm0406" { TEXT "Pøedpokládám, e Roh Quinta." }
	SUB "garm0407" { TEXT "Tak tohle je ten bájnı Roh Quinta. Doufám, e nikomu nebude vadit, kdy si ho prostì vezmu s sebou." }
	SUB "garm0408" { TEXT "Tolik tedy k Felixovi." }
	SUB "garm0409" { TEXT "Je to dlouhá cesta dolù." }
	SUB "garm0410" { TEXT "Heh.... Jak neslušné!" }
	SUB "garm0411" { TEXT "Hah.... Hrobky s troubenou hudbou... jak nóbl." }
	SUB "garm0412" { TEXT "Pìknı vıhled. Zajímalo by mì, jestli to mrtví ocení." }
	SUB "garm0413" { TEXT "Ještì e se nebojím vıšek." }
	SUB "garm0414" { TEXT "Vypadá to, e se blíím." }
	SUB "garm0415" { TEXT "Huh.... Ti chlapi nevypadají moc zle." }
	SUB "garm0501" { TEXT "Tak tohle jsou Ramirezovi kluci. Myslím, e je na èase, abych si to s panem Ramirezem vyøídil jednou provdy." }
	SUB "garm0502" { TEXT "Moná u je èas, abych šel dál. Nechci se vyèerpat." }
	SUB "garm0503" { TEXT "Moná bych se mìl vrátit do své ètvrti. Ti chlapíci nevypadají moc pøátelsky." }
	SUB "garm0504" { TEXT "Co je to za blázna, kterı si tyhle vìci chová jako domácí mazlíèky?" }
	SUB "garm0505" { TEXT "Sakra! Asi jsem ztratil jejich stopu." }
	SUB "garm0506" { TEXT "Ten vıstøel byl urèen pro mì." }
	SUB "garm0507" { TEXT "Tihle šmejdi mì dovedou pøímo k tomu, kdo je poslal, aby mì zabili. Ale jen pokud je dokáu sledovat, ani by si mì všimli." }     
	SUB "garm0601" { TEXT "Sklenìnı drahokam? Tenhle meè byla jen ztráta èasu!"}
	SUB "garm0602" { TEXT "Sakra! Je to padìlek!" }
	SUB "garm0603" { TEXT "Informace o Konstantinovi! Skoro jako zlato." }
	SUB "garm0604" { TEXT "Je èas vzít mùj novı meè a vypadnout z tohoto šíleného místa." }
	SUB "garm0605" { TEXT "Magické pasti. Hádám, e to se svım soukromím myslí vánì." }
	SUB "garm0701" { TEXT "Vypadá to, e tohle místo postavili moji staøí známí, Stráci. Zajímalo by mì, co tu skrıvají...?" }
	SUB "garm0901" { TEXT "Co to tu máme?" }
	SUB "garm0902" { TEXT "Nebudu tam plavat." }
	SUB "garm0903" { TEXT "Dìsivé...." }
	SUB "garm0904" { TEXT "Je nìkdo... doma?" }
	SUB "garm0905" { TEXT "Zajímalo by mì, jestli to vidìli Stráci?" }
	SUB "garm0906" { TEXT "Jeden je dole, jeden zbıvá." }
	SUB "garm0907" { TEXT "Jak mohou Stráci udret toto místo v tajnosti?" }
	SUB "garm0908" { TEXT "Vypadá to, e to musela bıt nìjaká knihovna." }
	SUB "garm0909" { TEXT "Podle mapy to nejspíš bylo trištì." }
	SUB "garm0910" { TEXT "Je èas na... rabování hrobek." }
	SUB "garm0911" { TEXT "Nejsem moc nadšenı z okolí." }
	SUB "garm0912" { TEXT "Abych mohl vyuít svou mapu, musím najít nìjakı orientaèní bod, podle kterého bych mohl jít." }
	SUB "garm0913" { TEXT "Tak tohle je Ztracené mìsto.... U není 'ztracené'!" }
	SUB "garm1001" { TEXT "Sakra! Zabralo mi to moc èasu." }
	SUB "garm1002" { TEXT "'Jsem Zednáø...' Uh... Tohle není místo pro ètení poezie." }
	SUB "garm1003" { TEXT "'Jsem Zednáø. A mé zdi vydrí od sezóny k sezónì, od roku k roku a od vìku k vìku. A mé zdi stojí, zatímco rodiny døou, armády pochodují a øíše padají. Já jsem Zednáø a mé zdi budou vdy stát jako štít proti zlu. O to se modlím, to mi Pán Stavitel dopøeje.'" }
	SUB "garm1101" { TEXT "Nelíbí se mi, jak to vypadá." }
	SUB "garm1102" { TEXT "O-ou." }
	SUB "garm1103" { TEXT "Hmm...." }
	SUB "garm1104" { TEXT "Co tu máme?" }
	SUB "garm1105" { TEXT "Tyhle schody u zaily lepší èasy." }
	SUB "garm1106" { TEXT "Vypadá to, e tohle u nefunguje." }
	SUB "garm1107" { TEXT "Jestli to nebude fungovat, tak se daleko nedostanu." }
	SUB "garm1108" { TEXT "Co to bylo?" }
	SUB "garm1109" { TEXT "A jak se odsud dostanu?" }
	SUB "garm1110" { TEXT "Ó Pane Staviteli, prosíme Tì, abys poehnal našemu bratrovi, kterı zemøel ve Tvıch slubách. Odpus mu prohøešky za dnù jeho ivota a shlédni pøíznivì na skutky jeho ve Jménu Tvém. Olovnice a hoblík, oheò a vıheò, oèisti jeho ducha a odejmi z nìj vše, co neodpovídá Tvému plánu. Vezmi si ho, aby s Tebou slouil ve Tvém domovì, kde mùe odpoèívat ve vìèném pokoji." }
	SUB "garm1202" { TEXT "No, tohle je... zajímavé, ale neøíká to nic o Oku." }
	SUB "garm1203" { TEXT "Páni... Heh... ani Kladiváøi v tom nenašli hlavu nebo patu, ale nevypadá to dobøe." }
	SUB "garm1301" { TEXT "Co se tu stalo? A kde jsou všichni Kladiváøi?!" }
	SUB "garm1303" { TEXT "Vypadá to, e by to pro mì a veleknìze mohla bıt dobrá úniková cesta." }
	SUB "garm1401" { TEXT "Tak tohle je moje cesta ven. Radši to nezvorat." }
	SUB "garm1402" { TEXT "Tohle nemùe vést na ádné pøíjemné místo." }
	SUB "garm1403" { TEXT "Vy všichni ostatní démoni... Mùete teï zùstat doma." }
	SUB "garm1404" { TEXT "A teï u to nebudeme zkoušet." }
	SUB "garm1405" { TEXT "To si ze mì dìláte srandu." }
	SUB "garm1406" { TEXT "Hah. Tak to je velkı!" }
	SUB "garm1407" { TEXT "Ó, zajímavé." }
	SUB "garm1408" { TEXT "U toho mám dost." }
	SUB "garm1409" { TEXT "Vypneme ten portál a dáme Kladiváøùm šanci bojovat." }
	SUB "garOT01" { TEXT "Ani to nebudu komentovat...." }
	SUB "garOT02" { TEXT "To bych nazval chybou." }
	SUB "garOT03" { TEXT "Hej, vra se sem!" }
	SUB "garOT04" { TEXT "Ach jo... je pryè." }
	SUB "garOT05" { TEXT "Zapalte nìkdo sirku." }
	SUB "garOT06" { TEXT "Co je vlastnì k sakru ten 'tafel'?" }
	SUB "garOT07" { TEXT "Nesnáším moderní trendy." }
	SUB "garOT08" { TEXT "Myslím, e Bafford má ve zvonici pøíliš mnoho netopırù." }
}
