SUB1

{
	TYPE "convo"
	DESCR "Hlídka"
	SUB "SG2A0MU1" { TEXT "Fuj, je tu mokro... Všude plíseò!" }
	SUB "SG2A0MU2" { TEXT "Tohle místo se mi vùbec nelíbí... Chodí tu jen málo lidí..." }
	SUB "SG2A0MU3" { TEXT "Ach jo, u musím domù na veèeøi... Èeká mì a já mám hlad... Nejedl jsem od snídanì!" }
}
{
	TYPE "bark"
	DESCR "Hlídka"
	SUB "SG2A1__1" { TEXT "Nìkdo je za mnou?" }
	SUB "SG2A1__2" { TEXT "Kdo to tam jde?" }
	SUB "SG2A1__3" { TEXT "Jsi to ty?" }
	SUB "SG2A1__4" { TEXT "Co?" }
	SUB "SG2A1__5" { TEXT "Co?" }
	SUB "SG2A1__6" { TEXT "Co to je? Kde kdo?!" }
	SUB "SG2A1_W1" { TEXT "Bylo tam nìco?" }
	SUB "SG2A1_W2" { TEXT "Myslíš, e tam nìco je?" }
	SUB "SG2A1DR1" { TEXT "Kdo to tam chodí?" }
	SUB "SG2A1H_1" { TEXT "Hej! Co to bylo za zvuk?" }
	SUB "SG2A1H_2" { TEXT "Kdo to tam šustí?" }
	SUB "SG2A1H_3" { TEXT "Divnı rámus." }
    SUB "SG2A1HW1" { TEXT "Nìco udìlalo rámus! Tiše!" }
	SUB "SG2A1HW2" { TEXT "Taky jsi to slyšel? Myslím, e tam nìkdo je..." }
	SUB "SG2A1HW3" { TEXT "Co to bylo? Slyšel jsi nìco?" }
	SUB "SG2A1HW4" { TEXT "Slyšel jsi nìco?" }
	SUB "SG2A1V_1" { TEXT "Pohnul se ten stín?" }
	SUB "SG2A1V_2" { TEXT "Nìco se tam pohnulo?" }
	SUB "SG2A1VW1" { TEXT "Co to bylo? Vidìl jsi to?" }
	SUB "SG2A1VW2" { TEXT "Vidìl jsi nìco? Ne! Támhle!" }
	SUB "SG2A1VW3" { TEXT "Hej, myslím, e jsem nìco vidìl!" }
	SUB "SG2A1VW4" { TEXT "Vidíš to?" }
	SUB "SG2A2__1" { TEXT "Jsi to ty? Poèkej, kdo je to?!" }
	SUB "SG2A2__2" { TEXT "Pøestaò se se mnou taføit! Uka se!" }
	SUB "SG2A2__3" { TEXT "Co je to? Hej, nìkdo se tu taføí?" }
	SUB "SG2A2__4" { TEXT "Co se to tam dìje?" }
	SUB "SG2A2__5" { TEXT "Kdo je to tam?" }
	SUB "SG2A2DR1" { TEXT "Co je to?" }
	SUB "SG2A2DR2" { TEXT "Eh-hey! Pøestaò se tu taføit!" }
	SUB "sg2a2h_1" { TEXT "Kdo tam chodí? Kdo udìlal ten rámus?" }
	SUB "sg2a2h_2" { TEXT "To jsem slyšel! Uka se! Myslím to vánì!" }
	SUB "SG2A2H_3" { TEXT "Slyšel jsem tì!" }
	SUB "SG2A2SE1" { TEXT "Dobøe, ty tafre, najdu tì!" }
	SUB "SG2A2SE2" { TEXT "Dlouho se neschováš!" }
	SUB "SG2A2SE3" { TEXT "Jen poèkej, a tì najdu!" }
	SUB "SG2A2SE4" { TEXT "Dobøe, kde jsi?" }
	SUB "SG2A2V_1" { TEXT "Vidím tì tam! Kdo je to?" }
	SUB "Sg2a3b_1" { TEXT "Co jsi udìlal? Zùstaò, kde jsi!" }
	SUB "SG2A3DR1" { TEXT "Heh, kdo sakra jsi?" }
	SUB "SG2A3NA1" { TEXT "Zahrávej si se mnou a je z tebe maso pro vrány, hochu!" }
	SUB "SG2A3NA2" { TEXT "Máme tu narušitele!" }
	SUB "SG2A3NA3" { TEXT "Nemysli si, e mùeš zase jen tak zmizet ve stínech, chytráku! Vidím tì!" }
	SUB "SG2A3NA4" { TEXT "Nepokoušej se utéct, tafre! Prostì se vzdej!" }
	SUB "SG2A3NA5" { TEXT "Stùj!" }
	SUB "SG2A3NA6" { TEXT "Pohni se a je po tobì! Nezkoušej to!" }
	SUB "SG2A3S_1" { TEXT "Áá! Zastav se!" }
	SUB "SG2A3S_3" { TEXT "Eh, ty!" }
	SUB "SG2A3S_4" { TEXT "Eh, stùj!" }
    SUB "Sg2a3se1" { TEXT "Schovávání tì nezachrání, zlodìji!" }
	SUB "Sg2a3se2" { TEXT "A tì najdu, budeš toho litovat!" }
	SUB "Sg2a3se3" { TEXT "Vra se sem a bojuj!" }
	SUB "Sg2a3se4" { TEXT "Pojï sem! Vyzıvám tì!" }
	SUB "SG2ALMA1" { TEXT "Poplach!" }
	SUB "SG2ALMA2" { TEXT "Vší rychlostí k alarmu!" }
	SUB "SG2ALMA3" { TEXT "K alarmu!" }
	SUB "SG2ALMW1" { TEXT "Rychle! Bìte k alarmu!" }
	SUB "SG2ALMW2" { TEXT "Rychle k alarmu!" }
	SUB "SG2AMB_1" { TEXT "Vylez ven, kde ti mùu ublíit!" }
	SUB "SG2AMB_2" { TEXT "Hnido! Pojï sem!" }
	SUB "SG2AMB_3" { TEXT "Kde jsi, èernı pse?" }
	SUB "SG2AMB_4" { TEXT "Zbabìlec! Vypadni odsud!" }
	SUB "SG2AMBW1" { TEXT "Jsem zasaen! Pozor na záda!" }
	SUB "SG2AMBW2" { TEXT "Jsem napaden!" }
	SUB "SG2AMBW3" { TEXT "Pomoc! Jsem napaden!" }
	SUB "Sg2atb_1" { TEXT "Nemùeš uhnout šípu!" }
	SUB "Sg2atb_2" { TEXT "Pro tvé srdce!" }
	SUB "Sg2atb_3" { TEXT "Jako cviènı terè!" }
	SUB "SG2ATN_1" { TEXT "Zhebni!" }
	SUB "SG2ATN_2" { TEXT "Tam!" }
	SUB "Sg2atw_1" { TEXT "Vymla si zuby!" }
	SUB "SG2ATW_2" { TEXT "Ha ha tobì!" }
	SUB "SG2ATWW1" { TEXT "Ztrácí nervy!" }
	SUB "SG2BAK_1" { TEXT "Musím se pøestat cukat pro nic!" }
	SUB "SG2BAK_2" { TEXT "Moc kafe dneska ráno, jsem nervní jak èert! Zdá se tu èisto." }
	SUB "SG2BAK_3" { TEXT "Èisto, zdá se." }
	SUB "SG2BAK_4" { TEXT "To je naposledy, co jsem vyskoèil kvùli krysám." }
	SUB "SG2BAK_5" { TEXT "Teï u není nic k vidìní." }
	SUB "SG2BAK_6" { TEXT "U to není slyšet. Asi nic." }
	SUB "SG2BAK_7" { TEXT "Teï u je ticho. To musely bıt krysy." }
	SUB "SG2BAK_8" { TEXT "Teï u nic nevidím." }
	SUB "SG2BKD_1" { TEXT "Sakra!" }
	SUB "SG2BKD_2" { TEXT "Zkus zablokovat další!" }
	SUB "SG2BKD_3" { TEXT "Ještì zakolísáš!" }
	SUB "SG2BKDW1" { TEXT "Má dobrou obranu! Urychli to!" }
	SUB "SG2BLK_1" { TEXT "Radìji to zkus znovu!" }
	SUB "SG2BLK_2" { TEXT "Musíš bıt rychlejší!" }
	SUB "SG2BLK_3" { TEXT "Dnes ne, kámo!" }
	SUB "SG2BLKW1" { TEXT "Dr se ve støehu a neprojde!" }
	SUB "SG2BOD_1" { TEXT "Paneboe! Zabili ho!" }
	SUB "SG2BOD_2" { TEXT "Ahh, pšššt...! Co se stalo?" }
	SUB "SG2BOD_3" { TEXT "Krev za krev!" }
}
{
	TYPE "convo"
	DESCR "Hlídka"
	SUB "SG2C0102" { TEXT "Ts! Nezaplatili mi dost!" }
	SUB "SG2C0104" { TEXT "Ne, ne! Je mi z toho zle! Kdy jsem byl malı..." }
	SUB "SG2C0106" { TEXT "Sklapni, ty tafre! Chceš krev? Mìl jsi tam bıt pøed lety! Øeknu ti... medvìdi tehdy? Bylo se na co dívat. Ti medvìdi nepotøebovali ádné bodce na tváøe, iletkové obojky, háky na tlapy a všechny ty noe, co jim teï nasazujou!" }
	SUB "SG2C0108" { TEXT "Hah! Naaa! Tehdejší medvìdi mìli drápy dlouhé jako tvùj prst! A strašné tesáky!" }
	SUB "SG2C0110" { TEXT "Proto teï nemùu vystát Jámy! Ani nevíš, o co jsi pøišel. Medvìdi u prostì nejsou jako kdysi...." }
	SUB "Sg2c0702" { TEXT "Eh, mohlo to bıt horší." }
	SUB "Sg2c0704" { TEXT "Radìji bys zase zametal ulice?" }
	SUB "Sg2c0706" { TEXT "Jo, ale špatnı druh lidí...." }
	SUB "Sg2c0802" { TEXT "Ne, Bafford a jeho poskoci to všechno serali!" }
	SUB "Sg2c0804" { TEXT "Moná, e v kuchyni nìco zbylo." }
	SUB "Sg2c0806" { TEXT "Huh! Tlustı flákaè!" }
	SUB "Sg2c0902" { TEXT "Šéf je poslal na zvláštní pochùzku. Na nìjakého chlápka, co chce pod drnem! Zlodìje, jmenuje se 'Garrett'." }
	SUB "Sg2c0904" { TEXT "U ne, pokud ho navštívili tihle dva!" }
	SUB "Sg2c1002" { TEXT "Copak jsi to neslyšel? Vytáhli smìnu ze sklepa. Nejspíš je ještì pár hodin neuvidíme!" }
	SUB "Sg2c1004" { TEXT "Tak to je pro nás lepší, co? No, mìl bych se vrátit k pøední bránì. Uvidíme se tady za pár hodin?" }
	SUB "Sg2c1101" { TEXT "Eh, jdi dolù ke studni a pøines nám trochu vody." }
	SUB "SG2C1202" { TEXT "Coe? Proè mnì?"}
	SUB "SG2C1204" { TEXT "Já konèím první. Uvidíš, jestli ne!" }
	SUB "Sg2c1301" { TEXT "Vidìl jsi, co nosí Šemenovi drsòáci?" }
	SUB "Sg2c1303" { TEXT "A my tu trèíme s tímhle harampádím! A oni mají taky halapartny!" }
	SUB "Sg2c1601" { TEXT "Prı se musíš zásobit!" }
	SUB "Sg2c1603" { TEXT "Uh, dej mi šest na Bohna a... uh... uh... pìt na další dva roky." }
	SUB "Sg2c1605" { TEXT "Hele poèkej. Zaplatíme ti teï a ty dva roky neplatíš? Nasrat!" }
	SUB "Sg2c1702" { TEXT "Jo! Samozøejmì.... Mìl kámoše z party, co blokoval zadní ulièku." }
	SUB "Sg2c1704" { TEXT "Další dozorce pod trhem? To je mazanı!" }
	SUB "Sg2c1802" { TEXT "Coe?" }
	SUB "Sg2c1804" { TEXT "Dìs!" }
	SUB "Sg2c2001" { TEXT "Take, jak jsem ti vèera øíkal, chceš tomu chlapovi ublíit, ne ho srazit na zem nebo ho poplácat po hlavì." }
	SUB "Sg2c2003" { TEXT "Praš ho do ramene a to ho jen zpomalí! Jdi na bøicho nebo ní. Kladivo je tam obvykle slabé." }
	SUB "SG2C2102" { TEXT "Víš, jak to teï na svìtì chodí. Nemùeš mu to mít za zlé." }
	SUB "Sg2c2201" { TEXT "Myslíš, e se nìco stane?" }
	SUB "Sg2c2203" { TEXT "Já ne!" }
	SUB "Sg2c2501" { TEXT "Myslím, e jsi ospalı." }
	SUB "Sg2c2503" { TEXT "'Sníèek' mìls." }
	SUB "Sg2c2602" { TEXT "Proè vùbec chodíš do Wayside? Jsou tam jen dìvky a penìzomìnci." }
	SUB "Sg2c2604" { TEXT "Vsadím se, e vím, co je zaè!" }
	SUB "Sg2c3002" { TEXT "Vidìl jsem lepší... Vidìl jsem lepší." }
	SUB "Sg2c3102" { TEXT "Taky." }
}
{
	TYPE "bark"
	DESCR "Hlídka"
	SUB "Sg2c3201" { TEXT "Vidìl jsi nìco?" }
	SUB "Sg2c3301" { TEXT "Hezká noc." }
	SUB "Sg2c3401" { TEXT "U mì všecko v poøádku." }
	SUB "SG2C3502" { TEXT "Oh, z koho si utahuješ?" }
	SUB "SG2CHGA1" { TEXT "To byla tvá poslední šance!" }
	SUB "SG2CHGA2" { TEXT "Tohle bude zábava!" }
	SUB "SG2CHGW1" { TEXT "Pomozte mi ho dostat! Zlodìj, zlodìj!" }
	SUB "SG2CHGW2" { TEXT "Ke zbrani!" }
	SUB "SG2CHGW3" { TEXT "Pomozte mi dostat toho zlodìje!" }
	SUB "SG2CHGW4" { TEXT "Za ním!" }
	SUB "SG2DET_1" { TEXT "Tohle mi neublíí!" }
	SUB "SG2DET_2" { TEXT "Máš nahnáno?" }
	SUB "SG2DET_3" { TEXT "Myslíš, e to pomùe?" }
	SUB "SG2DETW1" { TEXT "Teï z nás má plné gatì." }
	SUB "SG2HIT_1" { TEXT "Mám tì!" }
	SUB "SG2HIT_3" { TEXT "Vzdej to, tafre!" }
	SUB "SG2HIT_4" { TEXT "To musí bolet!" }
	SUB "SG2HITW1" { TEXT "Máme ho v koutì!" }
	SUB "SG2HITW2" { TEXT "Jsi na øadì!" }
	SUB "SG2HLOW1" { TEXT "Kryjte mì!" }
	SUB "SG2HND_1" { TEXT "To je to nejlepší, co dokáeš?" }
	SUB "SG2HND_2" { TEXT "Ani škrábnutí!" }
	SUB "SG2HND_3" { TEXT "Páni, trochu jsi promáèkl brnìní!" }
	SUB "SG2LAR_1" { TEXT "Podívejte se na to! Pomoc! Tudy!" }
	SUB "SG2LAR_2" { TEXT "Co to sakra je? Kdo to... Pomoc!" }
	SUB "SG2LAR_3" { TEXT "Co to všechno je?" }
	SUB "SG2LOS_1" { TEXT "Kam šel teï?" }
	SUB "SG2LOS_2" { TEXT "Kam šel ten tafer?" }
	SUB "SG2LOS_3" { TEXT "Hej! Vra se sem! Kam jsi šel?" }
	SUB "SG2LOS_4" { TEXT "Kam šel?" }
}
{
	TYPE "convo"
	DESCR "Hlídka"
	SUB "Sg2m0201" { TEXT "Skvìlé. Mistr je pryè, a zatímco ostatní se nejspíš baví nahoøe, já tu trèím dole a hlídám pivo, místo abych ho pil!" }
	SUB "Sg2m0202" { TEXT "Loupeníci! Pomoc!" }
	SUB "Sg2m02d1" { TEXT "Ahoj, pøíteli! Co to máš za bláznivı pøevlek?" }
}
{
	TYPE "bark"
	DESCR "Hlídka"
    SUB "SG2M0501" { TEXT "Chopte se ho!" }
	SUB "Sg2m0502" { TEXT "Utíká nám!" }
	SUB "Sg2m0503" { TEXT "Poèkej! Slyšel jsi nìkoho?" }
	SUB "Sg2m0504" { TEXT "Pøísahal bych, e jsem nìkoho slyšel. Zbystøi zrak!" }
	SUB "Sg2m0505" { TEXT "Slyšel jsi to? Nìkdo je nám urèitì v patách!" }
	SUB "Sg2m0506" { TEXT "Podívej! To je on! Tentokrát ho sejmi!" }
	SUB "Sg2m0507" { TEXT "Mám pocit, e nás nìkdo sleduje!" }
	SUB "Sg2m0508" { TEXT "Nìkdo nás sleduje?" }
	SUB "Sg2m0509" { TEXT "Slyšel jsem tam vzadu nìco divného." }
	SUB "Sg2m0510" { TEXT "Slyšels to?" }
	SUB "SG2MIS_1" { TEXT "Kam to...? Zlodìj, zlodìj!" }
	SUB "SG2MIS_2" { TEXT "Kde je ezlo?" }
	SUB "SG2MIS_3" { TEXT "To není dobré. Kam se podìlo?" }
	SUB "SG2MIS_4" { TEXT "Zlodìj!	Meè je pryè!" }
	SUB "SG2RBOD1" { TEXT "Opatrnì, venku je vrah. Vidìl jsem tìlo, které to dokazuje." }
	SUB "SG2RBOD2" { TEXT "Je tu s námi vrah! Nikomu nevìøte!" }
	SUB "SG2RBOD3" { TEXT "Pozor! Byla tu vrada!" }
	SUB "SG2RINT1" { TEXT "Pozor! Kolem bìhá nìjakı tafer." }
	SUB "SG2RINT2" { TEXT "Máme tu vetøelce. Bacha." }
	SUB "SG2RINT3" { TEXT "Údajnì se plíí kolem zlodìj!" }
	SUB "SG2RMIS1" { TEXT "Šiøte zprávu! Byli jsme okradeni!" }
	SUB "SG2RMIS2" { TEXT "Pán byl okraden! Zlodìj v budovì!" }
	SUB "SG2RMIS3" { TEXT "ezlo bylo ukradeno!" }
	SUB "SG2RMIS4" { TEXT "Zlodìj u je uvnitø!" }
	SUB "SG2ROTH1" { TEXT "Zùstaò vzhùru. Myslím, e se nìco dìje." }
	SUB "SG2ROTH2" { TEXT "Pozor! Pøed chvílí jsem vidìl nìco divného!" }
	SUB "SG2ROTH3" { TEXT "Pozor! Nìco se dìje! Pozor na nìco neobvyklého!" }
	SUB "SG2ROTH4" { TEXT "V budovì je vetøelec! Nepuste si ho k tìlu!" }
	SUB "SG2ROTH5" { TEXT "Zlodìj se vloupal dovnitø!" }
	SUB "SG2RUNA1" { TEXT "Mùete sem zavolat pomoc?" }
	SUB "SG2RUNA2" { TEXT "Pojïte sem. Pomoc!" }
	SUB "SG2RUNA3" { TEXT "A pøijedou moji bratøi, nebudeš tak zvesela!" }
	SUB "SG2RUNA4" { TEXT "Zlodìj tady! Stráe!" }
	SUB "SG2SEC_1" { TEXT "Cizinec v budovì!" }
	SUB "SG2SEC_2" { TEXT "Vetøelec je tady!" }
	SUB "SG2SEC_3" { TEXT "Hej, pozor na narušitele!" }
	SUB "SG2SEC_4" { TEXT "Prošel tudy zlodìj!" }
	SUB "SG2SMA_1" { TEXT "Nìkdo se tu kolem taføí." }
	SUB "SG2SMA_2" { TEXT "Co se tu stalo?" }
	SUB "SG2SMA_3" { TEXT "Nìkdo se tu potuloval?" }
	SUB "SG2SMA_4" { TEXT "Kdo to udìlal?" }
	SUB "SG2TELC1" { TEXT "Mám ho! Tudy!" }
	SUB "SG2TELC2" { TEXT "Narušitel je pøímo tam!" }
	SUB "sg2telc3" { TEXT "Vidím ho! Tudy!" }
	SUB "SG2TELC4" { TEXT "Zlodìj! Tudy!" }
	SUB "SG2TELC5" { TEXT "Tady je! Tady!" }
	SUB "SG2TELC6" { TEXT "Zlodìj je pøímo tady! Nenechte ho utéct!" }
	SUB "SG2TELR1" { TEXT "Hej! Podívejte, co tu máme!" }
	SUB "SG2TELR2" { TEXT "Máme v budovì tafra!" }
	SUB "SG2TELR3" { TEXT "Zlodìj tady!" }
	SUB "SG2TELR4" { TEXT "Vetøelec zde!" }
	SUB "SG2WRN11" { TEXT "Vypadni odsud, lumpe! Tady pro tebe nic není." }
	SUB "SG2WRN21" { TEXT "Tohle je tvá poslední šance! Odejdi, nebo budeš èelit následkùm!" }
	SUB "SG2WRNF1" { TEXT "Kdy to tak chceš, chytráku!" }
}