SUB1

{
	TYPE "convo"
	DESCR "Hlídka"
	SUB "SE3DETW1" { TEXT "Máme ho v obranì." }
	SUB "SG306200" { TEXT "Tyhle tlakové dveøe, to je zatracená nuance. Musíš se ubírat z cesty, abys našel tu staføenou páku." }
	SUB "SG306202" { TEXT "Kdo by se sem vloupal? Jediná akce nastane, kdy se nìkdo pokusí sklouznout ze støechy." }
	SUB "SG306204" { TEXT "Hej, to je pravda. Bylo by fajn pro zmìnu vymlátit pár kebulí!" }
	SUB "SG306401" { TEXT "Jo, ale kdy se perou, tak taky nesešermujou vázou. Ta váza prostì zùstane zavøená v doupìti lorda Donala." }
	SUB "SG306403" { TEXT "Ani mi to není nic platné. Ta safírová váza má vìtší cenu ne celı zbytek Randallovho lupu. Nevstoupil jsem do Povìtøí, abych pracoval zadarmo. Chci svùj podíl!" }
	SUB "SG310100" { TEXT "Proè ale smìjí dovnitø jen mágové? Proè nás nechtìjí pustit do svıch vìí?" }
	SUB "SG310102" { TEXT "Ale co s tím vším utajováním? Ani sluebnictvo tam nesmí. Vìøí ti èarodìjové nìkomu?" }
	SUB "SG310200" { TEXT "S tìmito mágy si není radno zahrávat. Vidìl jsem, jak pouili svou magii na starého Bradworta. Pøistihli ho, jak krade lupeny ze stolù v zasedací síni. Jeden z nich pøivolal z nebe velké vrhací koule, hnoucí kameny z mìsíce, a ty mu rozmáèkly jeho ubohou lebku!" }
	SUB "sg312301" { TEXT "Ne u pokladny, protoe kdybych byl zlodìj, tak bych šel tam." }
	SUB "sg312303" { TEXT "Kdy jsou potíe, nìkdo musí hlídat tu holku s pláštìm. Je úplnì sama, nemá si s kım promluvit!" }
	SUB "SG312305" { TEXT "Musím hlídat ten vodní kámen, o kterı se nikdo nezajímá, kromì paní Valerie." }
	SUB "SG3A0MU1" { TEXT "A kdy mi pøinesou veèeøi? To chci vìdìt... kdy mi pøinesou veèeøi...?" }
	SUB "SG3A0MU2" { TEXT "Nechápu, proè bych mìl bıt já ten tady dole, v zimì, tmì a vlhku...." }
	SUB "SG3A0MU3" { TEXT "A pak mají lidé nade mnou všechen svit a dostávají všechny laskavosti a já nemám co jíst celé dny...." }
}
{
	TYPE "bark"
	DESCR "Hlídka"
	SUB "SG3A0TC4" { TEXT "Bah!" }
	SUB "SG3A1__1" { TEXT "Haló? Uka se." }
	SUB "SG3A1__2" { TEXT "Haló? Je tam nìkdo?" }
	SUB "SG3A1__3" { TEXT "Pane, byl jste to vy?" }
	SUB "SG3A1__4" { TEXT "Kdo je tam? Je tam nìkdo?" }
	SUB "SG3A1__5" { TEXT "Co je tam?" }
	SUB "SG3A1_W1" { TEXT "Je to mnou, nebo se nìco pohnulo?" }
	SUB "SG3A1_W2" { TEXT "Tamhle!" }
	SUB "SG3A1H_1" { TEXT "Kdo je tam? Kdo to øekl?" }
	SUB "SG3A1H_2" { TEXT "Nìkdo dìlá rámus?" }
	SUB "SG3A1HW1" { TEXT "Poslouchejte! Slyšíte to?" }
	SUB "SG3A1HW2" { TEXT "Pøestanete dìlat kravál? Myslím, e jsem nìco slyšel." }
	SUB "SG3A1HW3" { TEXT "Slyšel jsi nìjakı rámus?" }
	SUB "SG3A1HW4" { TEXT "Slyšel jsi to?" }
	SUB "SG3A1V_1" { TEXT "Myslím, e jsem nìco vidìl...." }
	SUB "SG3A1VW1" { TEXT "Hej! Myslím, e jsem tady nìco vidìl!" }
	SUB "SG3A1VW2" { TEXT "Podívej se támhle. Vidíš nìco?" }
	SUB "SG3A1VW3" { TEXT "Tamhle! Tam je...! Uh... nìco jsem vidìl... nìco jsem vidìl!" }
	SUB "SG3A1VW4" { TEXT "Podívej se tam. Vidíš nìco?" }
	SUB "SG3A2__1" { TEXT "Hej! Okamitì vylez!" }
	SUB "SG3A2__2" { TEXT "Kdo je tam... ve stínu?" }
	SUB "SG3A2__3" { TEXT "Kdo tam jde? Hej!" }
	SUB "SG3A2__4" { TEXT "Hej! Je tam nìkdo? Kdo je to?" }
	SUB "SG3A2__5" { TEXT "Vylez ven!" }
	SUB "SG3A2H_1" { TEXT "Kdo je tam? Kdo dìlal ten rámus?" }
	SUB "SG3A2H_2" { TEXT "Koho jsem tam slyšel?" }
	SUB "Sg3a2se1" { TEXT "Tak pojï ven!" }
	SUB "Sg3a2se2" { TEXT "Nenu mì, abych tì hledal!" }
	SUB "Sg3a2se3" { TEXT "Kde jsi, ty tafre?" }
	SUB "Sg3a2se4" { TEXT "Brzy tì najdu." }
	SUB "SG3A2V_1" { TEXT "Vidím tì tam! Uka se!" }
	SUB "SG3A3B_1" { TEXT "Hej! Polo ho! Pojï sem!" }
	SUB "SG3A3NA1" { TEXT "Hej, stùj! Nehıbej se!" }
	SUB "SG3A3NA2" { TEXT "Je tu vetøelec!" }
	SUB "SG3A3NA3" { TEXT "Tak jo, teï jsi v tom, zlodìji!" }
	SUB "SG3A3NA4" { TEXT "Nehıbej se!" }
	SUB "SG3A3S_1" { TEXT "Aa! Stát!" }
	SUB "SG3A3S_2" { TEXT "Hej, kdo jsi?!" }
	SUB "SG3A3S_3" { TEXT "Narušitel! Pomoc, pomoc!" }
	SUB "SG3A3S_4" { TEXT "Zlodìj!" }
	SUB "Sg3a3se1" { TEXT "Jen trochu šustni!" }
	SUB "Sg3a3se2" { TEXT "Najdu tì, jen poèkej!" }
	SUB "Sg3a3se3" { TEXT "Vyjdi ven a postav se mi, zlodìji!" }
	SUB "Sg3a3se4" { TEXT "Vra se sem, ty... zbabìlèe!" }
	SUB "SG3ALMA1" { TEXT "Alarm na tebe!" }
	SUB "SG3ALMA2" { TEXT "Jen chvilku a budou tu všichni!" }
	SUB "SG3ALMA3" { TEXT "Spustím alarm!" }
	SUB "SG3ALMW1" { TEXT "Spuste alarm! Já ho zdrím." }
	SUB "SG3ALMW2" { TEXT "Ty! Poplach!" }
	SUB "SG3AMB_1" { TEXT "Wuah! Zbabìlèe! Bojuj se mnou tváøí v tváø!" }
	SUB "SG3AMB_2" { TEXT "Nejzrádnìjší padouch!" }
	SUB "SG3AMB_3" { TEXT "Pojï se mnou bojovat, ty zbabìlèe!" }
	SUB "SG3AMB_4" { TEXT "Do otevøeného prostoru, ty darebáku!" }
	SUB "SG3AMBW1" { TEXT "Pomoc! Útoèí na mì!" }
	SUB "SG3AMBW2" { TEXT "Uah, dostal mì! Vidíte ho?!" }
	SUB "SG3AMBW3" { TEXT "Jsem napaden! Au!" }
	SUB "Sg3atb_1" { TEXT "Hromada bolesti pro tebe!" }
	SUB "Sg3atb_2" { TEXT "Zkus to chytit!" }
	SUB "Sg3atb_3" { TEXT "Nemùeš bìet rychleji ne šíp, tafre!" }
	SUB "SG3ATN_1" { TEXT "Zesyp se!" }
	SUB "SG3ATN_2" { TEXT "Tu máš!" }
    SUB "SG3ATW_1" { TEXT "U tì mám!" }
	SUB "SG3ATW_2" { TEXT "Dám ti lekci!" }
	SUB "SG3ATWW1" { TEXT "Brzy padne!" }
	SUB "SG3BAK_1" { TEXT "Ach jo.... Hádám, e to nic nebylo." }
	SUB "SG3BAK_2" { TEXT "Haló? Je tam nìkdo? ...Uh, asi ne." }
	SUB "SG3BAK_3" { TEXT "No jo. Nevím, co to bylo." }
	SUB "SG3BAK_4" { TEXT "Hmm.... To se mi muselo zdát." }
	SUB "SG3BAK_5" { TEXT "Zdá se, e teï u je klid. Ach jo." }
	SUB "SG3BAK_6" { TEXT "Teï u nic nedìlá rámus." }
	SUB "SG3BAK_7" { TEXT "Nic tady není." }
	SUB "SG3BKD_1" { TEXT "Pøíštì nebudeš tak rychlı!" }
	SUB "SG3BKD_2" { TEXT "Ještì uvidím tvou krev!" }
	SUB "SG3BKD_3" { TEXT "Nemùeš je všechny zablokovat!" }
    SUB "SG3BKDW1" { TEXT "Unavíme ho!" }
	SUB "SG3BLK_1" { TEXT "Moná pøíštì." }
	SUB "SG3BLK_2" { TEXT "Tohle vydrím celı den. Hah!" }
	SUB "SG3BLK_3" { TEXT "Aa! Dobrı pokus!" }
	SUB "SG3BLKW1" { TEXT "Je dost pomalı. Mùeme ho dostat!" }
	SUB "SG3BOD_1" { TEXT "Jsi v poøádku? Ne, ne, samozøejmì, e nejsi v poøádku, promiò." }
	SUB "SG3BOD_2" { TEXT "Zaplatíš, zlodìji!" }
}
{
	TYPE "convo"
	DESCR "Hlídka"
	SUB "SG3C0101" { TEXT "Hej, zítra jdu do Medvìdí Jámy. Chceš se pøidat?" }
	SUB "SG3C0103" { TEXT "Cooo? Ty mìkkıši! Medvìdi mají tyhle nové náhubky se zapuštìnımi hroty. Kdy jsem tam byl naposled, tak si tam opravdu vyškrábali oèi." }
	SUB "SG3C0105" { TEXT "Hah! Pøekvapuje mì, e vùbec dìláš tuhle práci.... 'Úú tolik krve, z toho se mi obrací bøíško!'" }
	SUB "SG3C0107" { TEXT "ádné háky na tlapy? Co tam dìlají? Jen tak do sebe vráejí?" }
	SUB "SG3C0109" { TEXT "Medvìdi? To si ze mì dìláš prdel! Vypadají docela neškodnì, pokud nemají na sobì postroj." }
	SUB "SG3C0111" { TEXT "Wou.... Zabijáètí medvìdi. To bych chtìl vidìt...." }
	SUB "Sg3c0602" { TEXT "Ná, ty pokadé vyhraješ. Pøišel jsem u o dost penìz." }
	SUB "Sg3c0604" { TEXT "Jako by mi to pomohlo, ty tafre." }
	SUB "Sg3c0606" { TEXT "Nooo...." }
	SUB "Sg3c0608" { TEXT "Mmm, dobøe. Eee... Kámen!" }
	SUB "Sg3c0610" { TEXT "Proklatì! Jak to dìláš? Tady máš." }
	SUB "Sg3c0612" { TEXT "Dabl nebo nic! Kámen èi mince?" }
	SUB "Sg3c0614" { TEXT "K èertu s tebou! Na." }
	SUB "Sg3c0616" { TEXT "Jdi ode mì pryè! Poslednì jsem ti dluil tøi tıdny." }
	SUB "SG3C1102" { TEXT "Neboj. Nevyplaším se a nezapnu alarm, a uslyším krysu... Jako minule." }
	SUB "Sg3c1402" { TEXT "S tìmi koly a èepelemi a vùbec?" }
	SUB "Sg3c1404" { TEXT "Velká chyba! Paní pøijde domù, zapomene zatáhnout za páku, a rozseká ji to na cucky!" }
	SUB "Sg3c1406" { TEXT "Nemluvì o tom, e dva chlápci s meèi u nedostanou zaplaceno." }
	SUB "Sg3c1501" { TEXT "Jorek mi øekl, e Kladiváøi zavøou Horoštìp." }
	SUB "Sg3c1503" { TEXT "Cojávím.... Spadly do studny nebo tak nìco. Kadopádnì u nemají dost chlapù." }
	SUB "Sg3c1602" { TEXT "Jo. Cyric nad Bohnem, tøi ku dvìma. A taky a skonèí válka." }
	SUB "Sg3c1604" { TEXT "Jasnì. Peníze hned." }
	SUB "Sg3c1701" { TEXT "Hele, pamatuješ, jak baronova policie sejmula DeWalla?" }
	SUB "Sg3c1703" { TEXT "Slyšel jsem, e ho udal Raputo." }
	SUB "Sg3c1902" { TEXT "Co tím myslíš? Co je s námi?" }
	SUB "Sg3c1904" { TEXT "To je blbost! Lidi, o které si máš dìlat starosti, jsou uvnitø." }
	SUB "Sg3c1906" { TEXT "Ahá." }
	SUB "Sg3c2002" { TEXT "Coe nedìlám?" }
	SUB "Sg3c2004" { TEXT "Kladiva to maj dobrı. Prostì je umlátí na plocho." }
	SUB "Sg3c2302" { TEXT "Myslel jsem, e má dobrou náladu...." }
	SUB "Sg3c2401" { TEXT "Vidìli jste novou místnost? Ty... stromy?" }
	SUB "Sg3c2403" { TEXT "Rád tam dìlám všechny obchùzky." }
	SUB "Sg3c2502" { TEXT "Aa, já ne. Koukaj, kdy si trochu zdøímneš." }
	SUB "Sg3c3302" { TEXT "Radìji spím." }
	SUB "Sg3c3402" { TEXT "Mùj taky." }
}
{
	TYPE "bark"
	DESCR "Hlídka"
	SUB "SG3C3501" { TEXT "Buï zdráv, bratøe ve zbrani." }
	SUB "Sg3c3601" { TEXT "Co se dìje?" }
	SUB "Sg3c3702" { TEXT "Jo, nikdy se nic nedìje." }
	SUB "Sg3c3801" { TEXT "Stát! Kdo tam chodí?" }
	SUB "SG3CHGA1" { TEXT "Øekl sis o to!" }
	SUB "Sg3chga2" { TEXT "Je po tobì, kámo!" }
	SUB "SG3CHGW1" { TEXT "Spoleènì ho mùeme dostat!" }
	SUB "SG3CHGW2" { TEXT "Chyte ho!" }
	SUB "SG3CHGW3" { TEXT "Chyte toho tafra!" }
	SUB "SG3DET_1" { TEXT "Ach, toèíme elvu?" }
	SUB "SG3DET_2" { TEXT "Poèkám, tafre...! Mám èas." }
	SUB "SG3DET_3" { TEXT "Utíkaš strachy?" }
	SUB "SG3FRE_1" { TEXT "Pokraèujte v ceste." }
	SUB "SG3FRE_2" { TEXT "No tak, dej si pohov." }
	SUB "SG3HIT_1" { TEXT "Krvácíš!" }
	SUB "SG3HIT_3" { TEXT "U jsi pøipraven zemøít?" }
	SUB "SG3HIT_4" { TEXT "Wou-hoho! Štípe to trochu?" }
	SUB "SG3HITW1" { TEXT "U mu to dlouho nevydrí!" }
	SUB "SG3HITW2" { TEXT "Teï ho udeø!" }
	SUB "SG3HLOW1" { TEXT "Ne! Nemùu... u víc......." }
	SUB "SG3HND_2" { TEXT "To mìlo bolet?" }
	SUB "SG3HND_3" { TEXT "Pìkné milostné pohlazení, tafre!" }
	SUB "SG3LAR_1" { TEXT "Podívejte se na toho tafra! Hej, tady!" }
    SUB "SG3LAR_2" { TEXT "Podívej se sem!" }
	SUB "SG3LOS_1" { TEXT "O-ou, je nìkde tady." }
	SUB "SG3LOS_2" { TEXT "Hej ty.... Vra se." }
	SUB "SG3LOS_3" { TEXT "Kam šel? Sakra." }
	SUB "SG3LOS_4" { TEXT "Sakra. Kde je ten zlodìj teï?" }
	SUB "Sg3m0201" { TEXT "Útoèí na nás!" }
	SUB "SG3MIS_1" { TEXT "Tohle by mìlo bıt tady." }
	SUB "SG3MIS_2" { TEXT "Nìjakı tafer ukradl ezlo!" }
	SUB "SG3MIS_3" { TEXT "Zlodìj tu byl!" }
}
{
	TYPE "convo"
	DESCR "Hlídka"
	SUB "SG3MUTT1" { TEXT "Zase pozdì v noci... a já jsem jedinı na celém tomhle patøe... Ké bych mìl vlastní postel..." }
	SUB "SG3MUTT2" { TEXT "Ké bych mìl práci, která by byla lépe placená ne tahle. Jsem utahanı, ubolenı, je mi špatnì,..." }
	SUB "SG3MUTT3" { TEXT "Co to tam dole sakra leí...?" }
}
{
	TYPE "bark"
	DESCR "Hlídka"
    SUB "SG3RBOD1" { TEXT "Hlídej si záda! Vidìl jsem dalšího podobného s dírou." }
	SUB "SG3RBOD2" { TEXT "Pozor! Ten vetøelec je zabiják!" }
	SUB "SG3RBOD3" { TEXT "Pozor! Zlodìj je i vrah." }
	SUB "SG3RBOD4" { TEXT "To on zabil šéfa. Neodejde odsud ivı!" }
	SUB "SG3RINT1" { TEXT "Dávejte si pozor na lupièe. Nìkoho jsem pøed chvíli vidìl." }
	SUB "SG3RINT2" { TEXT "Buïte ve støehu. V budovì je vetøelec." }
    SUB "SG3RINT3" { TEXT "Zlodìj je... uvnitø..." }
	SUB "SG3RMIS1" { TEXT "Pozor na zlodìje. Pán nás odmìní, pokud se nám podaøí získat jeho zboí zpìt." }
	SUB "SG3RMIS2" { TEXT "Øeknìte ostatním: Byly ukradeny vìci." }
	SUB "SG3RMIS3" { TEXT "Zlodìj má meè." }
    SUB "SG3ROTH1" { TEXT "Buï ve støehu. Myslím, e se pøed chvílí nìco stalo." }
	SUB "SG3ROTH2" { TEXT "Vidìl jsi v poslední dobì nìco? Nìco jsem zahlédl." }
	SUB "SG3ROTH3" { TEXT "Pozor! Nìco se tam vzadu dìlo." }
	SUB "SG3ROTH4" { TEXT "Zlodìj, pøed kterım nás šéf varoval, je nìkde poblí." }
	SUB "SG3RUNA1" { TEXT "Stráe! Tudy!" }
	SUB "SG3RUNA2" { TEXT "Ke mnì! Kryjte mì!" }
	SUB "SG3RUNA3" { TEXT "Stráe! Stráe!" }
	SUB "SG3RUNA4" { TEXT "Tady!" }
	SUB "SG3SEC_1" { TEXT "Podívej se na to. Byl tu narušitel." }
	SUB "SG3SEC_2" { TEXT "Pán by se o tom mìl dozvìdìt." }
	SUB "SG3SEC_3" { TEXT "Dostal se sem nìjakı tafer." }
	SUB "SG3SEC_4" { TEXT "Zlodìj je uvnitø." }
	SUB "SG3SMA_1" { TEXT "Hej, takhle to nemá vypadat!" }
	SUB "SG3SMA_2" { TEXT "Tohle není správnì." }
	SUB "SG3TELC1" { TEXT "Našel jsem ho!" }
	SUB "SG3TELC2" { TEXT "Mám ho! Tudy!" }
	SUB "Sg3telc3" { TEXT "Tady je! Pospìšte si!" }
	SUB "SG3TELC4" { TEXT "Tady! Opatrnì... je ozbrojenı!" }
	SUB "SG3TELC5" { TEXT "Hej! Narušitel je pøímo tady!" }
	SUB "SG3TELR1" { TEXT "Hej, mám tu nìkoho!" }
	SUB "SG3TELR2" { TEXT "Mám tu narušitele!" }
	SUB "SG3TELR3" { TEXT "Zlodìj je tady!" }
	SUB "SG3TELR4" { TEXT "Je tu zlodìj!" }
	SUB "SG3WRN11" { TEXT "Bìte pryè! Vstup na cizí pozemek zakázán." }
	SUB "SG3WRN21" { TEXT "U ádná varování, darebáku! Prac se odsud!" }
	SUB "SG3WRNF1" { TEXT "To by staèilo, máš to mít!" }
} 
