SUB1

{
	TYPE "bark"
	DESCR "Kladiváø"
	SUB "hm2a0ch1" { TEXT "A Stavitel øekl, 'Je-li základ slabı, bìduješ a skøípeš zuby? ádáš snad by se sám spravil? Kdepak, zbouráš ho a znovu zaèneš. I tak to se všemi Mımi Dìtmi bude, a jsou z kamene, nebo z masa.'" }
	SUB "hm2a0ch2" { TEXT "A vìøící promluvili, 'Hle, ezlem pravosti spravedlnost ukována byla. Budeš-li zámìrùm, je Stavitel uèinil, naslouchati a ustanovení jeho zachovávati, podíl na jeho triumfech míti budeš.'" }
	SUB "hm2a0ch3" { TEXT "Naším štítem bdìlost jest, je pøed minulostí bídnou chrání nás. Naší zbraní poznání jest, jím cestu k budoucnosti osvícené razíme si." }
	SUB "hm2a0mu3" { TEXT "Nerozumìjí nám, nerozumìjí... èlovìèe pravdivı...." }
	SUB "HM2A1__1" { TEXT "Ano, kdo ke mnì pøichází?" }
	SUB "hm2a1__2" { TEXT "Kdo tam prochází?" }
	SUB "HM2A1__3" { TEXT "To ty jest?" }
	SUB "HM2A1__4" { TEXT "Co je to? Kdo jde?" }
	SUB "HM2A1_W1" { TEXT "Bylo tam nìco?" }
	SUB "HM2A1H_1" { TEXT "Co je to slyšeti?" }
	SUB "HM2A1H_2" { TEXT "Kdo ten zvuk udìlati?" } - rovnaky pripad ako riadok vyssie, nepouziva sa takyto tvar v jazyku, skusil by som bud neurcitok udelal alebo a to nebude doslovny preklad ale Kdo jest toho zvuku puvodcem
	SUB "HM2A1HW1" { TEXT "Nìco rámus udìlalo. Poslouchej...." }
	SUB "hm2a1hw2" { TEXT "Slyšels to také? Myslím, e tam nìkdo jest." }
	SUB "hm2a1hw3" { TEXT "Slyšels nìco? Co to bıti?" }
	SUB "HM2A1V_1" { TEXT "Ukazují mi mé oèi pravdu?" }
	SUB "hm2a1vw1" { TEXT "Co to bylo? Vidìls to?" }
	SUB "HM2A1VW2" { TEXT "Tamhle...! Vidìls nìco?" }
	SUB "hm2a1vw3" { TEXT "Myslím, e jsem tam nìco vidìl." }
	SUB "hm2a2__1" { TEXT "Jsi... Ne, poèkej.... Kdo jest?" }
	SUB "hm2a2__2" { TEXT "Myslíš, e se mì posmívati budeš? Uka se!" }
	SUB "hm2a2__3" { TEXT "Kdo tam chodí? Zastav se a uka tváø svou." }
	SUB "hm2a2__4" { TEXT "Co se to tam dìje?" }
	SUB "hm2a2h_1" { TEXT "To jsem slyšel! Uka se, nebo následkùm èeliti budeš!" }
	SUB "hm2a2h_2" { TEXT "Kdo tam chodí? Kdo ten rámus udìlal?" }
	SUB "hm2a2se1" { TEXT "Stavitel tì špehovati bude, kdy já ne." }
	SUB "hm2a2se2" { TEXT "Nevydrí lest tvá." }
	SUB "hm2a2se3" { TEXT "Stín tvùj nezakryje tì navdy!" }
	SUB "hm2a2se4" { TEXT "Vyjdou zase ven, a kdokoli jsou!" }
	SUB "hm2a2v_1" { TEXT "Vidím tì tam. Kdos?" }
	SUB "hm2a3b_1" { TEXT "Cos to udìlal? Vrada! Vrada!" }
	SUB "hm2a3b_2" { TEXT "Zabils bratra. Vrah!" }
	SUB "hm2a3na1" { TEXT "Litovati budeš, es obtìoval mì!" }
	SUB "hm2a3na2" { TEXT "Nemysli si, e teï zmizíš! Zøím tì tam." }
	SUB "hm2a3na3" { TEXT "Pøijï blí a mùj bøit pocítíš." }
	SUB "hm2a3s_1" { TEXT "Stùj! Kdos?" }
	SUB "hm2a3s_2" { TEXT "Hah! Odkud pøišels?" }
	SUB "hm2a3s_3" { TEXT "Stùj! Tohle místo není dáno ti." }
	SUB "hm2a3se1" { TEXT "Najdu tì i rozdrtím tì!" }
	SUB "hm2a3se2" { TEXT "Pøestaòs hrát i èel mnì!" }
	SUB "hm2a3se3" { TEXT "Nebudeš se navdy skrıvati!" }
	SUB "hm2a3se4" { TEXT "Stavitel mì dovede k tobì!" }
	SUB "hm2alma1" { TEXT "Spuste poplach!" }
	SUB "hm2alma2" { TEXT "Køiète 'Zlosyn!' Køiète 'Utíká' A poplach zní!" }
	SUB "hm2alma3" { TEXT "Køiète 'Zlodìj!' Køiète 'Zloduch!' A poplach zní!" }
	SUB "hm2almw1" { TEXT "Na poplach se odeber. Já linii udrím!" }
	SUB "hm2amb_1" { TEXT "Vyjdi ze stínu a èel hnìvu mému!" }
	SUB "hm2amb_2" { TEXT "Zbabìlèe! Vyjdi ven!" }
	SUB "hm2amb_3" { TEXT "Bojíš se mi èeliti jako mu mui?" }
	SUB "hm2amb_4" { TEXT "Vyjdi z úkrytu svého, zlosynu!" }
	SUB "hm2ambw1" { TEXT "Zranìn jsem! Vidíš toho mue?" }
	SUB "hm2ambw2" { TEXT "Pomoz mi! Jsem tísnìn!" }
	SUB "hm2ambw3" { TEXT "Varuj se luèištníka ve stínech." }
	SUB "hm2atl_1" { TEXT "Staviteli, ruku mou veï!" }
	SUB "hm2atl_2" { TEXT "Staviteli, sluebníku svému pomoz!" }
	SUB "hm2atn_1" { TEXT "Stezka tvá neviditelná konèí zde, zlodìji." }
	SUB "hm2atn_2" { TEXT "Kladivo spravedlnosti tìce dopadne na tebe!" }
	SUB "hm2atn_6" { TEXT "Høích tvùj smrt pøinesl ti!" }
	SUB "hm2atn_7" { TEXT "Stavím odplatu tvou!" }
	SUB "hm2atn_8" { TEXT "Stál ivot tvùj za to, zlodìji?" }
	SUB "hm2atn_9" { TEXT "Osud tvùj v Knize zapsán jest!" }
	SUB "hm2atp_1" { TEXT "Vidíš, jak zkáza tvá se blíí!" }
	SUB "hm2atp_2" { TEXT "Kladivu Stavitele neunikneš!" }
	SUB "hm2atp_3" { TEXT "Le hbitì a opravdovì!" }
	SUB "hm2atw_1" { TEXT "Smrt tvá na dosah jest teï!" }
	SUB "hm2atw_2" { TEXT "Zkáza tvá padá na tebe!" }
	SUB "hm2atww1" { TEXT "Máchni se mnou a skonèi ivot zlosyna tohoto!" }
	SUB "hm2bak_1" { TEXT "Stavitelùv mír jest teï." }
    SUB "hm2bak_2" { TEXT "Nervy své uklidniti musím." }
	SUB "hm2bak_3" { TEXT "Vše v klidu jest teï. Nic to bıti." }
	SUB "hm2bak_4" { TEXT "Hmm... Nenapadlo by mì, e krysy na Stavitelùv dùm troufnou si." }
	SUB "hm2bak_5" { TEXT "Mor na ty krysy!" }
    SUB "hm2bak_6" { TEXT "Nic k vidìní u není, se obávám." }
	SUB "hm2bkd_1" { TEXT "Ještì krváceti budeš, zlosyne!" }
	SUB "hm2bkd_2" { TEXT "To tì dlouho nezachrání!" }
	SUB "hm2bkd_3" { TEXT "Utíkati budeš teï?" }
	SUB "hm2bkdw1" { TEXT "Zloduch rychlı jest, ale my ho pøemùem!" }
	SUB "hm2blk_1" { TEXT "Pomalı pøíliš jseš!" }
	SUB "hm2blk_2" { TEXT "Tvé ruce na mì nedosáhnou!" }
	SUB "hm2blkw1" { TEXT "Heh, jeho údery slabé jsou, bratøe!" }
	SUB "hm2bod_1" { TEXT "Ty... pomstìn budeš!" }
	SUB "hm2bod_2" { TEXT "Pøivolej hnìv Stavitele na sebe, kterıs to udìlal!" }
	SUB "hm2bod_3" { TEXT "Tìlo.... Vrada! Ocel pomsty pout zbavena a probuzená jest!" }
}
{
	TYPE "convo"
	DESCR "Kladiváø"
	SUB "hm2c0702" { TEXT "Tak jest od dob renovace." }
	SUB "hm2c0704" { TEXT "Deštì pøijdou a pøejde to." }
	SUB "hm2c0901" { TEXT "Dokonce i Baron nakonec zakroèí proti zlu... kdy je dostateènì dùraznì pobízen." }
	SUB "hm2c0903" { TEXT "Vìru, nìkteøí øekli mi, e to vlastní bratøi jeho byli, kdo v høíchu udali ho." }
	SUB "hm2c1101" { TEXT "Další únik vody z kanalizace, jak jsem vèera slyšel." }
    SUB "hm2c1103" { TEXT "Domníváš se, e bychom bøemeno jejich vzíti mìli? Èerpadlo nebo soukolí pro nás nic cizího není." }
	SUB "hm2c1202" { TEXT "Síla a odhodlání naše, to u není, co bıvalo." }
	SUB "hm2c1302" { TEXT "Jak troufnouti si mohl! Copak studu zbaven?" }
	SUB "hm2c1304" { TEXT "Hah. Šemenové lajdáètí øemeslníci jsou a Tarius dobøe pouèen jest o tom." }
	SUB "hm2c1501" { TEXT "Dolan øekl mi, e jeho uèeò novı uzávìr uvolnil na trysku parním a opaøil se." }
	SUB "hm2c1503" { TEXT "Dolan øíká, e chlapec bude íti, no Øád mùe opustiti." }
	SUB "hm2c1702" { TEXT "I ty." }
	SUB "hm2c1802" { TEXT "Dobøe i tak." }
	SUB "hm2c1901" { TEXT "Chvála Staviteli." }
	SUB "hm2c2001" { TEXT "Ké Kladivo tvé máchá pravdou." }
	SUB "hm2c2101" { TEXT "Buï zdráv, bratøe." }
	SUB "hm2c2202" { TEXT "Mé díky, bratøe." }
}
{
	TYPE "bark"
	DESCR "Kladiváø"
	SUB "hm2chga2" { TEXT "Poslední varování tvé!" }
	SUB "hm2chgw1" { TEXT "Pøines Kladivo Pravosti své proti vetøelci tomuto!" }
	SUB "hm2chgw2" { TEXT "Udeø se mnou, bratøe mùj!" }
	SUB "hm2chgw3" { TEXT "Máchej, bratøe! Máchej!" }
	SUB "hm2det_1" { TEXT "Zastrašen jseš, padouchu?!" }
	SUB "hm2det_2" { TEXT "Pouze prodluuješ osud svùj!" }
	SUB "hm2det_3" { TEXT "Pokus tvùj ti nic platnı nebude!" }
	SUB "hm2detw1" { TEXT "Zloduch brání se!" }
	SUB "hm2hit_1" { TEXT "Heh! Zbıvá jeden høebík do rakve tvé!" }
	SUB "hm2hit_2" { TEXT "Vzdej se bolesti své!" }
	SUB "hm2hit_3" { TEXT "Krev tvá silnìji støíká!" }
	SUB "hm2hit_4" { TEXT "A vyjeví se ti!" }
	SUB "hm2hitw1" { TEXT "Sraz i nepøítele!" }
	SUB "hm2hitw2" { TEXT "Nemùe se nám postavit!" }
	SUB "hm2hlo_1" { TEXT "Arrggh! Staviteli støe mne!" }
	SUB "hm2hlow1" { TEXT "Staviteli, pomoz nám!" }
	SUB "hm2hnd_1" { TEXT "Ruka tvá silnìjší bıt musí , kdy útoèí na mì!" }
	SUB "hm2hnd_2" { TEXT "Myslíš si, es ublíil mi?" }
	SUB "hm2hnd_3" { TEXT "Zbroj má proti takovım jest, jak tys, odolná!" }
    SUB "hm2lar_1" { TEXT "Stavitel toho proklíná, kdo zkázu tuto pøivolal!" }
	SUB "hm2lar_2" { TEXT "Zlomenı trám lze znovu opravit, ale pokøivená duše musí bıt vyvrácena z koøenù." }
	SUB "hm2los_1" { TEXT "Ustup tam, kde vysmívati mohu se ti, zlosyne." }
	SUB "hm2los_2" { TEXT "Kam schoval se?" }
	SUB "hm2los_3" { TEXT "Neukryješ se navìky." }
}
{
	TYPE "convo"
	DESCR "Kladiváø"
	SUB "hm2m1001" { TEXT "Kdo jseš? ádnı novic nejseš...! Poplach, vetøelec!" }
	SUB "hm2m1002" { TEXT "Nemáš snad nìjakou práci, novici?" }
    SUB "hm2m1003" { TEXT "Novici tu nemaj co pohledávat, bratøe. Nejlepší bude, kdy odejdeš, ne si toho všimnou Mistøi Kováøi." }
	SUB "hm2m1004" { TEXT "Novici, nechceš pro mì nìco udìlati? Bratr tvùj svícen støíbrnı nesl od oltáøe sem do jídelny a tuším, e jej tam zapomnìl. Prosím, pospìš si a pøines mi ho." }
	SUB "hm2m1005" { TEXT "Ach, dìkuji, novici. Mùeš ho poloiti na podlahu vedle oltáøe, abych ho mohl znovu posvìtiti." }
	SUB "hm2m1006" { TEXT "Tvá rychlost nevhodná jest, novici. Nasaï tempo dùstojnìjší." }
	SUB "hm2m1007" { TEXT "Dobrı den, novici." }
	SUB "hm2m1008" { TEXT "Stavitel ti udìluje moudrost svou, mladíku." }
	SUB "hm2m1009" { TEXT "Zvedni bránu!" }
	SUB "hm2m1010" { TEXT "Pøedlo své povìøení, jinochu." }
	SUB "hm2m1011" { TEXT "Není ti dovoleno... Poèkej! Podvodník jseš! Spuste poplach!" }
	SUB "hm2mis_1" { TEXT "Nepokradeš v domì Stavitele!" }
	SUB "hm2mis_2" { TEXT "Zemì pohanská pohltí toho, jen kradl!" }
}
{
	TYPE "bark"
	DESCR "Kladiváø"
	SUB "hm2rbod1" { TEXT "Pozvedni ocel svou v pomstì krvavé, bratøe mùj! Zlodìj vradil!" }
	SUB "hm2rbod2" { TEXT "Pøiprav pai svou k pomstì krvavé. Tìmito sínìmi se plíí vrah." }
	SUB "hm2rint1" { TEXT "Mezi náma vetøelec jest. Nedovol mu kolem tebe projít." }
	SUB "hm2rint2" { TEXT "Prošel tudy zlosyn jakısi. Buï ve støehu." }
	SUB "hm2rint3" { TEXT "Šel tudy zlodìj? Buï opatrnı, protoe má zbranì." }
	SUB "hm2rmis2" { TEXT "Pozor na zlodìje. Nakonec mu to pøinese jen malı uitek." }
	SUB "hm2roth1" { TEXT "Zùstaò vzhùru! Obávám se, e se nìco dìje." }
	SUB "hm2roth2" { TEXT "Opatrnì. Dávej pozor na cokoli neobvyklého." }
	SUB "hm2roth3" { TEXT "Probuï se, ty lenochu. Pøed chvílí vidìl jsem divného nìco. Dr hlídku." }
	SUB "hm2runa1" { TEXT "Pøineste mi na pomoc zbranì své!" }
	SUB "hm2runa2" { TEXT "Pøijïte ke mnì! Napaden jsem!" }
	SUB "hm2runa3" { TEXT "Bratøi moji, pojïte posílit druha svého suovaného!" }
	SUB "hm2sec_1" { TEXT "Naše svatynì narušena jest!" }
    SUB "hm2sec_2" { TEXT "Mezi náma ten jest, kdo by nemìl bıti." }
	SUB "hm2sec_3" { TEXT "Pozor na vetøelce." }
	SUB "hm2sma_1" { TEXT "Nìco tu mluví varovnì." }
	SUB "hm2sma_2" { TEXT "Coe? Byl tu nìkdo?" }
	SUB "hm2telc1" { TEXT "Zlodìj je na dosah. Nenechte ho utéct!" }
	SUB "hm2telc2" { TEXT "Vidím ho. Tudy!" }
	SUB "hm2telc3" { TEXT "Pomoz mi tomuto høíšníkovi jeho daò zaplatiti!" }
	SUB "hm2telr1" { TEXT "Propùjè mi sílu svou, abych chytil tohoto mue." }
	SUB "hm2telr2" { TEXT "Zlodìj! Zlodìj! Za ním!" }
	SUB "hm2telr3" { TEXT "Utíká nám vìzeò! Tudy!" }
	SUB "hm2telr4" { TEXT "Vetøelec! Vrhnìte se na nìj!" } 
}