SUB1

{
	TYPE "bark"
	DESCR "Kladiváø"
	SUB "hm106500" { TEXT "Stavitel mi je svìdkem, najdu tì a potøísním zdi Horoštìpu krví tvou, zlodìji!" }
	SUB "HM1A0CH1" { TEXT "A slovo šlo pøed ním na vánku nesoucím naši spásu. Zde jest alespoò mu s myslí generála a srdcem básníka, ale také s rukama stavitele. On nás ze zemì pozvedne." }
	SUB "HM1A0CH2" { TEXT "Naším štítem bdìlost jest, je nás pøed minulostí bídnou chrání. Naší zbraní poznání jest, jím cestu k budoucnosti osvícené razíme si." }
	SUB "HM1A0CH3" { TEXT "Kladivo, kovadlina, vıheò a oheò, zaeòte Lháøe Kopytnatého. Støecha a vrata, cihla a trám, zaeòte Šejdíøe ze snù našich." }
	SUB "HM1A0MU1" { TEXT "Hmm.... Proè zrovna já musím tady dole bıti, hlídati to všechno a..." }
	SUB "HM1A0MU2" { TEXT "A nevím, proè bych umístìn tady mìl bıti, kdy všichni ostatní venku bìhaj... Kdy veèeøi dostanu? To bych vìdìl rád...." }
	SUB "HM1A0MU3" { TEXT "Všichni ti lidé, se kterımi pracovati musím, tak neschopní jsou, tak hloupí, tak líní.... Nechápu, proè bych mìl zrovna já ten bıti, kdo má k tìmto nekompetentním lidem postaven bıti...." }
	SUB "HM1A1__1" { TEXT "Identifikovati se. Nìkdo tam jest?" }
	SUB "HM1A1__2" { TEXT "Státi! Nìkdo tam jest?" }
	SUB "HM1A1__3" { TEXT "Nìkdo pøišels?" }
	SUB "HM1A1__4" { TEXT "Pøedstoupiti a promluviti, jsou-li tam." }
	SUB "HM1A1_W1" { TEXT "Nìco tamhle jest?" }
	SUB "HM1A1H_1" { TEXT "Hmm, zdálo se mi, e nìco zaslechl jsem." }
	SUB "HM1A1H_2" { TEXT "Vydalo nìco zvuk?" }
	SUB "HM1A1HW1" { TEXT "Slyšels nìco?" }
	SUB "HM1A1HW2" { TEXT "Slyšeti nìco?" }
	SUB "HM1A1HW3" { TEXT "Tiše. Já... slyšeti nìco." }
	SUB "HM1A1V_1" { TEXT "Hmm.... Zdálo se mi, e jsem nìco zazøel." }
	SUB "HM1A1VW1" { TEXT "Vidìls tam nìco?" }
	SUB "HM1A1VW2" { TEXT "Vidìti nìkoho?" }
	SUB "HM1A1VW3" { TEXT "Vidìls to také?" }
	SUB "HM1A2__1" { TEXT "Kdo je to tam? Promluviti." }
	SUB "HM1A2__2" { TEXT "Tamhle! Pøedstoupiti a øeknou jméno své." }
	SUB "HM1A2__3" { TEXT "Státi! Co je to tam?" }
	SUB "HM1A2__4" { TEXT "U Stavitele, zjev se!" }
	SUB "HM1A2H_1" { TEXT "Slyším je. Pøed zraky se ukáou vmiku." }
	SUB "HM1A2H_2" { TEXT "Slyšel jsem to. Na míste stùj!" }
	SUB "Hm1a2se1" { TEXT "Kde jseš, zlosyne?" }
	SUB "Hm1a2se2" { TEXT "ádnı strach, špehovati budu tì ." }
	SUB "Hm1a2se3" { TEXT "Nebudeš se skrıvati na vìky." }
	SUB "Hm1a2se4" { TEXT "Skrıvání nezachrání tì." }
	SUB "HM1A2V_1" { TEXT "Vidím tì tam. Kdo jseš?" }
	SUB "HM1A3B_1" { TEXT "Stùj! Co to jest za ohavnı èin?" }
	SUB "HM1A3B_2" { TEXT "Co to jest? Vrahoun! Teï Staviteli zaplatíš!" }
	SUB "HM1A3NA1" { TEXT "Stùj! Jseš vìzeò mùj!" }
	SUB "HM1A3NA2" { TEXT "Zotrvej na místì." }
	SUB "HM1A3NA3" { TEXT "Stùj, zlodìji! Vidím tì. Neuteèeš!" }
	SUB "HM1A3NA4" { TEXT "Odhoï zbraò! A...nehıbej se." }
	SUB "HM1A3S_1" { TEXT "U Stavitele, od kterak pøišels?" }
	SUB "HM1A3S_2" { TEXT "Z jakého to stínu vzešels, zlosynu?" }
	SUB "HM1A3S_3" { TEXT "Rukou Stavitele...!" }
	SUB "HM1A3S_4" { TEXT "Zpátky do cely tvé, zlosynu!" }
	SUB "Hm1a3se1" { TEXT "Stopovati vytrvale tì budu, zlodìji!" }
	SUB "Hm1a3se2" { TEXT "Neunikneš mì!" }
	SUB "Hm1a3se3" { TEXT "Skoncuj se skrıváním, zbloudilèe." }
	SUB "Hm1a3se4" { TEXT "Nemùeš ve stínu zùstat na vìky!" }
	SUB "HM1ALMA1" { TEXT "Nech stavitelùv kov zvoní tvé záhubì!" }
	SUB "HM1ALMA2" { TEXT "Mluv, alarmuj a pøivolej své svìøence!" }
	SUB "HM1ALMW1" { TEXT "Jdi a vyhlaš poplach!" }
	SUB "HM1AMB_1" { TEXT "Ááá, nejhorší zbabìlost!" }
	SUB "HM1AMB_2" { TEXT "Èelem postav se mi, zlosyne!" }
	SUB "HM1AMB_3" { TEXT "Vyjdi ze svého stínu a postav se mé oceli!" }
	SUB "HM1AMB_4" { TEXT "Tvá zrada tì odsoudí k zániku!" }
	SUB "HM1AMBW1" { TEXT "Stùj pøi mnì, bratøe, nebo jsem zasaen!" }
	SUB "HM1AMBW2" { TEXT "Jsem... napaden!" }
	SUB "Hm1ambw3" { TEXT "Zøels, kdo to udìlal?" }
	SUB "HM1ATL_1" { TEXT "Staviteli! Dej mi sílu!" }
	SUB "HM1ATL_2" { TEXT "Staviteli! Pomoz mé ránì!" }
	SUB "HM1ATN_1" { TEXT "Polo se na mou kovadlinu, zlodìji!" }
	SUB "HM1ATN_2" { TEXT "Tvé klouby budou rozštípány, ne odsud odejdeš!" }
	SUB "HM1ATN_6" { TEXT "Zhroutiti se pøed Stavitele silou!" }
	SUB "HM1ATN_7" { TEXT "Prolita tvá krev bude!" }
	SUB "HM1ATN_8" { TEXT "Pøijmi ránu svou!" }
	SUB "HM1ATN_9" { TEXT "Pocítíš hrot høíchu svého!" }
	SUB "Hm1atp_1" { TEXT "Stavitelova ruka srazí je na zvolání mé!" }
	SUB "Hm1atp_2" { TEXT "Sesílám jejich znièení!" }
	SUB "Hm1atp_3" { TEXT "Staviteli, sraz tohoto zlosyna!" }
	SUB "HM1ATW_1" { TEXT "Stavitelova ruka mi brzy dopøeje vítìzství!" }
	SUB "HM1ATW_2" { TEXT "Nyní selháváš!" }
	SUB "HM1ATWW1" { TEXT "Ještì jeden úder, bratøe!" }
	SUB "HM1BAK_1" { TEXT "Hmm.... Teï u tam nic není." }
	SUB "HM1BAK_2" { TEXT "Teï se zdá bıt všechno v klidu." }
	SUB "HM1BAK_3" { TEXT "Teï se zdá, e tam nic není." }
	SUB "HM1BAK_4" { TEXT "Na.... vskutku, pouhé krysy." }
	SUB "HM1BAK_5" { TEXT "No, teï u nic nevidím." }
	SUB "HM1BAK_6" { TEXT "Pouhı vítr bıti." }
	SUB "HM1BAK_7" { TEXT "Hmm.... Hluk ustal. Bıti to nic nepochybnì." }
	SUB "HM1BAK_8" { TEXT "Hmm, spytuju se, co to bylo, ale zdá se, e u je to pryè." }
	SUB "HM1BKD_1" { TEXT "Tentokrát máš štìstí!" }
	SUB "HM1BKD_2" { TEXT "Nemùeš vydret vìènì!" }
	SUB "HM1BKD_3" { TEXT "Kdy ne tento úder, tak pøíští vyádá si tì!" }
	SUB "HM1BKDW1" { TEXT "Dostaneš se pøes jeho strá?" }
	SUB "HM1BLK_1" { TEXT "Tvé údery jsou voda!" }
	SUB "HM1BLK_2" { TEXT "Nemyslis, e mi mùeš ublíiti!" }
	SUB "HM1BLK_3" { TEXT "Nemùeš zvítìziti!" }
	SUB "HM1BLKW1" { TEXT "Zloduch je pomalı, ha ha!" }
	SUB "HM1BOD_1" { TEXT "Probuï se! Vrada! Vrah!" }
	SUB "HM1BOD_2" { TEXT "A vìøící promluvili i øekli, 'Hle, ezlem Pravosti byla ukována spravedlnost.'" }
	SUB "HM1BOD_3" { TEXT "U Stavitele, ke mnì! Jeden z našich zlomen byl, jeho ivot vylit!" }
}
{
	TYPE "convo"
	DESCR "Kladiváø"
	SUB "HM1C0311" { TEXT "Jest nám poznamenáno: Fellahdeeni jsou kacíøi a rozpadnou se jako staré døíví." }
	SUB "HM1C0312" { TEXT "Zlodìji nemaj úctu praádnou. Boství - i falešné boství - je jako bláto pod jejich nohama. Nepøejí si, aby to byla hlína, kterou bude tvarovat Stavitelova ruka." }
	SUB "HM1C0313" { TEXT "Kdepak, naše hradby jsou tesány z nejtuších kamenù, naše brány jsou kovány z plného eleza. Kadı, kdo proti síle jejich 'postaví sílu svou, rozbije úsilím vlastním, jako ovoce padající ze stromu rozbije se o skálu dolù.'" }
	SUB "HM1C0314" { TEXT "Stavitel klade pøed tebe vızvy jako schody z tesaného kamene do vìe ivota tvého. Kdy snaíš se k tìmto vızvám pøiloiti, abys zdolal pıchu svou, zaneøádíš plán schodištì a vneseš do nìj trhliny a slabiny, jimi mùe Šejdíø vstoupiti i pøivoditi zánik tvùj!" }
	SUB "HM1C0321" { TEXT "Radìji k upevnìní obrany naší." }
    SUB "HM1C0322" { TEXT "Nikoli, to oni nejsou, kdo rısují stavbu bitvy. Oni pouze prosazují vùli Baronovu a Baron se rozhodl útok neprosazovat." }
	SUB "HM1C0323" { TEXT "Nerozum. Myslíš, e baron chce Blackbrook dobıti?" }
	SUB "HM1C0324" { TEXT "Copak myslíš? Válka poskytuje baronovi krizi, pøed kterou se mùe postaviti, a pøináší mu daní spousty, kterıch by se jindy nedoèkal." }
	SUB "HM1C0325" { TEXT "Daah, dìtinskost! To pravda jest. A tak dláto nikdy nemùe znáti vùli ruky, jí slouí, a nemìlo by posuzovat, zda znamení, je udìlá, dobré èi špatné jest. Postaèuje, kdy nástroj ostrı a dobøe opracovanı jest. Jen tak mùe Staviteli slouiti." }
	SUB "HM1C0331" { TEXT "Copak tento hladomor nepøestane nikdy? Obchodníci ze Stonemarketu chtìjí ještì o pìtinu navíc, ne si pøed mìsícem úètovali. Pøesto si myslím, e z prodeje maj zisk malı." }
	SUB "HM1C0332" { TEXT "Sám bych øekl, e to bylo kvùli válce mezi Cyrikem a Bohnem. Bitevní linie se skuteènì rozbíhají a míjejí to, co pøed èasem byly farmy a ranèe." }
	SUB "HM1C0333" { TEXT "Tvé argumenty pøesvìdèivé jsou a prokazují oddanost, ale myslím, e bys mohl mnohé zjednodušiti." }
	SUB "HM1C0334" { TEXT "Hmm...." }
	SUB "HM1C0351" { TEXT "Copak ses nic nenauèil? To jméno ti ústa zneèišuje." }
	SUB "HM1C0352" { TEXT "Nikoli, prosáèku. Copak nevíš, e øíci 'Tafer' znamená vyslovit jméno protivníka poraeného, Šejdíøe? Jest to zkaenost - rouška, která ho uznává bez úmyslu - a umoòuje mu vstup do myšlenek tvıch." }
	SUB "HM1C0353" { TEXT "S nepøítelem se nejlépe bojuje na svìtle, nikoli ve stínu! Nedovol nikomu, aby se pøed tebou takto zastíral, abys sám do stínù nesklouzl a neztratil se tak." }
	SUB "HM1C0601" { TEXT "V pravdì øeèeno, nikdy jsem neslyšel, e by se nìkdo tak choval, jako tento zlodìjùv pìšák, Cutty." }
	SUB "HM1C0603" { TEXT "Chvílemi myslel jsem, e Blok 4 u kvùli svému kašli neusne nikdy. Ale teï se ztišil." }
	SUB "hm1c0701" { TEXT "Proklínám tento prach!" }
	SUB "hm1c0703" { TEXT "Inu, mysleli si, e kamennı prach se usadí rychleji ne døevìnı. Aèkoli ho mnoho nohou nahoru vyvrhlo." }
	SUB "hm1c0705" { TEXT "To pravda jest. A do té doby neštìstí zrcadlem jsou pro naše poehnání." }
	SUB "hm1c0801" { TEXT "Pøemıšlels o tom, kdo by mohl nástupcem našeho pána bıti?" }
	SUB "hm1c0803" { TEXT "Slepı jseš? On starı jest a mistøi Kováøi mezi sebou pøetahují se o pøednost." }
	SUB "hm1c0805" { TEXT "To pravda jest, to pravda...." }
	SUB "hm1c0902" { TEXT "Míníš akci na DeWallovy bandity?" }
	SUB "Hm1c0904" { TEXT "Zlodìji své vlastní zrazují. Teï jako jindy." }
	SUB "hm1c1002" { TEXT "Ten uboák slouí obchodníkùm jen ve vlastní chamtivosti své." }
	SUB "hm1c1004" { TEXT "Stavitelova pravda jest, e lidé bez víry mìknou a jako døevo ztrouchnivìlé padaj." }
	SUB "hm1c1301" { TEXT "Slyšels? Tarius, chtìje ušetøit mìšec svùj, novı nù u Šemenovıch koupil si, u našich kováøù nikoliv." }
	SUB "hm1c1303" { TEXT "Zajisté dost ostudy mìl, kdy mu pøi veèeøi èepel praskla." }
	SUB "hm1c1401" { TEXT "Èasy bıvaly, kdy všechny tyto sínì plné nováèkù byly, kdo snaili se umìní našemu uèiti." }
	SUB "hm1c1403" { TEXT "Avšak ménì bratøe, ménì. Mláde se v této dobì snaí o zlatì a politice uèiti, neli o øemesle poctivém." }
	SUB "hm1c1601" { TEXT "Mistr Kováø Dovetail práci svou na spirálovém soukolí dokonèil!" }
	SUB "hm1c1603" { TEXT "Dle plánu! Tohle novı standard pro navíjecí stroje pøinese." }
	SUB "hm1c1701" { TEXT "Stavitel s tebou." }
	SUB "Hm1c1801" { TEXT "Dobøe i tak." }
	SUB "Hm1c1902" { TEXT "Chválím Stavitele." }
	SUB "Hm1c2302" { TEXT "Dobøe stalo se." }
	SUB "Hm1c2402" { TEXT "Taky tvùj." }
	SUB "Hm1c2501" { TEXT "Øezba tvá pøipravena jest?" }
}
{
	TYPE "bark"
	DESCR "Kladiváø"
	SUB "HM1CHGA2" { TEXT "Teï to máš za mít!" }
	SUB "HM1CHGA3" { TEXT "Mé kladivo oèekává tì!" }
    SUB "HM1CHGW1" { TEXT "Hlídej záda mé!" }
	SUB "HM1CHGW2" { TEXT "Postav se se mnou proti nepøíteli našemu a zvítìzíme zcela jistì!" }
	SUB "HM1CHGW3" { TEXT "Podej mì ruku svou silnou." }
	SUB "HM1DET_1" { TEXT "Štítíš se tedy?" }
	SUB "HM1DET_2" { TEXT "Zbabìlèe!" }
	SUB "HM1DET_3" { TEXT "Nesna se zkáze své zabrániti!" }
	SUB "HM1DETW1" { TEXT "Mùeme poèkat, zlosynu." }
	SUB "HM1DIEC3" { TEXT "Aaaa! Tøíštím se...." }
	SUB "HM1HIT_1" { TEXT "Krev tvá maltu Stavitele tvoøí!" }
	SUB "HM1HIT_2" { TEXT "Cítíš, jak z tebe síla vyprchává!" }
	SUB "HM1HIT_3" { TEXT "Bolest tvá ti lekci dává!" }
	SUB "HM1HIT_4" { TEXT "Cítíš, jak odhodlání tvé hroutí se!" }
	SUB "HM1HITW1" { TEXT "Zlosyn potácí se!" }
	SUB "HM1HITW2" { TEXT "Nech tvùj úder ozvìnou mého jest, bratøe!" }
	SUB "HM1HLO_1" { TEXT "Aaah! Stavitel mi pomùe!" }
	SUB "HM1HLOW1" { TEXT "Chraò mì, bratøe!" }
	SUB "HM1HND_1" { TEXT "Ta chyba tì ivot stát bude!" }
	SUB "HM1HND_2" { TEXT "Hle, stavitelova milost obrní mì!" }
	SUB "HM1HND_3" { TEXT "Chtìls mi tím bolest zpùsobiti?" }
	SUB "HM1LAR_1" { TEXT "Jaká to pohroma tu udeøila?" }
	SUB "HM1LAR_2" { TEXT "Co za zkáza se tu nese?" }
	SUB "HM1LOS_1" { TEXT "Proklínám oèi své chøadnoucí. Kam narušitel podìl se?" }
	SUB "HM1LOS_2" { TEXT "Kam šel?" }
	SUB "HM1LOS_3" { TEXT "Na dlouho mi neunikneš, zlodìji!" }
	SUB "HM1M1001" { TEXT "Co to dìláš? Øekni, kdo jsi? Poèkej chvíli! Špeh, narušitel!" }
}
{
	TYPE "convo"
	DESCR "Kladiváø"
	SUB "hm1m1002" { TEXT "Novici mladej, nemáš nìjakou práci, které by ses vìnovati mohl?" }
	SUB "hm1m1003" { TEXT "Pravidla nedovolují novicùm v kasárnách pobıvati, jak bys mìl dobøe znáti. Odejdi." }
	SUB "hm1m1004" { TEXT "Novici! Potøebuji sluby tvé. Jak nejrychleji dovedeš, pøines svícen, prosím, kterı v jídelnì zùstal." }
	SUB "hm1m1005" { TEXT "Á, novici. Jen zanech svícen na podlaze u oltáøe. To je dobrı chlapec." }
	SUB "hm1m1006" { TEXT "Co to za nouzi hrozí, e natolik pospícháš? Zpomal, novici." }
	SUB "hm1m1007" { TEXT "Budi zdráv, novici." }
	SUB "hm1m1008" { TEXT "Síla Stavitelova tobì, novici." }
	SUB "HM1M1009" { TEXT "Otevøete bránu!" }
	SUB "HM1M1010" { TEXT "Pøedlo povìøení své, novici." }
	SUB "Hm1m1011" { TEXT "Copak tu dìláš, novici? Poèkej, ty nejsi... Stùj, zlosyne!" }
	SUB "Hm1m1301" { TEXT "Ach, tojs ty, ten mistr zlodìj. Na vysvìtlování málo èasu jest. Šejdíøovy ohavné bestie našeho veleknìze zajaly, a pokud se nám ho získat zpìt ivého nepovede, vše ztraceno bude. Pokusiti o záchranu neodváime se... tvé umìní lsti a zrady postrádame a naši nepøátelé ho jistì zabijí, pokusíme-li se o to troufale. Pøiveï nám ho ivého a mùem promluviti si o tom, jak samotného Šejdíøe poraziti. Nìkde v jeskyních a síních za tímto obloukem dren jest. Nech Stavitel vede kroky tvé." }
	SUB "HM1M1302" { TEXT "Nemarni èas. Pøiveï nám veleknìze zpìt." }
	SUB "HM1M1303" { TEXT "Poèkej! Jdeš špatnì!" }
	SUB "HM1M1304" { TEXT "Chvalme Stavitele! Náš veleknìz stále ije!" }
	SUB "HM1M1305" { TEXT "Ach, to jsi ty, ten mistr zlodìj. Na vysvìtlování málo èasu jest." }
    SUB "HM1M1306" { TEXT "Šejdíøovy ohavné bestie našeho veleknìze zajaly, a pokud se nám ho získat zpìt ivého nepovede, vše ztraceno bude." }
	SUB "HM1M1307" { TEXT "tvé umìní lsti a zrady postrádame a naši nepøátelé ho jistì zabijí, pokusíme-li se o to troufale." }
	SUB "HM1M1308" { TEXT "Vem tento klíè a mapu a jdi. Nech Stavitel vede kroky tvé." }
	SUB "HM1M1309" { TEXT "Také naši nepøátelé drí Stavitelovo dláto, které musíš zpìt získati." }
	SUB "HM1M1310" { TEXT "Zachránils veleknìze našeho, ale nepøinesls nám Dláto. Získej zpìt artefakt náš nejsvìtìjší, jinak ztraceni jsme." }
	SUB "HM1M1311" { TEXT "Dìkujeme ti, es tohoto nezabil." }
	SUB "HM1M1312" { TEXT "Tvé navrácení Dláta je prozøetelné, ale musíme našeho veleknìze míti. Pospìš si!" }
	SUB "HM1M1313" { TEXT "Chvalme Stavitele. Nejenom es nám Dláto Jeho vrátil, ale náš Veleknìz díky úsilí tvému ije stále." }
}
{
	TYPE "bark"
DESCR "Kladiváø"
	SUB "HM1MIS_1" { TEXT "Nìkdo drancuje to, co nepatøí mu." }
	SUB "HM1MIS_2" { TEXT "Zlodìj! Lupiè!" }
	SUB "HM1RBOD1" { TEXT "Ten narušitel je také vrah! Hlídejte si záda!" }
	SUB "HM1RBOD2" { TEXT "Na útìku je vrah! U došlo k jednomu úmrtí!" }
	SUB "HM1RINT1" { TEXT "V budovì je ozbrojenı zlodìj! Vrhni se na nìj, kdybys ho zahlédl!" }
	SUB "HM1RINT2" { TEXT "Zahlédl jsem jednoho, jen mùe bıt uprchlım vìznìm. Buï na pozoru!" }
	SUB "HM1RINT3" { TEXT "Kde jseš ty slídile mezi Stavitelovımi dìtmi?" }
	SUB "HM1RMIS1" { TEXT "Øekni Mistru Kováøi, e okraden byl." }
	SUB "HM1ROTH1" { TEXT "Nìkdo tu byl bezprávnì. Mìjte oèi otevøené!" }
	SUB "HM1ROTH2" { TEXT "Zpozorovals nìèeho? Pøed chvílí tu nìco bylo." }
	SUB "HM1ROTH3" { TEXT "Mám podezøení, e v budovì nìkdo je. Buïte ve støehu." }
	SUB "HM1RUNA1" { TEXT "Ke mì, bratøi moji! Narušitel ohrouje!" }
	SUB "HM1RUNA2" { TEXT "Vemte zbranì a sem!" }
	SUB "HM1RUNA3" { TEXT "Naše strá zkoušena jest! Ke mì!" }
	SUB "HM1SEC_1" { TEXT "Kdo tudy prošel?" }
	SUB "HM1SEC_2" { TEXT "Narušitel pøichází mezi nás!" }
    SUB "HM1SEC_3" { TEXT "Obávejte se narušitele!" }
	SUB "HM1SMA_1" { TEXT "Kdo se to tu potuluje?" }
	SUB "HM1SMA_2" { TEXT "Tento neøád mluví zlem." }
	SUB "HM1TELC1" { TEXT "Ke mì! Za ním!" }
	SUB "HM1TELC2" { TEXT "Tudy! Narušitel uniká!" }
	SUB "HM1TELC3" { TEXT "Narušitel je zde!" }
	SUB "HM1TELR1" { TEXT "Máme tu narušitele! Pospìšte si! Ke mnì!" }
    SUB "HM1TELR2" { TEXT "Narušitel pøichází mezi nás!" }
	SUB "HM1TELR3" { TEXT "Varuj se, toten zlosyn!" }
}
