SUB1
disabled
{
	TYP "bark"
	DESCR "Dìs"
	SUB "Hh1a0mo1" { TEXT "Slova tvá se zabodla jako kopí do myšlenek krvavıch potemnìlıch... myšlenky své jsi si støeil, abys ruce své od vrady uchránil." }
	SUB "Hh1a0mo2" { TEXT "[nesrozumitelné]... základy...[nesrozumitelné]." }
	SUB "Hh1a0mo3" { TEXT "A tak se musíš i ty obrniti proti vábení jejich a prorazit li a lsti jejich. Ohnìm spoutanım k skutkùm tvım musí ivot skonèiti." }
	SUB "Hh1a0wh1" { TEXT "A tak se musíš i ty obrniti proti vábení jejich a prorazit li a lsti jejich. Ohnìm spoutanım k skutkùm tvım musí ivot skonèiti." }
	SUB "Hh1a0wh2" { TEXT "Vìz tedy, e v boji se máš na pozoru míti pøed tìmito boøiteli... I vysvoboï základy z plamenù." }
	SUB "Hh1a0wh3" { TEXT "Slova tvá se zabodla jako kopí do myšlenek krvavıch potemnìlıch... myšlenky své jsi si støeil, abys ruce své od vrady uchránil." }
	SUB "Hh1a1__1" { TEXT "Pod kùí se k nám teï pøidává." }
	SUB "Hh1a1__2" { TEXT "Trpíme dny vìkù olovìnıch hnusnıch bohù." }
	SUB "Hh1a1__3" { TEXT "Kuj a vra se k plamenùm svım." }
	SUB "Hh1a1__4" { TEXT "Plameny kolem tebe, plameny, nic ne plameny spalující tìlo tvé." }
	SUB "Hh1a1__5" { TEXT "Duše tvá nemùe bıt spasena." }
	SUB "Hh1a1__6" { TEXT "Pøidej se k nám, pøidej se k nám, pøidej se k nám hned!" }
	SUB "hh1bak__1" { TEXT "Dr ruce pryè od vrady své." }
	SUB "Hh1m0401" { TEXT "Ten, kdo mi chce srdce ukrást musí nejprve porazit rány mé." }
    SUB "Hha0mo1" { TEXT "Skutky tvé zabodly se jako kopí hluboko do temnoty, je udusila by ve vıhni tvé plameny vrahù..." }
	SUB "Hh1a1__2" { TEXT "Ve snech trpíme bolestí staletí..." } 
} 
