SUB1

{
	TYPE "convo"
	DESCR "Keeper Instructor"
	SUB "ke1m0101" { TEXT "No tak, synku, pokraèuj ve vıcviku. Pokud si pøeješ slyšet instrukce znovu, øekni mi to." }
	SUB "ke1m0102" { TEXT "Nehraješ podle pravidel, mladíku." }
	SUB "ke1m0103" { TEXT "Vítej, mladı Garrette." }
	SUB "ke1m0104" { TEXT "V okolních místnostech tì nauèím rùznım dovednostem, které budeš potøebovat k pøeití. Zùstaò prosím ve vstupní èásti kadé místnosti, zatímco vysvìtlím její úèel. A budeš pøipraven zaèít s vıukou, pokraèuj touto chodbou do první místnosti." }
	SUB "ke1m0105" { TEXT "Musíš se nauèit pohybovat nepozorovanì. Dr se ve stínu... vyhıbej se svìtlu. Indikátor na obrazovce ti ukáe, jak moc jsi vidìt. Sna se dostat na vrchol plošiny, ani by tì nìkdo vidìl." }
	SUB "ke1m0106" { TEXT "Zkus to znovu. Nezapomeò se dret mimo dobøe osvìtlená místa, dokud nedosáhneš plošiny." }
	SUB "ke1m0107" { TEXT "Otevøi tyto dveøe, abys mohl pokraèovat. A se dveøe budou nacházet blízko støedu obrazovky, rozsvítí se, co znamená, e jsou vybrány. Chceš-li manipulovat s vybranımi dveømi a dalšími objekty, 'Pouij' je." }
	SUB "ke1m0108" { TEXT "Dobøe." }
	SUB "ke1m0109" { TEXT "Pokraèuj touto chodbou k dalšímu testu." }
	SUB "ke1m0110" { TEXT "Nyní se musíš nauèit pohybovat tiše." }
	SUB "ke1m0111" { TEXT "Nìkteré povrchy jsou pøi chùzi hlasitìjší ne jiné a rychlı pohyb dìlá vìtší hluk ne pomalı. Poslouchej své vlastní kroky, abys slyšel, jak velkı hluk dìláš. Instruktor bude otoèen zády. Musíš se dostat na vrchol plošiny, ani by tì nìkdo slyšel." }
	SUB "ke1m0112" { TEXT "Zkus to znovu. Nezapomeò chodit po tichém povrchu a pohybovat se pomalu." }
	SUB "ke1m0113" { TEXT "Za tìmito dveømi je chodba, která tì dovede k dalšímu úkolu." }
	SUB "ke1m0114" { TEXT "Nyní si vem zbranì. Chceš-li sebrat pøedmìty, vyber je tak, e je vycentruješ na obrazovce, dokud se nerozsvítí, a pak je 'Pouij'." }
	SUB "ke1m0115" { TEXT "Nyní si vyber zbraò. Zkus si pøipravit meè a pak luk. Vdy je mùeš zase odloit, pokud potøebuješ mít volné ruce." }
	SUB "ke1m0116" { TEXT "Nyní pojïme na nádvoøí, abychom si procvièili støelbu na terè." }
	SUB "ke1m0117" { TEXT "Pøiprav si luk. Zaklesni šíp a podrením tlaèítka 'Útok' natáhni tìtivu. Dbej na to, abys natáhl tìtivu úplnì dozadu, jinak tvùj vıstøel nebude mít plnou sílu. Zamiø, a a budeš pøipraven vystøelit, uvolni útok. Zkus, zda se ti podaøí zasáhnout nìkterı z tìchto cílù." }
	SUB "ke1m0118" { TEXT "Dobrá trefa. Pokud chceš, pokraèuj v tréninku." }
	SUB "ke1m0119" { TEXT "A budeš pøipraven pokraèovat, pøistup k tréninkové figurínì a pøiprav si meè." }
	SUB "ke1m0120" { TEXT "Máchni na cíl tlaèítkem 'Útok'. Rychlım klepnutím provedeš seknutí. Pøesuò špièku meèe vlevo od cíle pro seknutí vlevo a vpravo od cíle pro seknutí vpravo. Podrením tlaèítka 'útok' a jeho uvolnìním provedeš švih nad hlavou. Zkus si oba seky a švih nad hlavou na cvièné figurínì." }
	SUB "ke1m0121" { TEXT "Dobrá práce. Jsi pøipraven na ivého protivníka. Chceš-li trénovat proti svému partnerovi, vstup do dládìného sparingového prostoru." }
	SUB "ke1m0122" { TEXT "Zaútoè na nìj meèem, ne lukem." }
	SUB "ke1m0123" { TEXT "Dobrá práce. Pokud si pøeješ, pokraèuj v sparingu. A skonèíš, opus prostor pro sparing." }
	SUB "ke1m0124" { TEXT "To by pro dnešek staèilo. Prosím, pøejdi ke stolu." }
	SUB "ke1m0125" { TEXT "Chtìl by ses obèerstvit, ne budeme pokraèovat, mladı Garrette?" }
	SUB "ke1m0126" { TEXT "Prosím, posbírej všechny pøedmìty na tomto stole." }
	SUB "ke1m0127" { TEXT "Projdi svùj inventáø a podívej se na pøedmìty, které máš v kapsách. Jakmile je pøedmìt zobrazen, mùeš jej pouít. Pokud si pøeješ, dej si nìco k jídlu a pak mùeš pokraèovat. Další zkouška èeká na druhé stranì kovovıch dveøí." }
	SUB "ke1m0128" { TEXT "Dveøe jsou zamèené, ale klíè ze stolu je otevøe." }
	SUB "ke1m0129" { TEXT "Chceš-li dveøe odemknout, vyber klíè ze svého inventáøe. Vycentruj dveøe na obrazovce, dokud se nerozsvítí, a pak klíè na dveøe 'pouij'." }
	SUB "ke1m0130" { TEXT "Dobøe." }
	SUB "ke1m0131" { TEXT "Nyní se vydej touto chodbou, abys se dostal k dalšímu testu." }
	SUB "ke1m0132" { TEXT "Nyní se nauèíš nové pohybové dovednosti." }
	SUB "ke1m0133" { TEXT "Nejprve vyšplhej po lanì tak, e na nìj skoèíš." }
	SUB "ke1m0134" { TEXT "Pohybuj pohledem nahoru nebo dolù abys šplhal po lanì nahoru nebo dolù. Otáèením zmìníš smìr pohledu. Pokud znovu 'Skoèíš', pustíš se lana. Nyní vyšplhej po lanì a dostaò se na vrchol plošiny." }
	SUB "ke1m0135" { TEXT "Dobrá práce." }
	SUB "ke1m0136" { TEXT "Bì a pøeskoè pøes propast na druhou stranu od potoka." }
	SUB "ke1m0137" { TEXT "Vypadá to, e ses trochu promoèil, chlapèe. Ujisti se, e pøi 'bìhu' 'skáèeš', abys pøekonal tak velkou mezeru. Znovu vyšplhej po lanì a proveï další pokus." }
	SUB "ke1m0138" { TEXT "Dobrı skok." }
	SUB "ke1m0139" { TEXT "Tuto pøekáku snadno zdoláš, pokud víš, jak na to." }
	SUB "ke1m0140" { TEXT "Nejprve se pøibli ke zdi. Poté se 'Skokem' chytni okraje zdi a vytáhni se nahoru." }
	SUB "ke1m0141" { TEXT "Dobrá práce. Jsem velmi potìšen tvım pokrokem. Poslední test pro dnešní den jsi zvládl." }
	SUB "ke1m0142" { TEXT "Pokud chceš, mùeš zùstat a procvièit si šplhání a skákání... nebo plavání, uhıbání, naklánìní èi plazení. A skonèíš, mùeš se vrátit do svıch komnat tak, e projdeš tìmito èervenımi dveømi. Buï zdráv." }
	SUB "ke1m0143" { TEXT "Velmi pùsobivé, chlapèe. Doufám, e svùj talent vyuiješ stejnì rozvánì jako obratnì." }
}
