SUB1

{
	TYPE	"convo"
	DESCR "Mág"
	SUB "mg210401" { TEXT "Mnozí nepøeijí. Musíme se pokusit pøesmìrovat proud." }
	SUB "mg210403" { TEXT "Vyschlá a mrtvá je velká èást Mìsta. Slunce se postaví na odpor a konflikt skonèí v plamenech." }
	SUB "mg210405" { TEXT "Vítr pokroku vdy smìøuje k hrobu." }
	SUB "mg210601" { TEXT "Ach! Proè je to tak, Aroune?" }
	SUB "mg210603" { TEXT "Copak nemají v plicích dech, aby se mì sami zeptali?" }
	SUB "mg210605" { TEXT "Pak ohlaš, e knihovník Verlin skvìle pokroèil s projektem v tajné pracovnì. Øekni jim také, e Verlin nejšikovnìji zaloil Rituál otevøení na správné místo. Øekni jim, e Verlin mistrnì uklidil mnoho knih a e u na to nemusí myslet." }
	SUB "mg210607" { TEXT "Inu, dnes nebo zítra." }
	SUB "mg2a0ch1" { TEXT "Vítr fouká, oheò hoøí. Zemì se tøese, voda teèe." }
	SUB "mg2a0ch2" { TEXT "Budu kráèet po cestì, dokud se nevrátím k Vìènému ohni." }
	SUB "mg2a0ch3" { TEXT "Budu stavìt úkryty pøed Vìtry, cítit nesèetné Vody, vidìt rozlehlou Zemi a hoøet ve Vìènıch Ohních." }
}
{
	TYPE "bark"
	DESCR "Mág"
	SUB "mg2a1__1" { TEXT "Kdo trápí toto místo?" } 
	SUB "mg2a1__2" { TEXT "Nìco je v nepoøádku." }
	SUB "mg2a1__3" { TEXT "Vìtry nejsou v klidu." }
	SUB "mg2a1_w1" { TEXT "Pøíteli, nìco neklidného se dìje." }
	SUB "mg2a1h_1" { TEXT "Vzduchem se rozléhá zvuk." }
	SUB "mg2a1h_2" { TEXT "Slyšel jsem nìjakı zvuk?" }
	SUB "mg2a1hw1" { TEXT "Slyšel jsi to?" }
	SUB "mg2a1hw2" { TEXT "Záhadné zvuky." }
	SUB "mg2a1hw3" { TEXT "Také jsi nìco slyšel?" }
	SUB "mg2a1v_1" { TEXT "Jaká vize mì znepokojuje?" }
	SUB "mg2a1vw1" { TEXT "Svìtlo nám odhaluje stín." }
	SUB "mg2a1vw2" { TEXT "Podívej. Tamhle!" }
	SUB "mg2a2__1" { TEXT "Je tu podivná pøítomnost!" }
	SUB "mg2a2__2" { TEXT "Vše není tak, jak by mìlo bıt." }
	SUB "mg2a2__3" { TEXT "Nebezpeèí ve stínech." }
	SUB "mg2a2h_1" { TEXT "Zvuk vetøelce ruší vzduch!" }
	SUB "mg2a2h_2" { TEXT "Okamitì vyjdi ven, protoe slyším tvou pøítomnost." }
	SUB "mg2a2se1" { TEXT "Stíny odhalují tvou zbabìlost, narušiteli!" }
	SUB "mg2a2se2" { TEXT "Vìènı Oheò tì pøijme zpìt!" }
	SUB "mg2a2se3" { TEXT "Mám vìènost, abych tì našel!" }
	SUB "mg2a2se4" { TEXT "Opus nás, dokud mùeš." }
	SUB "mg2a2v_1" { TEXT "Vidím tì. Nepokoušej se utéct." }
	SUB "mg2a3b_1" { TEXT "Vrátil jsi mého bratra do Vìèného ohnì. Udìlám ti toté!" }
	SUB "mg2a3na1" { TEXT "Varuji tì: neber proti mnì zbranì!" }
	SUB "mg2a3na2" { TEXT "Buï v klidu." }
	SUB "mg2a3na3" { TEXT "Stùj nehybnì jako rybník v zimì." }
	SUB "mg2a3na4" { TEXT "Hıbání pøinese jen smrt!" }
	SUB "mg2a3s_1" { TEXT "Neutíkej!" }
	SUB "mg2a3s_2" { TEXT "Nesna se utéct!" }
	SUB "mg2a3s_3" { TEXT "Nepatøíš sem!" }
	SUB "mg2a3se1" { TEXT "Vidíš v temnotì smrt?" }
	SUB "mg2a3se2" { TEXT "Stíny tì nebudou chránit navdy." }
	SUB "mg2a3se3" { TEXT "Tvùj osud je hurikán, kterému nelze uniknout." }
	SUB "mg2alma1" { TEXT "Tvé srdce se zrychlí s kadım pulsem alarmu!" }
	SUB "mg2alma2" { TEXT "Uslyšíš zvuk své zkázy!" }
    SUB "mg2almw1" { TEXT "Spuste poplach!" }
	SUB "mg2amb_1" { TEXT "Kdo na mì útoèí?" }
	SUB "mg2amb_2" { TEXT "Aaagh! Neviditelnı nepøítel na mì útoèí!" }
	SUB "mg2amb_3" { TEXT "Aaha! Hanebnı útok zezadu!" }
	SUB "mg2ambw1" { TEXT "Kdo útoèí?" }
	SUB "mg2atb_1" { TEXT "Temnota tì dostihne." }
	SUB "mg2atb_2" { TEXT "Poci osten mého hnìvu." }
	SUB "mg2atb_3" { TEXT "Vyzıvám ivly, aby tì zasáhly!" }
	SUB "mg2bak_1" { TEXT "Vítr mì oklamal." }
	SUB "mg2bak_2" { TEXT "Vše je v klidu." }
	SUB "mg2bak_3" { TEXT "Sladké ticho se vrací." }
	SUB "mg2bak_4" { TEXT "Byla to falešná vidina." }
	SUB "mg2bak_5" { TEXT "Nic to nebylo." }
	SUB "mg2bod_1" { TEXT "Byl jsi zkøiven, ale Vìènı oheò oèistí všechno zlo!" }
	SUB "mg2bod_2" { TEXT "A je tvá pøíští cesta radostnìjší ne tato." }
	SUB "mg2chga1" { TEXT "Síla ivlù na tebe dopadne!" }
	SUB "mg2chga2" { TEXT "Ukradnu ti dech, zlodìji!" }
	SUB "mg2chgw1" { TEXT "Tento narušitel nás nezastaví!" }
	SUB "mg2chgw2" { TEXT "Ten falešnı se nesmí uèit našim zpùsobùm." }
	SUB "mg2det_1" { TEXT "Nevyhnutelnému neunikneš." }
	SUB "mg2hit_1" { TEXT "Tvùj konec se blíí!" }
	SUB "mg2hit_2" { TEXT "Pøiprav se na smrt, narušiteli!" }
	SUB "mg2hitw1" { TEXT "Zanedlouho nám u nebude køíit cestu!" }
	SUB "mg2hlow1" { TEXT "Uuugh! Padám!" }
	SUB "mg2hnd_1" { TEXT "Jsem bez zranìní, blázne!" }
	SUB "mg2hnd_2" { TEXT "Stojím bez úhony." }
	SUB "mg2lar_1" { TEXT "Pracují zde ruce cizího èlovìka." }
	SUB "mg2lar_2" { TEXT "Narušitel vnesl chaos do našeho Øádu." }
	SUB "mg2los_1" { TEXT "Moná se vrátil do temnoty, ale èas je na mé stranì." }
	SUB "mg2los_2" { TEXT "Vetøelec mi prozatím uniká." }
	SUB "mg2m1603" { TEXT "Roèní období se pohybují rychleji, narušiteli!" }
	SUB "mg2m1604" { TEXT "Udeøil jako skomírající vítr!" }
	SUB "mg2m1609" { TEXT "Uaaah! Zemì mì ochrání!" }
	SUB "mg2mis_1" { TEXT "Tohle není tam, kde by to mìlo bıt." }
	SUB "mg2mis_2" { TEXT "Zlodìjina!" }
	SUB "mg2rbod1" { TEXT "Náš bratr se vrátil do Vìèného Ohnì." }
	SUB "mg2rbod2" { TEXT "Kráèí po Poslední Stezce." }
    SUB "mg2rint1" { TEXT "Vyslídil jsem útoèníka." }
	SUB "mg2rint2" { TEXT "Náš nevítanı host se mi zjevil." }
	SUB "mg2rmis1" { TEXT "Zlodìj je v našem domì." }
	SUB "mg2rmis2" { TEXT "Nìkdo to ukradl!" }
	SUB "mg2rmis3" { TEXT "Tohle se ztratilo." }
	SUB "mg2roth1" { TEXT "Chodí mezi námi nìkdo, kdo sem nepatøí." }
	SUB "mg2roth2" { TEXT "Vetøelec obchází naše vìe!" }
	SUB "mg2runa1" { TEXT "Vrátím se s ostatními, lumpe!" }
	SUB "mg2runa2" { TEXT "Ke mnì! Pøišel narušitel!" }
	SUB "mg2sec_1" { TEXT "Naše svatynì je napadena!" }
	SUB "mg2sec_2" { TEXT "Je tu cizinec!" }
	SUB "mg2sma_1" { TEXT "Rovnováha byla narušena." }
	SUB "mg2sma_2" { TEXT "Je zde disharmonie." }
	SUB "mg2telc1" { TEXT "Tady je.... Narušitel je odhalen." }
	SUB "mg2telc2" { TEXT "Falešnı! Je tady!" }
	SUB "mg2telc3" { TEXT "Našel jsem ho!" }
	SUB "mg2telc4" { TEXT "Pospìšte si, pøátelé mágové! Zlodìj je tady!" }
	SUB "mg2telr1" { TEXT "Vetøelec vstoupil do svìtla." }
	SUB "mg2telr2" { TEXT "Pøidejte se ke mnì proti tomuto cizákovi!" }
	SUB "mg2telr3" { TEXT "Vidím zdroj disharmonie!" } 
}
