SUB1

{
	TYPE "convo"
	DESCR "Bratr Murus"
	SUB "MURA0MU1" { TEXT "Hmm.... Proè si nikdy nemùu vzpomenout, kde jsem nechal vìci?" }
	SUB "MURA0MU2" { TEXT "Tady je ale nepoøádek! Proè to tady zasvìcenci neudrují v èistotì?" }
	SUB "MURA0MU3" { TEXT "Hmm.... Zajímalo by mì, co má ten lupiè za lubem." }
	SUB "MURA0MU4" { TEXT "Obèas mám obavy, e u jsem tu tak dlouho uvìznìn, a je tìké jasnì myslet." }
	SUB "MURA0MU5" { TEXT "Pán Stavitel mùe bıt pyšnı na naši slavnou katedrálu." }
	SUB "MURA0MU6" { TEXT "Lidé v celém mìstì si váí Øádu kladiva." }
	SUB "MURBAD" { TEXT "Ale ne! Svatı symbol, kterı máš, nebyl poehnán. Musíš najít zpùsob, jak mu udìlit Stavitelovo poehnání. A to udìláš, vra se sem." }
	SUB "MURBOOK1" { TEXT "Zpropadenì, zdá se, e jsem ztratil svou modlitební knihu. Novici, prosím, dojdi mi pro ni. Jmenuje se 'Modlitba posvìcení'. Nemám ponìtí, kde jsem ji naposledy èetl." }
	SUB "MURBOOK2" { TEXT "U jsi našel 'Modlitbu posvìcení'? Hledal jsem ji v této èásti, ale nenašel jsem ji. Zkus hledat nìkde jinde." }
	SUB "MURBOOK3" { TEXT "Kdo by si tenkrát pomyslel, e taková nechutná postava, jako jsi ty, mùe bıt mou spásou? Dìkuji ti, e jsi pro mì tu knihu sehnal." }
	SUB "MURBUR" { TEXT "Akolite, zachránils mì pøed neklidem vìènım, ale potøebuji, abys i pøátelùm ze ivota mım pomohl . Pøipravil jsem pro nì místa posledního odpoèinku, ale potøebuji, abys tìla jejich do hrobù uloil." }	
	SUB "MURCAND1" { TEXT "Potøebuji najít svíèku, kterou jsem ještì zaiva pouíval. Naposledy si pamatuji, e jsem svíèku pouil v noci smrti své. Byl jsem na pracovním dvoøe, kde je studna. Mé osobní vìci byly schované, ale myslím, e svíèka je stále tam vzadu." }
	SUB "MURCAND2" { TEXT "Prosím, dojdi pro mou svíèku. Nìkde poblí studny jest." }
	SUB "MURCAND3" { TEXT "Ano, to je ta svíèka, kterou jsem vidìl onou noc, kdy zemøel jsem. Pro naše potøeby bude staèiti." }
	SUB "MURDEAL" { TEXT "Aha, náš nejnovìjší akolyta! Zdá se, e dostal ses do potíí nìjakıch, hmm? A ze zezøení tvého, bych øekl, e na problémy zvyklı jsi. No, mohu ti pomoci z tohoto opuštìného místa uniknouti, pokud mi s nìèím pomùeš." }
	SUB "MURFIN" { TEXT "Velmi pomohls mi, pøíteli, i já ti dluím mnohı dík. Rád bych ti dal klíè od klášterní brány, ale ten dávno ztracen jest. Vezmi radìji tento klíè. Otevírá zbrojnici na pùdì. Tam nahoøe je nìco, co se bude mazanému èlovìku, jako jsi ty, hoditi. Teï si jdu odpoèinout. Ještì jednou dìkuji ti." }
	SUB "MURGRAV" { TEXT "Vidím, e všechny pøedmìty máš, co potøebujeme k provedení rituálu posvìcení. Sejdeme se u mého hrobu na høbitovì." }
	SUB "MURHAU1" { TEXT "Nyní tì musím poádat o poslední vìc: Tito pøízrakové, je obıvají tìla mıch bratøí - všichni musí bıt zlikvidováni." }
	SUB "MURHAU2" { TEXT "Zabij všechny pøízraky Kladiva a vra se sem pro svou odmìnu." }
	SUB "MURINT" { TEXT "Vítej v majestátní a velkolepé Kladiváøské katedrále. Jak pøíjemné je pøivítat nové zasvìcence do našich øad. Jsem bratr Murus a budu tvım duchovním prùvodcem. Vidím, e jsi z cesty unavenı, a tak tì nechám bıt. Kdybys však potøeboval mou pomoc, najdeš mì dole v klášteøe." }
	SUB "MURMART" { TEXT "Prosím, pohøbi bratra Martella. Zemøel na pùdì katedrály." }
	SUB "MURREN" { TEXT "Akolyto, zachránil jsi mì pøed neklidem vìènım. Potøebuji však, abys pomohl i pøátelùm ze ivota mım. Pøipravil jsem jim místa posledního odpoèinku, ale potøebuji, abys tìla jejich uloil do hrobù. První bratr Renault jest. Zemøel ve sklepení katedrály. Prosím, dojdi pro tìlo jeho a ulo ho do hrobu." }
	SUB "MURREN1" { TEXT "První je bratr Renault. Zemøel ve sklepì katedrály. Prosím, dojdi pro tìlo jeho a ulo ho do hrobu." }
	SUB "MURREN2" { TEXT "Prosím, jdi pro tìlo bratra Renaulta a ulo ho do hrobu jeho." }
	SUB "MURRIT1" { TEXT "Zaènìme, pøíteli. Zakıvej rùencem nad náhrobkem mım." }
	SUB "MURRIT2" { TEXT "Nyní polo svíèku na náhrobek mùj." }
	SUB "MURRIT3" { TEXT "Pøeèti modlitbu posvìcení." }
	SUB "MURRIT4" { TEXT "Dotkni se náhrobku mého symbolem svatım." }
	SUB "MURRIT5" { TEXT "Koneènì! Modlitby mé vyslyšeny byly. Duše moje koneènì svobodná jest." }
	SUB "MURROS1" { TEXT "Protoe jsi sem oèividnì pøišel... shánìt vìci, mùeš zaèít tím, e mi nìjaké vìci seeneš. Všichni bratøi mají rùence, take ty také nìjaké potøebuješ. Mùeš si pùjèit mùj! Myslím, e jsem jej nechal v pokoji svém. Vzpomínám si, e bylo opravdu hezké dívat se na fontánu v zahradì....Buï tedy hodnı hoch a pøines mi rùenec mùj." }
	SUB "MURROS2" { TEXT "U našels mé korálky rùencové, akolyto záludnı? Nejsou tady. Musí bıt nìkde jinde na tomto krásném, posvátném místì." }
	SUB "MURROS3" { TEXT "Aha! Bájeènı zlodìj jseš. Našels rùenec mùj. Mám pro tebe i další vìci k uèinìní." }
	SUB "MURSYM1" { TEXT "Potøebuji, abys získal svatı symbol. Obávám se, e toto místo u není tak svaté jako kdysi, take bys mohl mít problém nìjakı najít. Vdycky si ho ale mùeš vyrobit sám v továrnì. Dìláme to poøád a chválíme Stavitele za jeho díla." }
	SUB "MURSYM2" { TEXT "Poøád se poohlííš po symbolu svatém? Moná u ádnı nenajdeš. Proè nejdeš do továrny a nevyrobíš si ho sám?" }
	SUB "MURSYM3" { TEXT "Vıbornì. S tímto svatım symbolem jsi skuteènım novicem Øádu." } 
}