SUB1

{
	TYPE	"convo"
	DESCR	"Mág"
	SUB "mg110400" { TEXT "Je to pravda, e se vrátil. Musíme bıt pøipraveni. Èekají nás drsné vody." }
	SUB "mg110402" { TEXT "A se snaíme sebevíc získat talismany, Proroctví je oceán, kterı se vrací ke bøehu. Jen málo mùeme udìlat, abychom tomu zabránili; pouze se pøipravit na jeho pøíchod." }
	SUB "mg110404" { TEXT "Tak u to chodí. Civilizace shoøí v zemi, aby mohla dát ivot dalším." }
	SUB "mg110406" { TEXT "Brzy, mladı uèedníku, pochopíš, v èem tkví pravda." }
	SUB "mg110600" { TEXT "Knihovníku, poèkej! Jsem rád, e se naše cesty dnes zkøíily." }
	SUB "mg110602" { TEXT "Ti z Vnitøního kruhu mì povìøili menším úkolem: zjistit tvùj postup v knihovnì." }
	SUB "mg110604" { TEXT "Dıchat by se dalo na desítky mágù, jak jistì víš, ale ti jsou v poslední dobì zaneprázdnìni jinımi záleitostmi." }
	SUB "mg110606" { TEXT "Jsem ohromen! Tohle všechno jsi dnes udìlal?" }
	SUB "mg1a0ch1" { TEXT "Vítr vane, oheò hoøí. Voda teèe, zemì se tøese." }
	SUB "mg1a0ch2" { TEXT "Budu kráèet po cestì a do svého návratu do Vìèného ohnì." }
	SUB "mg1a0ch3" { TEXT "Budu stavìt úkryty pøed Vìtry, cítit nesèetné Vody, vidìt rozlehlou Zemi a hoøet ve Vìènıch Ohních." }
}

{
	TYPE "bark" 
	DESCR "mág"
	SUB "mg1a1__1" { TEXT "Vše není v klidu." }
	SUB "mg1a1__2" { TEXT "Je tu nìjaké vyrušení." }
	SUB "mg1a1__3" { TEXT "Záhada se pøedstavuje." }
	SUB "mg1a1_w1" { TEXT "Tady, pøíteli! Vyrušení." }
	SUB "mg1a1h_1" { TEXT "Vzduch... ke mnì promlouvá." }
	SUB "mg1a1h_2" { TEXT "Hmm. Zvuky." }
	SUB "mg1a1hw1" { TEXT "Slyšíš to?" }
	SUB "mg1a1hw2" { TEXT "Záhadné zvuky." }
	SUB "mg1a1v_1" { TEXT "Je tohle vidìní?" }
	SUB "mg1a1vw1" { TEXT "Zjevuje nám to svìtlo nìco?" }
	SUB "mg1a1vw2" { TEXT "Je to tam?" }
	SUB "mg1a2__1" { TEXT "Je zde falešná pøítomnost." }
	SUB "mg1a2__2" { TEXT "Co je to za problém?" }
	SUB "mg1a2__3" { TEXT "Stíny skrıvají hrozbu." }
	SUB "mg1a2h_1" { TEXT "Vzduch varuje pøed narušitelem." }
	SUB "mg1a2h_2" { TEXT "Zrazuješ se! Okamitì vyjdi ven!" }
	SUB "mg1a2se1" { TEXT "Skrıvat se ve stínu znamená odhalovat svùj strach, narušiteli." }
	SUB "mg1a2se2" { TEXT "Pøed nevyhnutelnım se neschováš." }
	SUB "mg1a2v_1" { TEXT "Vidìl jsem tì! Nepokoušej se utéct." }
	SUB "mg1a3b_1" { TEXT "Krev mého bratra potøísnila tvé ruce. Teï tvá krev potøísní mou!" }
	SUB "mg1a3na1" { TEXT "Neberte proti mnì zbranì, varuji vás!" }
	SUB "mg1a3na2" { TEXT "Buï v klidu." }
	SUB "mg1a3na3" { TEXT "Útokem nic nezískáš, èlovìèe!" }
	SUB "mg1a3na4" { TEXT "Bylo by moudré se vzdát." }
	SUB "mg1a3s_1" { TEXT "Neutíkej!" }
	SUB "mg1a3s_2" { TEXT "Nepokoušej se utéct!" }
	SUB "mg1a3s_3" { TEXT "Nepatøíš sem!" }
	SUB "mg1a3se1" { TEXT "Uteè, dokud mùeš! Pøejeme si zùstat sami." }
	SUB "mg1a3se2" { TEXT "Temnota tì nebude dlouho chránit." }
	SUB "mg1a3se3" { TEXT "Pøed svım osudem neuteèeš!" }
	SUB "mg1alma1" { TEXT "Tento poplach je tvùj smrtící úder!" }
	SUB "mg1almw1" { TEXT "Upozorni ostatní, pøíteli mágu!" }
	SUB "mg1amb_1" { TEXT "Cítím bodnutí z temnoty!" }
	SUB "mg1amb_2" { TEXT "Nemysli si, e jsi v bezpeèí pøed naším hnìvem!" }
	SUB "mg1ambw1" { TEXT "Rozlévá se ze mì voda mého ivota." }
	SUB "mg1atb_1" { TEXT "Tvá mrtvola bude ivit zemi!" }
	SUB "mg1atb_2" { TEXT "Vra se do Vìèného ohnì, vetøelèe!" }
	SUB "mg1atb_3" { TEXT "A si tì vezme temnota!" }
	SUB "mg1bak_1" { TEXT "Vítr si pohrává s mımi smysly." }
	SUB "mg1bak_2" { TEXT "Vše je v klidu." }
	SUB "mg1bak_3" { TEXT "Sladké ticho se navrací." }
	SUB "mg1bak_4" { TEXT "Byla to falešná vidina." }
	SUB "mg1bak_5" { TEXT "Hmm. Nic." }
	SUB "mg1bak_6" { TEXT "Není tu ádná líce." }
	SUB "mg1bod_1" { TEXT "A tì na tvé cestì provází moudrost, padlı." }
	SUB "mg1chga1" { TEXT "Obrátim tì v popel, tuláku!" }
	SUB "mg1chga2" { TEXT "Uvidím tì krvácet, zlodìji!" }
	SUB "mg1chgw1" { TEXT "Musíme si podmanit tohoto vetøelce!" }
	SUB "mg1chgw2" { TEXT "Pošleme tì na další cestu, falešnı!" }
	SUB "mg1diec2" { TEXT "Neee!" }
	SUB "mg1hit_1" { TEXT "Tvé utrpení brzy skonèí." }
	SUB "mg1hit_2" { TEXT "Ha ha-ha! Neboj se své smrti!" }
	SUB "mg1hitw1" { TEXT "Spoleènì udeøte na nepøítele!" }
	SUB "mg1hlow1" { TEXT "Aaaagh! Já slábnu!" }
	SUB "mg1hnd_1" { TEXT "Nemùeš zmìnit mùj osud, zlodìji!" }
	SUB "mg1lar_1" { TEXT "Velké znamení konfliktu." }
	SUB "mg1lar_2" { TEXT "Tohle není dílo mágù!" }
	SUB "mg1los_1" { TEXT "Vrátil se do stínù." }
	SUB "mg1los_2" { TEXT "Nepodaøilo se mi najít narušitele." }
	SUB "mg1m1601" { TEXT "Odpor je marnı." }
	SUB "mg1m1602" { TEXT "Nevyhnutelnému neunikneš!" }
	SUB "mg1m1606" { TEXT "Jeho vìtry vanou rychle." }
	SUB "mg1mis_1" { TEXT "Vzal nám náš majetek a klid naší mysli." }
	SUB "mg1mis_2" { TEXT "Nìco nám chybí." }
	SUB "mg1rbod1" { TEXT "Další se vrátil do Vìèného ohnì." } 
	SUB "mg1rbod2" { TEXT "Ztratili jsme bratra!" }
	SUB "mg1rint1" { TEXT "Vidìl jsem narušitele." }
	SUB "mg1rint2" { TEXT "Zlodìj èíhá ve tmì. Vidìl jsem ho." }
	SUB "mg1rmis1" { TEXT "Kam zmizel?" }
	SUB "mg1rmis2" { TEXT "Byli jsme okradeni!" }
	SUB "mg1rmis3" { TEXT "Nìkdo nám vzal náš majetek!" }
	SUB "mg1roth1" { TEXT "Chodí mezi námi nìkdo, kdo sem nepatøí." }
	SUB "mg1roth2" { TEXT "Ve vìích je narušitel!" }
	SUB "mg1runa1" { TEXT "Vrátím se ve vìtším poètu, narušiteli!" }
	SUB "mg1runa2" { TEXT "Mágové, spojte se proti této hrozbì!" }
	SUB "mg1sec_1" { TEXT "Naše svatynì je napadena!" }
	SUB "mg1sec_2" { TEXT "Hradby byly prolomeny!" }
	SUB "mg1sma_1" { TEXT "Rovnováha je zde nerovnomìrná." }
	SUB "mg1sma_2" { TEXT "Vidím disharmonii." }
	SUB "mg1telc1" { TEXT "Narušitel je odhalen!" }
	SUB "mg1telc2" { TEXT "Mé pátrání skonèilo! Vidìl jsem vetøelce." }
	SUB "mg1telc3" { TEXT "Zlodìj vyšel na svìtlo." }
	SUB "mg1telr1" { TEXT "Našel jsem mezi námi vetøelce." }
	SUB "mg1telr2" { TEXT "Shromádìte se, mágové, a ukonèete tuto hrozbu!" }
	SUB "mg1telr3" { TEXT "Návštìvník ohrouje náš mír!" }
}