SUB1

{
	TYPE "convo"
	DESCR "Zpìvaèka"
	SUB "op212400" { TEXT "'No poèkej! Kdo to, co ho zøím? Kdo se opovauje kácet døíví z mého panství?'" }
	SUB "op212402" { TEXT "'No poèkej! Kdo to, co ho zøím? Kdo se opovauje kácet..." }
	SUB "op212404" { TEXT "Mám lepší nápad! Co kdybys zítra veèer zazpíval roli 'lesní princezny Conandry' ty? A kdy u sme u toho, proè si nenajdeš jinou hlavní protagonistku?" }
	SUB "op212406" { TEXT "Fajn! Netalentovanı taferskı troglodyte!" }
	SUB "op212501" { TEXT "Ironie, protoe jsem tvé umìní vdycky povaovala za mrhání." }
	SUB "op212503" { TEXT "Nemùu uvìøit, e opera stále prodìlává. Za to mùou všichni ti lidé z niších vrstev, kteøí pracují na pokladnì a podobnì. Kradou všechno, co jim pøijde pod ruku! Valerie by je mìla všechny vyhodit!" }
	SUB "op212505" { TEXT "Taføe!" }
	SUB "op212601" { TEXT "Nemohu s tebou nesouhlasit! Tahle opera je spíš parodií ne svìdectvím. Jediné, co zmohlo mé ubohé uši, byla ta pøíšerná hudba, kterou napsal Cribs!" }
	SUB "op212603" { TEXT "Tak to vùbec není! Od té doby, co Valerie pøevzala vládu, musíme snášet tohohle pana Cribse a jeho zvrácené operetky s liánami a mièudami místo padouchù - co je to za naprostı nesmysl! Jak to mùeš vystát?" }
	SUB "op212700" { TEXT "Mohu si vzít váš pláš, pane? Poèkejte chvíli.... Pomoc!	Zlodìj!" }
	SUB "op2a0si5" { TEXT "Sysli nesli sysla v sesli. Sesle praskla: Sysle, slez! Sysli nesli sysla... Ach, boe mùj!" }
}
{
	TYPE "bark"
	DESCR "Zpìvaèka"
	SUB "op2a1__1" { TEXT "J-je tam nìkdo?" }
	SUB "op2a1__2" { TEXT "Co to bylo?" }
	SUB "op2a1__3" { TEXT "Ha?" }
	SUB "op2a1v_1" { TEXT "Hmm? Myslela jsem, e jsem nìco vidím." }
	SUB "op2a2__1" { TEXT "Co se to k èertu dìje?" }
	SUB "op2a2__2" { TEXT "Kdo je tam?" }
	SUB "op2a3s_1" { TEXT "Aaah! Vetøelec!" }
	SUB "op2a3s_2" { TEXT "Stráe!" }
	SUB "op2alma1" { TEXT "Spuste poplach!" }
	SUB "op2bak_1" { TEXT "Krysy tady vystupují víc ne my." }
	SUB "op2bak_2" { TEXT "Asi to nic nebylo." }
	SUB "op2bak_3" { TEXT "Tyto sály musí mluvit z minulosti." }
	SUB "op2bod_1" { TEXT "Dobrı boe! Mrtvola!" }
	SUB "op2bod_2" { TEXT "Uuugh! Smrákova práce! Stráe!" }
	SUB "op2hlow1" { TEXT "Uh! Pomozte mi!" }
	SUB "op2hlow2" { TEXT "Ooo! Je v domì doktor?" }
	SUB "op2lar_1" { TEXT "To je ale nepoøádek! Stráe!" }
	SUB "op2mis_1" { TEXT "Co je to za loupe? Stráe!" }
	SUB "op2rbod1" { TEXT "Øíkám vám, e je mrtvı! Krev byla na podlaze ještì èerstvá!" }
	SUB "op2rint1" { TEXT "Zahlédla jsem zloèince!" }
	SUB "op2rmis1" { TEXT "Ukraden, øíkám vám! Nìkde je zlodìj!" }
	SUB "op2roth1" { TEXT "V sálech opery èíhá nìkdo, kdo tam nemá co dìlat." }
	SUB "op2runa1" { TEXT "Stráe... nìkde èíhá zlodìj!" }
	SUB "op2runa2" { TEXT "Pomozte nìkdo! Je tu vetøelec!" }
	SUB "op2runa3" { TEXT "Stráe! Zlodìj! Nenechte ho uniknout spravedlnosti!" }
	SUB "op2runa4" { TEXT "Zlodìj! Jdìte po nìm!" }
	SUB "op2sec_1" { TEXT "Pomoc! Je mezi námi lump!" }
	SUB "op2sma_1" { TEXT "Hmm.... Divné." }
	SUB "op2telc1" { TEXT "Zahlédla jsem ho!" }
	SUB "op2telc2" { TEXT "Stráe! Tady je!" } 
}
