SUB1

{
	TYPE "bark"
	DESCR "Ramirez"
	SUB "rmza0mu1" { TEXT "Moná bych mìl poslat nìjaké svalovce za Skupinou Kamene. Myslím, e danì pokryjí z fondu. Potøebuju Joffovi zlomit nohu, nemùe se mi takhle vzepøít." }
	SUB "rmza1__1" { TEXT "Co to bylo?" }
	SUB "rmza1_w1" { TEXT "Co to tam bylo?" }
	SUB "rmza1h_1" { TEXT "Podivné zvuky." }
	SUB "rmza1hw1" { TEXT "Co jsi øíkal?" }
	SUB "rmza1v_1" { TEXT "Hmm.... Pøísahal bych, e jsem nìco vidìl." }
	SUB "rmza1vw1" { TEXT "Vidìl jsi to tam?" }
	SUB "rmza2__1" { TEXT "Hej! Uka se!" }
	SUB "rmza2h_1" { TEXT "Tak hele, pøestaò tam vzadu èmuchat! Nedovolím, aby tu èíhal nìjakı sluha." }
	SUB "rmza2v_1" { TEXT "Kdo je to tam? Vylez ze stínu, ty!" }
	SUB "rmza3na1" { TEXT "Ááá! Podívej, a u jsi kdokoli, mùu ti udìlat poøádnou nabídku, abys nezpùsobil ádné trable!" }
	SUB "rmza3s_1" { TEXT "Ááá! Kdo jsi a jak ses sem dostal?" }
	SUB "rmzalma1" { TEXT "Nebudeš vypadat tak nadutì, a sem dorazí moje stráe!" }
	SUB "rmzbak_1" { TEXT "Mìlo mì to napadnout. Sem se nic nedostane." }
	SUB "rmzbod_1" { TEXT "Stavitelovo zlato! Vrah! Stráe, stráe!" }
	SUB "rmzchg_1" { TEXT "Tak to jsi ty? Skoncuju s tebou sám, ty zlodìjskı šakale!" }
	SUB "rmzhlow1" { TEXT "Uff, oh! Pomoz mi, ty idiote!" }
	SUB "rmzlar_1" { TEXT "Stráe, okamitì se o to postarejte: hledejte vetøelce!" }
	SUB "rmzlos_1" { TEXT "Sakra. Kam šel?" }
	SUB "rmzmis_1" { TEXT "Kdo to vzal? Postarám se, aby ho pohøbili zaiva!" }
	SUB "rmzruna1" { TEXT "Stráe! Stráe! Tady! Chci tohoto mue mrtvého!" }
	SUB "rmzsec_1" { TEXT "Stráe, v domì je vetøelec! Podívejte se sem!" }
	SUB "rmzsma_1" { TEXT "Hej... Co se tu dìje?" }  
}
