SUB1

{
	TYPE "convo"
    DESCR "Sluebník"
	SUB "sv106300" { TEXT "Udeø mì." }
	SUB "sv106302" { TEXT "Jo, jo, taføe, rozdej mi další karty." }
    SUB "sv106304" { TEXT "A tì Šejdíø najde ve tmì...." }
	SUB "sv106306" { TEXT "Øekl jsem 'Udeø mì'!" }
	SUB "sv1a0mu1" { TEXT "Další noc.... Další dlouhá, osamìlá noc.... Bloudìní kolem...." }
	SUB "sv1a0mu2" { TEXT "Nevadí mi tolik práce, spíš ta samota, já... nìkdy bych si pøál mít nìkoho, s kım bych si mohl popovídat, to vše..." }
	SUB "sv1a0mu3" { TEXT "Další noc.... Dlouhá, osamìlá noc.... Bloudìní kolem.... Ooo, ta zima...." }
}
{
	TYPE "bark"
	DESCR "Sluebník"
	SUB "sv1a1__1" { TEXT "Je tam nìkdo?" }
	SUB "sv1a1__2" { TEXT "Kdo je to?" }
	SUB "sv1a1__3" { TEXT "Kdo je tam? Haló?" }
	SUB "sv1a1h_1" { TEXT "Co to bylo za zvuk?" }
	SUB "sv1a1h_2" { TEXT "Aaa! Kdo udìlal ten rámus?" }
	SUB "sv1a1h_3" { TEXT "Je tam nìkdo?" }
	SUB "sv1a1v_1" { TEXT "Hmm.... Myslel jsem, e nìco vidím." }
	SUB "sv1a1v_2" { TEXT "Co je to tam v tom stínu?" }
	SUB "sv1a1v_3" { TEXT "Co je to?" }
	SUB "sv1a2__1" { TEXT "Co to bylo?" }
	SUB "sv1a2__2" { TEXT "Kdo je tam? Co to bylo?" }
	SUB "sv1a2__3" { TEXT "Hej, kdo to byl?" }
	SUB "sv1a2__4" { TEXT "Je tam nìkdo? Hej!" }
	SUB "sv1a3__1" { TEXT "Uh! Co to bylo?" }
	SUB "sv1a3b_1" { TEXT "Hej! Co se dìje?" }
	SUB "sv1a3s_1" { TEXT "Ah! Kdo jsi?" }
	SUB "sv1a3s_2" { TEXT "Neubliujte mi!" }
	SUB "sv1a3s_3" { TEXT "Já-já jsem neškodnı! Nechte mì na pokoji!" }
	SUB "sv1a3s_4" { TEXT "Pomoc! Pomoc!" }
	SUB "sv1almw1" { TEXT "Bì, vyhlaš poplach! Pospìš si!" }
	SUB "sv1bak_1" { TEXT "Hmm. No jo." }
	SUB "sv1bak_2" { TEXT "Nesnáším krysy." }
	SUB "sv1bak_3" { TEXT "Hmm. Asi to nic nebylo." }
	SUB "sv1bak_4" { TEXT "Haló? Haló? Teï u tam nic není." }
	SUB "sv1bak_5" { TEXT "Ups. Asi to nic nebylo." }
	SUB "sv1bak_6" { TEXT "Nevadí. Nikdo tu není." }
	SUB "sv1bak_7" { TEXT "Omlouvám se, e jsem udìlal rozruch." }
    SUB "sv1bod_1" { TEXT "Á! Tìlo! Pomoc! Pomoc!" }
	SUB "sv1bod_2" { TEXT "Ach ne! Pomoc! Pomoc!" }
	SUB "sv1bod_3" { TEXT "Pomoc! Vrada! Tady!" }
	SUB "sv1bod_4" { TEXT "Vrah! Vrada! Je tady tìlo!" }
}
{
	TYPE "convo"
    DESCR "Sluebník"
	SUB "sv1c0101" { TEXT "Klidné, e?" }
	SUB "sv1c0103" { TEXT "Kde tedy je? Dnes veèer jsem ho nevidìl." }
	SUB "sv1c0202" { TEXT "Sucho pøed dvanácti lety, to bylo skoro tak zlé jako tohle." }
	SUB "sv1c0204" { TEXT "Hmmm! To by se Novému trhu líbilo." }
	SUB "sv1c0301" { TEXT "Nikdy bys nevìøili, co se dnes stalo. Kupoval jsem zeleninu a hospodynì de Perrin se kolem mì protlaèila a øekla prodavaèce, aby jí dala poslední øeøichu." }
	SUB "sv1c0303" { TEXT "To jsem si taky myslel! Jen proto, e pracuješ pro šlechtice, nemáš dùvod se takhle pøetvaøovat." }
	SUB "sv1c0402" { TEXT "Pán je idiot! Dokud neskonèí období nedostatku, tak jich víc nedostaneme." }
	SUB "sv1c0501" { TEXT "Myslím, e zahradní máta to nezvládne. Ani stín nepomáhá." }
	SUB "sv1c0503" { TEXT "Já vím. Jen stále doufám, e sucho brzy skonèí. Studna je u tak hluboko vyèerpaná." }
	SUB "sv1c0602" { TEXT "Jo, poøád to øíkám." }
	SUB "sv1c0604" { TEXT "A co ty vlastnì víš o Baronovıch románcích?" }
	SUB "sv1c0606" { TEXT "Aha! Jako by Felicia vìdìla, jestli to Baron myslí vánì." }
	SUB "sv1c0701" { TEXT "Kdy jsem se dnes ráno vracel z trhu, bylo to hrozné." }
	SUB "sv1c0703" { TEXT "Byl tam velkı dav Kladivounù, krouili kolem nìjakého chlapa jako vlci." }
	SUB "sv1c0705" { TEXT "Ne, utekl jsem! Nechci, aby obrátili zrak ke mnì. Trvalo jim celou vìènost, ne obešli kolem dokola." }
	SUB "sv1c0802" { TEXT "Co se dìje?" }
	SUB "sv1c0804" { TEXT "Je to tìké, já vím." }
	SUB "sv1c0901" { TEXT "Máš nìkdy pocit, e tì nìkdo... sleduje?" }
	SUB "sv1c0903" { TEXT "No, to taky, ale myslím spíš duchy, nebo nìkoho, kdo se skrıvá... a sleduje tì." }
	SUB "sv1c1002" { TEXT "Uzavøené oblasti? Ani náhodou! Slyšel jsem, e tam chodí mrtví." }
	SUB "sv1c1004" { TEXT "Co jsem slyšel, je tam jinı mìsíc. Takovı, kterı si bere všechno svìtlo." }
	SUB "sv1c1006" { TEXT "Ani mne." }
	SUB "sv1c1101" { TEXT "Všechno v poøádku?" }
	SUB "sv1c1201" { TEXT "Jakı máš den?" }
	SUB "sv1c1301" { TEXT "Vidìl jsi tu kuchaøe?" }
	SUB "sv1c1401" { TEXT "Jsi ještì vzhùru?" }
	SUB "sv1c1502" { TEXT "Mìlo by to bıt brzy hotové." }
	SUB "sv1c1602" { TEXT "Aah. Hrnce na guláš, to je moje nejhorší práce!" }
	SUB "sv1c1702" { TEXT "Uvidíme, jestli ti pak zaplatí víc." }
	SUB "sv1c1802" { TEXT "Ne, mùj ne." }
	SUB "sv1c1901" { TEXT "Co se stalo s mladım Brennanem? Vidìla jsem, jak ho odváí vùz, jak kvílí a stávaj vlasy." }
	SUB "sv1c1903" { TEXT "Tam dolù bys mì nedostal ani za nic." }
}
{
	TYPE "bark"
    DESCR "Sluebník"
	SUB "sv1hlow1" { TEXT "Aaa! Pomozte mi!" }
	SUB "sv1lar_1" { TEXT "Co to má všechno znamenat? To není dobré.... Pomoc!" }
	SUB "sv1lar_2" { TEXT "Hej! Pomoc! Podívejte se sem!" }
	SUB "sv1m0201" { TEXT "Zatracená vìc zhasla. Tak to bude asi studená kaše k snídani."
	}	
    SUB "sv1m0501" { TEXT "'Bì si najít práci u Ramireze,' øíká. 'Je bohatı a mocnı,' øíká. To bylo naposledy, co jsem poslouchal enskou!" }
	SUB "sv1m0503" { TEXT "Divnı.... Kam se podìl?" }
	SUB "sv1mis_1" { TEXT "Hej.... Kde je ten...?" }
	SUB "sv1mis_2" { TEXT "Ale ne! Jsme v takovém prùšvihu!" }
	SUB "sv1mis_3" { TEXT "ezlo je pryè! Ach ne!" }
	SUB "sv1rbod1" { TEXT "V budovì je vrah." }
	SUB "sv1rint1" { TEXT "Hej, támhle se potuluje chlap s lukem." }
	SUB "sv1rint2" { TEXT "V budovì je narušitel! Chraòte mì!" }
	SUB "sv1rint3" { TEXT "Pomoc! Pøed chvílí jsem nìkoho vidìl!" }
	SUB "sv1rmis1" { TEXT "Nìkdo ukradl vìci." }
	SUB "sv1rmis2" { TEXT "Oh, ezlo se ztratilo! Pán nás pøipraví o ivot!" }
	SUB "sv1roth1" { TEXT "Mám strach. Myslím, e se pøed chvílí nìco stalo." }
	SUB "sv1roth2" { TEXT "Myslím, e se dìje nìco divného." }
	SUB "sv1run_1" { TEXT "Pomoc! Zachraòte mì! Nìkdo tu je!" }
	SUB "sv1run_2" { TEXT "Tady je nìjakı chlap! Pomozte mi!" }
	SUB "sv1run_3" { TEXT "Pomoc, pomoc! Nenechte ho, aby mì dostal!" }
	SUB "sv1run_4" { TEXT "Pomoc, pomoc!" }
	SUB "sv1run_5" { TEXT "Podívej se tam! Má luk!" }
	SUB "sv1run_6" { TEXT "Rychle! Tady! Zachraò mì!" }
	SUB "sv1sec_1" { TEXT "Vetøelec!" }
	SUB "sv1sec_2" { TEXT "Pomoc! Loupeníci!" }
	SUB "sv1sma_1" { TEXT "Tohle není v poøádku." }
	SUB "sv1sma_2" { TEXT "Oh.... Budeme v prùšvihu, jestli se to neuklidí." }
	SUB "sv1telc1" { TEXT "Pomoc! Pomoc! Nenechte ho, aby mì dostal!" }
	SUB "sv1telc2" { TEXT "Chyte ho nìkdo!" } 
}
