SUB1

{
	TYPE "convo"
	DESCR "Sluebnice"
	SUB "sv206301" { TEXT "Ach, jak jsem hloupá, samozøejmì, e chceš zabodovat na dvacítce! Dvacet osm? Ó, prohrál jsi. Paneèku, jaká je pravdìpodobnost, e se to stane?" }
	SUB "sv206303" { TEXT "Samozøejmì. Tímhle tempem vyhraju všechny tvoje dıška za veèer!" }
	SUB "sv206305" { TEXT "Hmm? To jsem nepochopil." }
}
{
	TYPE "bark"
	DESCR "Sluebnice"
	SUB "sv2a1__1" { TEXT "Ha?" }
	SUB "sv2a1__2" { TEXT "Je tam nìkdo?" }
	SUB "sv2a1__3" { TEXT "Jsi to ty, Kevele?" }
	SUB "sv2a1__4" { TEXT "Co je to?" }
	SUB "sv2a1h_1" { TEXT "Eee! Co je to za zvuk?" }
	SUB "sv2a1h_2" { TEXT "Kdo je tam? Øíkal jsi nìco?" }
	SUB "sv2a1v_1" { TEXT "Kdo to tam byl? Nìco jsem vidìla." }
	SUB "sv2a1v_2" { TEXT "Aaah! Kdo... Je tam nìkdo?" }
	SUB "sv2a2__1" { TEXT "Tohle se mi nelíbí." }
	SUB "sv2a2__2" { TEXT "Pøestaò se se mnou taføit." }
	SUB "sv2a2__3" { TEXT "Co to je? Hej, je tu nìkdo?" }
	SUB "sv2a2__4" { TEXT "Kdo je tam?" }
	SUB "sv2a3b_1" { TEXT "Uugh! Ty... ty jsi ho zabil!" }	
    SUB "sv2a3s_1" { TEXT "Prosím, neubliuj mi!" }
	SUB "sv2a3s_2" { TEXT "Vzdávám se!" }
	SUB "sv2a3s_3" { TEXT "Já-já nemám ádné peníze!" }
	SUB "sv2a3s_4" { TEXT "Pomoc, pomoc! Nìkdo tu je!" }
	SUB "sv2almw1" { TEXT "Oh, zazvoòte na poplach! Zavolejte pomoc!" }
	SUB "sv2bak_1" { TEXT "No dobøe.... Pøíliš mnoho pøedstav." }
	SUB "sv2bak_2" { TEXT "Nevím, co to bylo." }
	SUB "sv2bak_3" { TEXT "Kdo ví, co to bylo." }
	SUB "sv2bak_4" { TEXT "Jsem ráda, e to nic nebylo." }
	SUB "sv2bak_5" { TEXT "No jo.... Promiò... asi to nic nebylo." }
	SUB "sv2bak_6" { TEXT "Nevím, co to bylo.... U je to pryè." }
	SUB "sv2bak_7" { TEXT "Pardon...teï u tu nic není." }
	SUB "sv2bod_1" { TEXT "Uuh! Tolik krve! Uh!" }
	SUB "sv2bod_2" { TEXT "Vrazi! Pomoc, tady!" }
	SUB "sv2bod_3" { TEXT "Tady! Pomoc! On... nìkoho zabil!" }
	SUB "sv2bod_4" { TEXT "Aah! Tady je mrtvı chlap... podívejte!" }
}
{
	TYPE "convo"
	DESCR "Sluebnice"
	SUB "sv2c0102" { TEXT "Uij si to, dokud to jde, pøíteli. 'Jeho Tlustost' se brzy vrátí, aby nám zase znepøíjemnila ivot." }
	SUB "sv2c0104" { TEXT "Zase dole ve sklepì poèítá svou koøist. Doufám, e tam zùstane celou noc." }
	SUB "sv2c0201" { TEXT "Pøísahám, e takhle nízko jsem hladinu øeky ještì nevidìla." }
	SUB "sv2c0203" { TEXT "V Shalebridge se dá skoro pøejít." }
	SUB "sv2c0302" { TEXT "Ta drzost!" }
	SUB "sv2c0304" { TEXT "Pøesnì tak!" }
	SUB "sv2c0401" { TEXT "Kuchaø øíká, e na nìj pán køièí, e veèeøe nejsou dost nóbl." }
	SUB "sv2c0403" { TEXT "Pøesnì tak! Pán si prostì myslí, e by všechno mìlo bıt zase jako za tuènıch let, a o nièem jiném nechce ani slyšet." }
	SUB "sv2c0502" { TEXT "Tak to bys ji mìl co nejdøív vytrhnout. Pánovi se nebude líbit, kdy se kolem bude povalovat spousta hnìdıch rostlin." }
	SUB "sv2c0504" { TEXT "Nemùe to trvat vìènì. A jestli ano, Pán se pøestìhuje do Cyriky a bude po všem." }
	SUB "sv2c0601" { TEXT "Pamatuješ, jak jsi øíkal, e se Baron nikdy neoení?" }
	SUB "sv2c0603" { TEXT "S tou Felicií to myslí vánì." }
	SUB "sv2c0605" { TEXT "Moje sestra! Pracuje pro paní, která šije Feliciiny šaty." }
	SUB "sv2c0702" { TEXT "Vidìla jsem, e ses vrátil pozdì." }
	SUB "sv2c0704" { TEXT "Take jsi zùstal a díval se?" }
	SUB "sv2c0801" { TEXT "Uff..." }
	SUB "sv2c0803" { TEXT "No já... já se jen bojím, e se mùj Jobi u nikdy nevrátí. Je pryè a bojuje s Blackbrookem. Myslela jsem, e to pro nìj bude dobré, nauèí ho to disciplínì, ale teï...." }
	SUB "sv2c0805" { TEXT "Bıt matkou, nejhorší vìc na svìtì, to ti povídám. Nejlepší, v co mùeš doufat, je umøít døív ne tvoje dìti." }
	SUB "sv2c0902" { TEXT "Myslíš pána?" }
	SUB "sv2c0904" { TEXT "Podle mì je to jen domem. Všechny ty stíny tì dostanou." }
	SUB "sv2c1001" { TEXT "Šel jsi nìkdy dolù k... víš... k Barikádám?" }
	SUB "sv2c1003" { TEXT "Slyšela jsem, e ty budovy jsou z kamene zlıch duchù. Pohltili toho, kdo tam il!" }
	SUB "sv2c1005" { TEXT "Tam dole mì nezastihneš." }
	SUB "sv2c1102" { TEXT "Jistì, zatím." }
	SUB "sv2c1202" { TEXT "Nemùu si stìovat." }
	SUB "sv2c1302" { TEXT "Dnes veèer ještì ne." }
	SUB "sv2c1402" { TEXT "Jo, ještì toho mám hodnì na práci." }
	SUB "sv2c1501" { TEXT "Dlouhá noc?" }
	SUB "sv2c1601" { TEXT "U mì nebaví ty zablácené boty." }
	SUB "sv2c1701" { TEXT "Slyšel jsi? Pán øíkal, e odvádím dobrou práci!" }
	SUB "sv2c1801" { TEXT "Ztratil jsi knoflík? Jeden jsem našla na chodbì." }
	SUB "sv2c1902" { TEXT "Jedna z šéfovıch bestií ho chytila ve sklepì a utrhla mu ruku! Má štìstí, e je naivu!" }
}
{
	TYP "bark "
	DESCR "Sluebnice"
	SUB "sv2hlow1" { TEXT "Prosím, ne! Pomoc!" }
	SUB "sv2lar_1" { TEXT "Aah! Podívejte se na tohle! Pomoc!" }
	SUB "sv2lar_2" { TEXT "Ale ne, kdo to udìlal? Pomoc! Pomoc!" }
	SUB "sv2m0201" { TEXT "Zase zima. Nesnáším studené snídanì." }
	SUB "sv2m0501" { TEXT "'Ještì víno', øíká. 'Více vína'. U ho mám dost i s tím jeho vínem." }
	SUB "sv2m0502" { TEXT "Jen si tam sedne a poèítá peníze, to dìlá. Ké by mi dal.... Ten tlustı, zpocenı, upjatı tupec!" }
	SUB "sv2m0503" { TEXT "Mìl by tu bıt. To je divné." }
	SUB "sv2mis_1" { TEXT "Hej! Pomoc, zlodìj!" }
	SUB "sv2mis_2" { TEXT "Kde je?" }
	SUB "sv2mis_3" { TEXT "Kam se podìlo ezlo?" }
	SUB "sv2rbod1" { TEXT "V-vidìli jste tìlo?" }
	SUB "sv2rint1" { TEXT "Právì jsem vidìl narušitele! Je nìkde tady!" }
	SUB "sv2rint2" { TEXT "Nìkdo se tu plíí. Mám strach." }
	SUB "sv2rmis1" { TEXT "Tady nìkde je zlodìj. Ztratily se všechny moné vìci!" }
	SUB "sv2rmis2" { TEXT "Nìkdo vzal ezlo!" }
	SUB "sv2roth1" { TEXT "Nìkdo nìco hledá a my za to dostaneme taf!" }
	SUB "sv2roth2" { TEXT "Celá místnost byla vybílená! Nevidìl jsi nìkoho?" }
	SUB "sv2run_1" { TEXT "Pomoc! Zlodìj! Zlodìj!" }
	SUB "sv2run_2" { TEXT "Je pøímo tady! Pomoc!" }
	SUB "sv2run_3" { TEXT "Vidím ho! Pomoc! Tady!" }
	SUB "sv2run_4" { TEXT "Tady! Má meè!" }
	SUB "sv2run_5" { TEXT "Chyte ho nìkdo!" }
	SUB "sv2run_6" { TEXT "Pomoc, pomoc! Nìkdo tu je!" }
	SUB "sv2sec_1" { TEXT "Nìkdo...nìkdo! Je tu nìjakı zlodìj!" }
	SUB "sv2sec_2" { TEXT "Pomoc! Tady... byl tu narušitel!" }
	SUB "sv2sma_1" { TEXT "Hej, co se to tu dìje?" }
	SUB "sv2sma_2" { TEXT "Co se tu stalo?" }
	SUB "sv2telc1" { TEXT "Je tady! Pomoc!" }
	SUB "sv2telc2" { TEXT "Tady! Má meè!" }
	SUB "sv2telc3" { TEXT "Vidím ho! Pomoc, tady! " } 
}
