SUB1

{
	TYPE "convo"
	DESCR "Zlodìj"
	SUB "th206101" { TEXT "Slyšel jsem. Máme Donala na jiní stranì a Ruebena na severní, jestli se nìco semele, tak nás to zastihne uprostøed." }
	SUB "th206103" { TEXT "Uff. Nikdy jsem nemìl jít do odborù." }
	SUB "th206601" { TEXT "Jo. Jmenuje se Garrett. Ramirez se ho pøed èasem snail naverbovat, ale Garrett ho odmítl. Slyšel jsem, e Ramirez poslal nìjaké uklízeèe, aby se postarali o ten nepoøádek." }
	SUB "th206701" { TEXT "Tu práci jsme nezvládli, e ne?" }
	SUB "th206703" { TEXT "A kdo tedy?" }
	SUB "th206801" { TEXT "Ne, co se mu stalo?" }
	SUB "th206803" { TEXT "To je šílenı!" }
	SUB "th206805" { TEXT "Dobøe, co to bylo?" }
	SUB "th206807" { TEXT "Haha haha! Chceš mi øíct, e tenhle tafer se vloupal do panství lorda Bafforda jen proto, aby ukradl ezlo, které u bylo ukradeno?" }
	SUB "th206809" { TEXT "Proè ale skonèil v Horoštìpu? Myslel jsem, e by ho Bafford prostì pøedal šerifovi." }
	SUB "th206811" { TEXT "Co dostal Bafford?" }
	SUB "th206901" { TEXT "Prı pøišel dost pozdì. Dostal nìco dobrého?" }
	SUB "th206903" { TEXT "Chytli ho?" }
	SUB "th206906" { TEXT "Coe?" }
    SUB "th207105" { TEXT "Dìláš si ze mì tafra?" }
	SUB "th207107" { TEXT "A já tu stojím a poslouchám, jak ti Danno øíká heslo. Myslíš, e by to udìlal, kdybych nebyl z Cechu, nebo si myslíš, e jsem takovı tupec, abych si to heslo nezapamatoval?" }
	SUB "th2a0__1" { TEXT "Jo, jo... to je ono...." }
	SUB "th2a0mu1" { TEXT "Šel jsem do svého pokoje, u tam nic nebylo.... Lidi mi berou vìci...." }
	SUB "th2a0mu2" { TEXT "Aaah, lidi tady, je jim to prostì jedno.... Potøebuju nìjaké peníze...." }
	SUB "th2a0mu3" { TEXT "Uh, mùj hrnek, je pryè.... Nevím, kam se podìl...." }
	SUB "th2a0tc1" { TEXT "Hmmm...." }
}
{
	TYPE "bark"
	DESCR "Zlodìj"
	SUB "th2a1__1" { TEXT "Ha?" }
	SUB "th2a1__2" { TEXT "Co" }
	SUB "th2a1__3" { TEXT "Uh?" }
	SUB "th2a1__4" { TEXT "Hej." }
	SUB "th2a1_w1" { TEXT "Co se dìje?" }
	SUB "th2a1_w2" { TEXT "Co se dìje?" }
	SUB "th2a1h_1" { TEXT "Co jsem to slyšel?" }
	SUB "th2a1h_2" { TEXT "Mmm. Myslel jsem, e jsem nìco slyšel." }
	SUB "th2a1hw1" { TEXT "Ticho!" }
	SUB "th2a1hw2" { TEXT "Hej, slyšíš to?" }
	SUB "th2a1hw3" { TEXT "Hej! Slyšíš ten rámus?" }
	SUB "th2a1hw4" { TEXT "Pšššt!" }
	SUB "th2a1v_1" { TEXT "Myslel jsem, e jsem nìco vidìl." }
	SUB "th2a1v_2" { TEXT "Vidìl jsem to, co si myslím, e jsem vidìl?" }
	SUB "th2a1vw1" { TEXT "Hej! Vidìl jsi to?" }
	SUB "th2a1vw2" { TEXT "Podívej se na to!" }
	SUB "th2a1vw3" { TEXT "Vidìl jsi nìco?" }
	SUB "th2a2__1" { TEXT "Kdo je to?" }
	SUB "th2a2__2" { TEXT "Nìco je špatnì." }
	SUB "th2a2__3" { TEXT "Co se dìje?" }
	SUB "th2a2__4" { TEXT "Nìco je tu divné." }
	SUB "th2a2h_1" { TEXT "Moná kdybys nebyl takovı amatér, nedìlal bys tolik hluku!" }
	SUB "th2a2h_2" { TEXT "Ty jsi ale hluènı!" }
	SUB "th2a2h_3" { TEXT "To jsem slyšel! Zùstaò, kde jsi!" }
	SUB "th2a2se1" { TEXT "To bude švanda, a tì vykucháme, chlapèe!" }
	SUB "th2a2se2" { TEXT "Jen vystrè hlavu ven! Rychle to pro tebe ukonèím!" }
	SUB "th2a2se3" { TEXT "Najdu tì... nakonec." }
	SUB "th2a2v_1" { TEXT "Víš, e tì vidím, e?" }
	SUB "th2a3b_1" { TEXT "To není koøist, kterou neseš!" }
	SUB "th2a3na1" { TEXT "Ani hnout!" }
	SUB "th2a3na2" { TEXT "Uhni a je po tobì!" }
	SUB "th2a3na3" { TEXT "U tì mám, tafre!" }
	SUB "th2a3na4" { TEXT "Zùstaò kde si, Garrette!" }
	SUB "th2a3s_1" { TEXT "Garrett!" }
	SUB "th2a3s_2" { TEXT "Nejsi jeden z nás!" }
	SUB "th2a3s_3" { TEXT "Co tady sakra dìláš?" }
	SUB "th2a3s_4" { TEXT "Hej!" }
	SUB "th2a3se1" { TEXT "A tì najdu, dám si s tebou na èas!" }
	SUB "th2a3se2" { TEXT "Pojï si hrát!" }
	SUB "th2a3se3" { TEXT "Nemùeš se schovávat vìènì!" }
	SUB "th2almw1" { TEXT "Jdi spustit poplach! Postarám se o nìj!" }
	SUB "th2almw2" { TEXT "Poplach, hned!" }
	SUB "th2amb_1" { TEXT "Jsi mizernı støelec!" }
	SUB "th2amb_2" { TEXT "Stejnì tak jsi mohl minout!" }
	SUB "th2ambw1" { TEXT "Ugh! Dostal mì!" }
	SUB "th2ambw2" { TEXT "Pomoc!" }
	SUB "th2atn_1" { TEXT "Sáhni si na mé ostøí, Garrette!" }
	SUB "th2atw_1" { TEXT "Shniješ ve stokách!" }
	SUB "th2atww1" { TEXT "Nemá šanci!" }
	SUB "th2bak_1" { TEXT "Je tu moc zatracenıch krys." }
	SUB "th2bak_2" { TEXT "Uh, asi to nic nebylo." }
	SUB "th2bak_3" { TEXT "Hm.... Teï u je klid." }
	SUB "th2bak_4" { TEXT "Asi to nic nebylo." }
	SUB "th2bkd_1" { TEXT "Rychle, co?" }
	SUB "th2bkd_2" { TEXT "Zablokuj tohle!" }
	SUB "th2bkdw1" { TEXT "Slyšel jsem, e jsi dobrı." }
	SUB "th2blk_1" { TEXT "Jsi strašnì pomalı." }
	SUB "th2blk_2" { TEXT "Mìl by ses nauèit bıt rychlejší, jestli nám chceš konkurovat, Garrette!" }
    SUB "th2blk_3" { TEXT "Musíš bıt rychlejší, Garrette!"    }     
    SUB "th2blkw1" { TEXT "Teï u nejsi takovı tvrïák, co?" }
	SUB "th2bod_1" { TEXT "Je mrtvı!" }
    SUB "th2bod_2" { TEXT "Snad ne další!" }
	SUB "th2chga1" { TEXT "Skoncuju s tebou, Garrette!" }
	SUB "th2chga2" { TEXT "Poznáš, co je to bolest!" }
	SUB "th2chgw1" { TEXT "Pobavíme se s tebou, Garrette!" }
	SUB "th2chgw2" { TEXT "Za ním!" }
	SUB "th2chgw3" { TEXT "Chyte ho!" }
	SUB "th2det_1" { TEXT "Nesnaíš se utéct, e ne?" }
	SUB "th2det_2" { TEXT "Nebuï takovı posera!" }
	SUB "th2detw1" { TEXT "U ho máme!" }
	SUB "th2hit_1" { TEXT "Jak se ti to líbí, Garrette?" }
	SUB "th2hit_2" { TEXT "Bolí to?" }
	SUB "th2hit_3" { TEXT "Máš dost?" }
	SUB "th2hitw1" { TEXT "U tì máme!" }
	SUB "th2hitw2" { TEXT "Je nás mnoho, Garrette!" }
	SUB "th2hlo_4" { TEXT "Agh! Nech toho!" }
	SUB "th2hlow1" { TEXT "Uh! Pomozte mi!" }
	SUB "th2hnd_2" { TEXT "To lechtá!" }
	SUB "th2lar_1" { TEXT "Rozhodnì se nìco dìje." }
	SUB "th2lar_2" { TEXT "Takové problémy nepotøebujeme." }
	SUB "th2los_1" { TEXT "Kam to sakra šel?" }
	SUB "th2los_2" { TEXT "Ztratil jsem ho." }
	SUB "th2los_3" { TEXT "Je pryè." }
	SUB "th2mis_1" { TEXT "Kde sakra je?" }
	SUB "th2mis_2" { TEXT "Kdo to ukradl?!" }
	SUB "th2rbod1" { TEXT "Uh. Byl vyøazen." }
	SUB "th2rbod2" { TEXT "Nìkdo tady zaèíná mít radost ze spouštì. Pozor na to!" }
	SUB "th2rint1" { TEXT "Mìjte oèi otevøené. Jsou tu potíe." }
	SUB "th2rint2" { TEXT "Dìje se nìco divného. Buïte ve støehu." }
	SUB "th2rint3" { TEXT "Jsou tu potíe. Buïte ve støehu." }
	SUB "th2rmis1" { TEXT "Dávejte pozor... nìkdo si vzal vìtší èást skóre, ne mìl." }
	SUB "th2rmis2" { TEXT "Hej, tady nìco chybí!" }
	SUB "th2rmis3" { TEXT "Váza je pryè! Bude to ošklivé!" }
	SUB "th2roth1" { TEXT "Potíe na obzoru.... Buï ve støehu." }
	SUB "th2roth2" { TEXT "Hlavu vzhùru! Máme tu vetøelce!" }
	SUB "th2runa1" { TEXT "Stráe! Tady!" }
	SUB "th2runa2" { TEXT "Stráe, to je Garrett! Chyte ho!" }
	SUB "th2runa3" { TEXT "Máme tu vetøelce!" }
	SUB "th2sec_1" { TEXT "Nìkdo tu èíhá." }
	SUB "th2sec_2" { TEXT "Urèitì tu máme nìjakého potíistu." }
	SUB "th2sma_1" { TEXT "Co je to?" }
	SUB "th2sma_2" { TEXT "Hmm.... Tohle je špatnì." }
	SUB "th2sma_3" { TEXT "Hmm.... Smrdí to jako trable." }
	SUB "th2telc1" { TEXT "Našel jsem ho!" }
	SUB "th2telc2" { TEXT "Tady je!" }
	SUB "th2telc3" { TEXT "Utíká! Za ním!" }
	SUB "th2telr1" { TEXT "Pojï sem! Vetøelec se dostal dovnitø!" }
	SUB "th2telr2" { TEXT "To je Garrett! Pojï sem!" }
	SUB "th2telr3" { TEXT "Zahlédl jsem ho!" }
	SUB "th2telr4" { TEXT "Hej, je tady!" }
	SUB "th2telr5" { TEXT "Tady je!" } 
} 
