SUB1

{
	TYPE "convo"
	DESCR "Zlodìj"
	SUB "th106100" { TEXT "Kdy se partneøi hádají, nikdy to není dobré." }
	SUB "th106102" { TEXT "Jestli se ti dva nepøestanou hádat a nevyøeší to, Rueben pošle své hochy, aby zjistili, kde je Donalùv sejf, a Donal bude hledat Ruebenùv klíè... A víš, e ti, co lámou klouby, si moc nevybírají, komu je zlomí." }
	SUB "th106501" { TEXT "Haah! Chy tohle, Kladivo!" }
	SUB "th106600" { TEXT "Slyšel jsem, e nìjakı nezávislı podnik podniká ve mìstì tìké operace." }
	SUB "th106602" { TEXT "Hádám, e u se o nìj nemusíme bát!" }
	SUB "th106700" { TEXT "Bafford zuøil, kdy se vrátil z vıletu a zjistil, e mu nìkdo ukradl jeho drahocenné ezlo!" }
	SUB "th106702" { TEXT "Ty taføe! Kdybychom na nìkoho z Ramirezovıch lidí vytáhli kšeftit, byla by z toho válka!" }
	SUB "th106704" { TEXT "Pravdìpodobnì Garrett. Ten jedinı je dost mazanı a pošetilı na to, aby takovou práci zvládl." }
	SUB "th106800" { TEXT "Hej, slyšel jsi, co se stalo Gibsonovi?" }
	SUB "th106802" { TEXT "Dostal dvacet let v Horoštìpu! V Baffordovì sídle vzal kšeft za old." }	
	SUB "th106804" { TEXT "Ne tak šílenı, jako to, po èem šel!" }
	SUB "th106806" { TEXT "Jeho støíbrné ezlo!" }
	SUB "th106808" { TEXT "Jop!" } 
	SUB "th106810" { TEXT "Nìjakı Kladiváø jménem Karras nabídl vımìnou za nìj nìco Baffordovi." }
	SUB "th106812" { TEXT "Nevím a je mi to jedno. Stejnì to se mnou nemá nic spoleèného!" }
	SUB "th106900" { TEXT "Slyšel jsi o Sutterovì práci vèera veèer?" }
	SUB "th106902" { TEXT "To by si pøál! Hele, je nahoøe v lonici téhle dámy, všude naprosté ticho, kdy v tom uslyší venku kroky!" }
	SUB "th106904" { TEXT "Hmm! Nic takového. Mohl by se rychle vydrápat odkud pøišel, ale nechce odejít, dokud nesebere aspon nìco." }
	SUB "th106905" { TEXT "Take smete všechno z prádelníku - šperky, svícny a kdovíco ještì - do svého pytle, sejde pùlku schodù, kdy vtom pytel zaène naskakovat!" }
	SUB "th106907" { TEXT "Mìl tam i koèku té paní! Koèka udìlá do pytle díru, všechno vypadne ven, kromì koèky! A ta mu visí v pùlce pae, s drápy na všechny strany!" }
	SUB "th106909" { TEXT "Musel skoèit do øeky, aby se té zatracené vìci zbavil! Zanechal za sebou krvavou stopu a vodu pøes pùlku Mìsta, jen po cestì domù!" }
	SUB "th107101" { TEXT "Reeveovy koule, Suttere! To jsem pøece já!" }
	SUB "th107103" { TEXT "Ruka stínu, noha vzduchu'... Otevøi dveøe, jo?" }
	SUB "th107108" { TEXT "Suttere, ty tvoje vıstøednosti ještì nìjak snesu, ale jestli zaèneš dìlat, jako e já jsem trouba, tak poteèe krev! Hned otevøi ty dveøe!" }
}
{
	TYPE "bark"
	DESCR "Zlodìj"
	SUB "th1a1__1" { TEXT "Huh?" }
	SUB "th1a1__2" { TEXT "Kdo je to?" }
	SUB "th1a1__3" { TEXT "Hmm.... Hádám, e to nic nebylo." }
	SUB "th1a1__4" { TEXT "Hej!" }
	SUB "th1a1_w1" { TEXT "Bylo tam nìco?" }
	SUB "th1a1_w2" { TEXT "Co se dìje?" }
	SUB "th1a1h_1" { TEXT "Co jsem slyšel?" }
	SUB "th1a1h_2" { TEXT "Hmm... To znìlo legraènì." }
	SUB "th1a1hw1" { TEXT "Ticho! Nìco slyším." }
	SUB "th1a1hw2" { TEXT "Hej, slyšíš to?" }
	SUB "th1a1hw3" { TEXT "Pšššt! Tam!" }
	SUB "th1a1hw4" { TEXT "Pšššt! Poslouchej!" }
	SUB "th1a1v_1" { TEXT "Hmm. Myslel jsem, e jsem nìco vidìl." }
	SUB "th1a1v_2" { TEXT "Moje oèi si se mnou asi hrají." }
	SUB "th1a1vw1" { TEXT "Hej, vidìl jsi to?" }
	SUB "th1a1vw2" { TEXT "Podívej! Támhle!" }
	SUB "th1a1vw3" { TEXT "Vidíš to?" }
	SUB "th1a1vw4" { TEXT "Taky jsi to vidìl?" }
	SUB "th1a2__1" { TEXT "Hej.... Kdo je tam?" }
	SUB "th1a2__2" { TEXT "Nìco je tu špatnì." }
	SUB "th1a2__3" { TEXT "Co se to tu sakra dìje?" }
	SUB "th1a2__4" { TEXT "Hmm.... Nìco se dìje." }
	SUB "th1a2h_1" { TEXT "Dìláš hodnì hluku na to, e nechceš bıt vidìn!" }
	SUB "th1a2h_2" { TEXT "Hej, nejsem hluchı, víš! Pojï ven!" }
	SUB "th1a2h_3" { TEXT "To jsem slyšel! Zùstaò, kde jsi." }
	SUB "th1a2se1" { TEXT "Máš pøedstavu, co dìláme s nevítanımi hosty?" }
	SUB "th1a2se2" { TEXT "Doufej, e tì najdu døív ne stráe!" }
	SUB "th1a2se3" { TEXT "Pojï ven a slibuji, e se o tebe rychle postarám!" }
	SUB "th1a2se4" { TEXT "Vím, e jsi tam nìkde!" }
	SUB "th1a2v_1" { TEXT "Yoohoo, vidím tì!" }
	SUB "th1a3b_1" { TEXT "Nìjak se mi nezdá, e by to tam tvùj kamarád pøehnal s pitím!" }
	SUB "th1a3na1" { TEXT "Stát!" }
	SUB "th1a3na2" { TEXT "Ani se nehni!" }
	SUB "th1a3na3" { TEXT "Mám tì pod kontrolou, taføe!" }
	SUB "th1a3na4" { TEXT "Sednout, Garrette!" }
	SUB "th1a3na5" { TEXT "Šéf si myslel, e bys mohl zkusit nìco tak hloupého!" }
	SUB "th1a3s_1" { TEXT "Garrette! Jsi blázen, e jsi sem pøišel!" }
	SUB "th1a3s_2" { TEXT "Ty!" }
	SUB "th1a3s_3" { TEXT "Co tady sakra dìláš?" }
	SUB "th1a3s_4" { TEXT "Hej!" }
	SUB "th1a3s_5" { TEXT "A tì najdu, pošlu na tebe psy!" }
	SUB "th1a3se2" { TEXT "Vylez, vylez, a jsi kdekoli!" }
	SUB "th1a3se3" { TEXT "Ne aby sis myslel, e na tebe zapomenu!" }
	SUB "th1a3se4" { TEXT "Nezùstaneš dlouho schovanı, taføe!" }
	SUB "th1alma1" { TEXT "Spuste poplach!" }
	SUB "th1almw1" { TEXT "Jdi spustit poplach! Já ho zdrím!" }
	SUB "th1almw2" { TEXT "Sakra, to je Garrett! Spuste poplach!" }
	SUB "th1amb_1" { TEXT "Uuh! Zkus mì bodnout do zad, jo?" }
	SUB "th1amb_2" { TEXT "Uuh! Propásl jsi šanci mì sejmout... teï se budeš muset vypoøádat se mnou!" }
	SUB "th1ambw1" { TEXT "Nìkde je tu ostøelovaè!" }
	SUB "th1ambw2" { TEXT "Pomoc! Byl jsem postøelen!" }
}
{ 
	TYPE "convo"
	DESCR "Zlodìj"
	SUB "th1aotk1" { TEXT "Ach boe, je mi jako... Nelíbí se mi... Co to sakra? Nebyla to tam krysa?" }
	SUB "th1aotk2" { TEXT "Ach mùj boe... Co to tady dole sakra smrdí? Kdo si dìlá úkryt v kanálech?" }
	SUB "th1aotk3" { TEXT "U s ním nebudu hrát kostky! Ne pokud nepøijde s penìzi, eano...." }
}
{
	TYPE "bark"
	DESCR "Zlodìj"
	SUB "th1atb_1" { TEXT "Vyhni se tomuto!" }
	SUB "th1atb_2" { TEXT "Udus se tímhle!" }
	SUB "th1atb_3" { TEXT "Chytej!" }
	SUB "th1atn_1" { TEXT "Vykrvácíš!" }
	SUB "th1atn_2" { TEXT "Vem si...tohle!" }
	SUB "th1atw_1" { TEXT "Zemøi!" }
	SUB "th1atww1" { TEXT "Jdeš k zemi!" }
	SUB "th1bak_1" { TEXT "Hmm. Jeden by si myslel, e bych u mìl bıt na krysí zvuky zvyklı." }
	SUB "th1bak_2" { TEXT "Aah, to nic nebylo." }
	SUB "th1bak_3" { TEXT "Teï u je ticho." }
	SUB "th1bak_4" { TEXT "Hmf. Zaèínám bıt pøíliš nervózní." }
	SUB "th1bkd_1" { TEXT "Uh! Jsi rychlı, to se musí nechat!" }
	SUB "th1bkd_2" { TEXT "Jak dlouho si myslíš, e to vydríš?" }
	SUB "th1bkdw1" { TEXT "Je dobrı!" }
	SUB "th1blk_1" { TEXT "Jsi strašnì pomalı!" }
	SUB "th1blk_2" { TEXT "Vypadá to, e potøebuješ trochu cviku, Garrette!" }
	SUB "th1blk_3" { TEXT "Neodpovídá své povìsti, co?" }
	SUB "th1bod_1" { TEXT "Ten chlap je mrtvı!" }
	SUB "th1bod_2" { TEXT "Hej, byl zabit!" }
	SUB "th1bod_3" { TEXT "Máme problémy!" }
	SUB "th1chga1" { TEXT "Oloupím tì o tvoje orgány, taføí chlapèe!" }
	SUB "th1chga2" { TEXT "Jdeš ke dnu!" }
	SUB "th1chgw1" { TEXT "Dáme ti lekci, Garrette!" }
	SUB "th1chgw2" { TEXT "Za ním!" }
	SUB "th1chgw3" { TEXT "Chyte ho!" }
	SUB "th1det_1" { TEXT "Kam si myslíš, e jdeš?" }
	SUB "th1det_2" { TEXT "Bojíš se, co?" }
	SUB "th1detw1" { TEXT "U ho máme!" }
	SUB "th1hit_1" { TEXT "Tvé dny jsou seèteny, Garrette!" }
	SUB "th1hit_2" { TEXT "Nezapomenu ti vykrást hrob, hlupáku!" }
	SUB "th1hit_3" { TEXT "Teï u nejsi tak tvrdı, Garrette!" }
	SUB "th1hitw1" { TEXT "Teï tì máme!" }
	SUB "th1hitw2" { TEXT "Jsi pøeèíslen, Garrette!" }
	SUB "th1hlow1" { TEXT "Uuh! Pomozte mi!" }
	SUB "th1hnd_1" { TEXT "Hah! Ale prosím tì!" }
	SUB "th1hnd_2" { TEXT "Musíš se snait víc!" }
	SUB "th1hnd_3" { TEXT "Hah! Nemùeš udeøit silnìji?" }
	SUB "th1lar_1" { TEXT "Nìco urèitì spadne!" }
	SUB "th1lar_2" { TEXT "O-ou, máme problém!" }
	SUB "th1los_1" { TEXT "Sakra! Kam se podìl?" }
	SUB "th1los_2" { TEXT "Ztratil jsem ho!" }
	SUB "th1los_3" { TEXT "Zmizel!" }
	SUB "th1mis_1" { TEXT "Nìkdo si zahrává s mımi penìzi!" }
	SUB "th1mis_2" { TEXT "Hej, kam se to sakra podìlo?" }
	SUB "th1rbod1" { TEXT "Nìkdo u se dostal k Trogovi! Nebuïme další na øadì." }
	SUB "th1rbod2" { TEXT "V okolí je vrah! Nepolevuj v ostraitosti!" }
	SUB "th1rbod3" { TEXT "Tìla se zaèínají hromadit." }
	SUB "th1rint1" { TEXT "Mìj oèi na stopkách! Nìco se dìje!" }
	SUB "th1rint2" { TEXT "Situace je napjatá! Buï ve støehu." }
	SUB "th1rint3" { TEXT "Zùstaòte ve støehu! Nìkdo nìco chystá." }
	SUB "th1rmis1" { TEXT "Nìkdo zaèíná bıt chamtivı. Dávej pozor!" }
	SUB "th1rmis2" { TEXT "Mají naše vìci!" }
	SUB "th1rmis3" { TEXT "Váza je pryè! Bude to ošklivé!" }
	SUB "th1roth1" { TEXT "Buïte ve støehu! Nìco se dìje!" }
	SUB "th1roth2" { TEXT "Máme tu vetøelce! Jsem si tím jistı." }
	SUB "th1runa1" { TEXT "Stráe, sem!" }
	SUB "th1runa2" { TEXT "Stráe! To je Garrett! Chyte ho!" }
	SUB "th1runa3" { TEXT "Vydali jsme vetøelce!" }
	SUB "th1sec_1" { TEXT "Šmejdí tu nìkdo, kdo nemá!" }
	SUB "th1sec_2" { TEXT "Urèitì tu máme vetøelce!" }
	SUB "th1sma_2" { TEXT "Hej, co je tohle?" }
	SUB "th1sma_3" { TEXT "Tohle není v poøádku." }
	SUB "th1sma_4" { TEXT "O-ou... cítím problém!" }
	SUB "th1telc1" { TEXT "Našel jsem ho!" }
	SUB "th1telc2" { TEXT "Hej, tady je!" }
    SUB "th1telc3" { TEXT "Rychle, utíká pryè!" }
	SUB "th1telr1" { TEXT "Hej, mám tu vetøelce!" }
	SUB "th1telr2" { TEXT "Pojï sem! Je to Garrett!" }
	SUB "th1telr3" { TEXT "Zahlédl jsem ho!" }
	SUB "th1telr4" { TEXT "Hej, je tady!" }
	SUB "th1telr5" { TEXT "Garrett je uvnitø komplexu!" }
} 
